### ISSUE TITLE
Limit pre-seeded ether to more realistic quantities

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#111]
## Expected Behavior

TestRPC will often be used to develop Dapps, with clients like MetaMask, which needs to render account states realistically.
## Current Behavior

Currently our formatting is thrown off with testrpc's 20-digit base-10 account balances.
## Possible Solution

Right now there's only 18 million ether in existence, so we can safely assume account balances will be no more than 7 digits, so I recommend testrpc does this in turn.
## Context

Right now I'm trying to come up with an account view format that looks good with impossible 20 digit balances, and it seems a little silly.

**Comment by tcoulter** [comment]
@flyswatter Check it: https://github.com/ethereumjs/testrpc/pull/109

Considering this a dupe of #109. Let me know if this fits in with your desires. This PR would put the default balance at 1000 ETH for each account.

**Comment by danfinlay** [comment]
Well _that's_ nice!  Thanks!
