### ISSUE TITLE
error while running testrpc on ubuntu

### ISSUE THREAD

**Issue by hasanqusay** [ConsenSys-archive/ganache-cli-archive#114]
i successfully installed testrpc but when I run it I get an error 

http://imgur.com/a/ePUi7

I have node version 5.x and npm version 3.8

truffle is running normally but obviously I can't deploy because testrpc isn't running

**Comment by SilentCicero** [comment]
Try installing `memdown`: https://www.npmjs.com/package/memdown

```
npm install memdown
```

Also, is your NPM globals configured correctly?

See https://github.com/iurimatias/embark-framework#eaccess-error -- for details/fix.

**Comment by tcoulter** [comment]
Thanks @SilentCicero. Often I've found npm doesn't install everything on the first try, like it should. Can you try reinstalling the testrpc and see what happens? I know that sounds rather pathological, but it has always solved it for me.

I'm going to close this. Please reopen if you have an issue.
