### ISSUE TITLE
CallStackDepthLimit is far less than 1024

### ISSUE THREAD

**Issue by lastperson** [ConsenSys-archive/ganache-cli-archive#115]
## Expected Behavior

Performing an internal transaction calls over and over again recursively should fail on 1024th call. Works so in browser-solidity.
## Current Behavior

Currently I wasn't able to get deeper than 181 using testrpc. This number seems to be dependent on vm state.
## Possible Solution

Check why the browser-solidity allows 1024 call stack size.
## Steps to Reproduce (for bugs)

``` js
contract Depth {
    event StackDepthLimitReached(uint16 depth);
    function callStackDepth(uint16 _depth) {
        if (!this.call(0xd76f6606, _depth + 1)) {
            StackDepthLimitReached(_depth);
        }
    }
}
```
1. Deploy the contract;
2. Do `var tx = depth.callStackDepth(0, {from: web3.eth.accounts[0]});`;
3. Do `web3.toDecimal(web3.eth.getTransactionReceipt(tx).logs[0].data)`.
## Context

I'm writing tests that asserts correct behavior in case of stack depth limit reached. In order to do that I needed to find the testrpc depth limit for my particular case and use it in the test, but I think it will be much more convenient to test on proper depths.
## Your Environment
- Version used: 1.0.9
- Operating System and version: Ubuntu 14.04 LTS

**Comment by davidmurdoch** [comment]
EIP-150 introduces "all but one 64th" for child calls which causes the the stack limit for CALL (and others) to be < 1024.

I'm currently writing tests to verify call stack depth limits under EIP-150 which should be merged shortly.
