### ISSUE TITLE
Pathological performance with large numbers of contract calls

### ISSUE THREAD

**Issue by PeterBorah** [ConsenSys-archive/ganache-cli-archive#117]
A transaction with thousands of contract calls can easily fit in the gas limit, but causes testrpc to work extremely slowly. The slow performance is made worse if you are doing a `call`, rather than a `sendTransaction`.
## Expected Behavior

Transactions that fit within the gas limit should, at minimum, not take longer to process than the current Ethereum block time.
## Current Behavior

A `call` on a transaction that costs ~3M gas can take more than a minute on my machine.
## Steps to Reproduce (for bugs)

Here's a minimal example:

```
contract Doubler {
  function invoke(uint n) returns(uint) {
    return 2 * n;
  }
}

import "doubler.sol";
contract ManyCaller {
  Doubler doubler;

  function ManyCaller() {
    doubler = new Doubler();
  }

  function runCalls(uint numCalls) {
    for (uint i = 0; i < numCalls; i++) {
      doubler.invoke(3);
    }
  }
}
```

When run with the following Truffle test, it costs 3038664 gas, and takes ~33 seconds on my machine.

```
it("should take forever", function(done) {
  many_caller = ManyCaller.deployed();
  many_caller.runCalls(7000).then(function() { done(); }).catch(done);
});
```

Changing the test to the following causes it to take ~63 seconds on my machine. (The only difference is using `.call` instead of `sendTransaction`.)

```
it("should take forever", function(done) {
  many_caller = ManyCaller.deployed();
  many_caller.runCalls.call(7000).then(function() { done(); }).catch(done);
});
```
## Context

I ran across this while playing around with implementing map and reduce for Ethereum arrays. This is not a practical pattern or one I actually intend to use, and so I am not immediately affected by this issue.
## Your Environment

OS X El Capitan (10.11.5)
MacBook Pro (Retina, 13-inch, Late 2013)
2.4 GHz Intel Core i5
8 GB 1600 MHz DDR3

TestRPC v2.0.9
Truffle v1.0.3

"In the wild" example: https://github.com/PeterBorah/ethereum_experiments/blob/cbda2dcaf84b5fa29509fe7ebe82f92688737375/test/list.js#L121

**Comment by benjamincburns** [comment]
A long time has passed since this bug was raised. Adding this to the list of things which need revalidation.

I vaguely recall reading that calling out to other contracts from within a for loop is somewhat of a performance problem in the EVM in general, but I could be just making things up here...

**Comment by mikeseese** [comment]
I'm going to close this due to inactivity.

If this begins to become an issue for anyone again, please open another issue. Thanks!
