### ISSUE TITLE
event listening web3.js notation changes logging behavior for contract factory methods

### ISSUE THREAD

**Issue by SilentCicero** [ConsenSys-archive/ganache-cli-archive#118]
## Expected Behavior

I should be able to use either event handling notations (`contractInstance.EventName().get` and `contractInstance.EventName()`) from the web3.js object and TestRPC, however, this does not happen. The result is different.
## Current Behavior

This works:

```
contractInstance.EventName({someFilterVar: someFIlterValue}, (err, result) => {});
```

This does not:

```
contractInstance.EventName({someFilterVar: someFilterValue}).get((err, result) => {});
```
## Possible Solution

I believe this could be due to the way the web3.js object interfaces with the RPC providers and thus TestRPC. I am getting this event problem with both the packed `.provider()` and the `http rpc -> server` providers.
## Steps to Reproduce (for bugs)
1. Setup a Basic contract with Events
2. Deploy the contract to TestRPC
3. Use a method
4. Listen for events with either notation (to see that one works and the other does not)
## Context

This is preventing me from building basic applications with TestRPC. I have to use the one notation, which is fine, however, events dont seem to be functioning properly, causing me a lot of trouble with very basic applications.
## Your Environment
- TestRPC 2.0.9 -- web3.js 15.3
- Ubuntu 64bit, 16gb Ram
## Side Note

I'm having a ton of trouble with events in general. They seem to not fire when they should, and can even crash my node if I listen for too many at a single time. This I believe to be related to issues: 
https://github.com/ethereumjs/testrpc/issues/113

**Comment by tcoulter** [comment]
Hi @SilentCicero, I'm not sure this is an actual bug. I did a bunch of a heavy digging, and had a writeup all ready for you, only to realize that you're performing events in the wrong order. Your steps to reproduce are these:
1. Setup a Basic contract with Events
2. Deploy the contract to TestRPC
3. Use a method
4. Listen for events with either notation (to see that one works and the other does not)

Items 3 and 4 should be reversed - you should start listening before triggering the function that should fire the event.

The reasoning behind this is the TestRPC is so fast that it processes the transaction that occurred in step 3, puts it in a block and moves on to the next block before 4 can start listening. Essentially, what the TestRPC has done is exposed a race condition in your application. On geth, where there's a significant block time between sending a transaction and that transaction being processed, you're not likely to notice - i.e., the block likely won't be processed before you start listening. However, with the TestRPC, you're listening **after** you've already "made a sound", we'll say. Which doesn't make sense right? :) 

So if you want to write code that works on both geth and the TestRPC, swap items 3 and 4. This not only gives you the benefit of being able to use both, but it also makes your code hold up logically: Start listening first, then make a noise. 

Cheers!

**Comment by tcoulter** [comment]
The more in-depth answer would have included that, when step 4 occurs, web3 calls `eth_newFilter` without any parameters, which means the new filter starts from the latest block. Note that the transaction in step 3 was processed in the **previous** block, so the event in step 4 wouldn't even be looking for it.
