### ISSUE TITLE
getTransaction/getTransactionReceipt returns null

### ISSUE THREAD

**Issue by BlockChange** [ConsenSys-archive/ganache-cli-archive#121]
I'm trying to get Transaction info with `getTransaction` by `hash` (https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransaction)

with `web3` in browser:

```
 web3.eth.getTransactionReceipt(transactionHash, function(transaction) {
    console.info(transaction);    
  })
```

But it returns `null`

The `transactionHash` is retrieved when I do a transaction via `ether-pudding`:

```
Things.load(Pudding)
var things = Things.deployed()

things.sendThing(destinationAccountId, amount, {from: accountId}).then(function(hash) {
   ...
}
```

I would assume that hash I get back would return the exact transaction. I've tried other hashes from blocks I get directly with `web3.eth.getBlockNumber` but those also return `null`

Is the `testrpc` supposed to even return these, or do I have to test this on a `geth` or other live node?

I have the same issue with `getTransactionReceipt`.

Something similar was supposedly fixed a year ago: https://github.com/ethereum/go-ethereum/issues/1473

Other similar issues are not solving this issue: https://github.com/ethereum/web3.js/issues/262 ,  https://github.com/ethereum/go-ethereum/issues/2434
- TestRPC Version: v2.0.8
  Update, same issue on geth:
- geth: 1.4.9-stable

**Comment by tcoulter** [comment]
Thanks for the writeup. First, can you try out the latest TestRPC, which is 2.0.9. Unlikely it fixes your issue, but would be great to know.

The biggest part of this is that getTransactionReceipt and getTransactionByHash are supposed to return `null` when a transaction doesn't exist. So the first step is ensuring the transaction does exist: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash

However, it seems you may have done that, by this comment: 

> I've tried other hashes from blocks I get directly with web3.eth.getBlockNumber but those also return null

Now, we have tests for this, which makes me skeptical it's a bug across the board. However, there might be something more subtle. More information (detailed reproduction steps) as well as code would be very helpful.

Related tests:

https://github.com/ethereumjs/testrpc/blob/master/test/requests.js#L251
https://github.com/ethereumjs/testrpc/blob/master/test/requests.js#L392
https://github.com/ethereumjs/testrpc/blob/master/test/requests.js#L486

Side note: Looks like we don't have any direct tests for getTransactionByHash, but I do believe web3 calls it in the contract tests.

**Comment by BlockChange** [comment]
Ok, so this was totally my fault, since all callbacks give `(err, result)` back, and err is also `null` when there's no error. Even though I read that part of the [docs](https://github.com/ethereum/wiki/wiki/JavaScript-API), I didn't apply it yet.

So correct code would be:

```
 web3.eth.getTransactionReceipt(transactionHash, function(err, transaction) {
    console.info(transaction);    
  })
```
