### ISSUE TITLE
Implement traceTransaction calls for debugging (Remix)

### ISSUE THREAD

**Issue by graup** [ConsenSys-archive/ganache-cli-archive#125]
[Remix](https://github.com/ethereum/remix) is a new debugging tool currently under development. It uses debug calls (`debug_traceTransaction` [and others](https://github.com/ethereum/remix/blob/master/src/util/web3Admin.js)) to retrieve information about a transaction. As far as I can tell, this is not yet supported by testrpc.

On another note, the Solidity compiler [will soon output sourcemaps](https://github.com/ethereum/solidity/issues/713). Should we add support for that for testrpc's `--debug` option? It could automatically show where in the code a invalid jump was thrown, for example.

**Comment by tcoulter** [comment]
This sounds like a great feature. I'm not yet sure how to implement it, but I'll look into it. Thanks! 

PS: If anyone would like to take a crack at it, please do!

**Comment by obo20** [comment]
I would love for this to become an option within remix

**Comment by tcoulter** [comment]
`eth_debugTraceTransaction` is already support in the latest TestRPC! As well, an integrated debugger will be shipped with [Truffle 4.0!](https://github.com/trufflesuite/truffle/releases/tag/v4.0.0-beta.0)

Closing this ticket. Cheers!
