### ISSUE TITLE
Default gas limit for eth_sendTransaction

### ISSUE THREAD

**Issue by axic** [ConsenSys-archive/ganache-cli-archive#130]
Currently the default limit seems to be `4712388` ([see here](https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L378)).

Both the [JSON RPC "spec"](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction) and [geth](https://github.com/ethereum/go-ethereum/blob/667a386d87de64587061c2462773977e8a9dc98a/eth/api.go#L55) use `90000` as the default.

I think `testrpc` should too, so that anyone not supplying their own gas limit during a contract deployment will realise it, even before they get to deal with geth.

**Comment by tcoulter** [comment]
Added to `develop` branch in [this commit](https://github.com/ethereumjs/testrpc/commit/fc0fb4cc728c1eb7df1745120151f9ef8a737584). CC @area. 

Closing.
