### ISSUE TITLE
Testrpc 2.1.0 broke BIP44 compliance

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#131]
Previously, (as recently as `2.0.9`), testrpc's mnemonic and `-m` flag used the BIP44 standard to derive keys, making it compatible with MetaMask, for a really smooth developer experience.
## Expected Behavior

When passing a mnemonic to testrpc, like `testrpc -m "pistol fancy fresh belt always pet tourist walnut crumble have lens inform"`, it should generate BIP44 compliant keys, in this case, account 0 should be `0xDc0eb274099922D49ECFC57263356Ce5fD4cAA9f`.
## Current Behavior

Right now that same mnemonic generates account 0 as `0x47ddf9fc9c7d85f126c4d620fad07abf86063642`.
## Your Environment

Mac OS X 10.11.6
TestRPC 2.1.0
Node.js v6.3.1

**Comment by kumavis** [comment]
cc @digitaldonkey

**Comment by danfinlay** [comment]
[I think I found the commit](https://github.com/ethereumjs/testrpc/commit/101000281052545eb6980c824fa033026dabc789).

**Comment by johnmcdowall** [comment]
@flyswatter I mean, feel free to submit a PR with a test, ya know?

**Comment by johnmcdowall** [comment]
I'm not sure why you're confused @flyswatter. You're original comment that you edited said "Y'all need tests." I'm saying you are more than welcome to help us out by submitting one for this case.

**Comment by axic** [comment]
I believe https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L96 should be:

```
var acct = this.wallet.derivePath(this.wallet_hdpath + '/' + index) // index is a number
```

So that the actual derivation path becomes `m/44'/60'/0'/0/0` and not `m/44'/60'/0'/00`.

**Comment by danfinlay** [comment]
That does it. Preparing a PR now.  Adding it to the original path instead, for less concatenation logic.
