### ISSUE TITLE
Error: Cannot find module './build/Release/scrypt'

### ISSUE THREAD

**Issue by pubkey** [ConsenSys-archive/ganache-cli-archive#134]
I simply created a nodejs-file with the following content:

``` javascript
var Web3 = require('web3');
var web3 = new Web3();
var TestRPC = require('ethereumjs-testrpc');
web3.setProvider(TestRPC.provider());
```

testrpc version: 2.1.0
nodejs version: 6.2.2
gcc version     : 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1) 
os                   : Linux Mint 18 Sarah
## Expected Behavior

it should just do nothing but also not give errors.
## Current Behavior

```
module.js:442
    throw err;
    ^
Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/[myusername]/Desktop/testRPC/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/scrypt.js/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```
## Possible Solution

It seems the problem comes with ethereumjs-wallet
## Steps to Reproduce (for bugs)
1. create the javascript-file with the shown content
2. install web3, ethereumsjs-testrpc
3. run the file with nodejs

**Comment by tcoulter** [comment]
It looks like this is your issue. Give this a shot and reopen if it doesn't work. https://github.com/barrysteyn/node-scrypt/issues/108

**Comment by tcoulter** [comment]
More direct link: https://github.com/barrysteyn/node-scrypt/issues/108#issuecomment-156624724

**Comment by BlockChange** [comment]
Just to add, I tried the above, didn't work (maybe it helped)

I fixed it by adding `--unsafe-perm` when installing:

`sudo npm install --unsafe-perm --verbose -g ethereumjs-testrpc`

Because I got this error:

`WARN EACCES user “root” does not have permission to access the dev dir`

**Comment by pubkey** [comment]
I actually just switched to nodejs v 6.2.2 and reinstalled all modules.
The problem came with v4.4.7 and with any other version because I installed it with the 4.x version.

**Comment by witwiki** [comment]
Just thought I'd add to this as I came across the same problem.

Solution suggested by @tcoulter didn't seem to work for me. 
Solution suggested by @BlockChange **_worked**_ for me.

I did not try @danielsun174 's solution.

Thanks everyone :+1:

**Comment by Honghe** [comment]
Environment: node v4.5.0
Occur the same problem.
Follow @BlockChange `--unsafe-perm` work for me.
`sudo npm install --unsafe-perm -g ethereumjs-testrpc`

But what's the reason causes this problem?

**Comment by chevdor** [comment]
Just to confirm that this issue went away for me switching from node 4.2.2 to 6.2.2

**Comment by DirkRay** [comment]
I meet it also,and I have used `sudo npm install --unsafe-perm --verbose -g ethereumjs-testrpc`.But nothing happen.Who can help me?

**Comment by pubkey** [comment]
@woaiyaomai   Which node version do you have?

**Comment by dendej** [comment]
My system is Mac OSX. The workaround I got is
1. install "scrypt" manually ("sudo npm install -g scrypt")
2. go to "ethereum-testrpc module folder"/node_modules/scrypt
3. make a symbolic link to scrypt build folder e.g. "ln -s /usr/local/lib/node_modules/scrypt/build"

Hope this is helpful

**Comment by dappaule** [comment]
thanks dendej, worked for me

**Comment by alxiong** [comment]
**Ubuntu: 16.04,
Node: 8.1.0,**

I used to have the same issue when installing testrpc, what I did and actually worked were the following:
1. install node version manager[(nvm)](https://github.com/creationix/nvm) , 
 `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash`
then
`export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm`
then test nvm installation:
`command -v nvm` which should output `nvm` if successful. 
then what i did was using nvm long term support version (lts):
`nvm install --lts
nvm use --lts`
Now, if you type `node -v`, bash should read`v6.11.0` 
(additionally, you could check your all node version you installed by using 
`nvm ls`
and you could set long term support version as default using 
`nvm alias defaults lts/*`)

2. navigate directory to `node_modules` using `cd` (location may various, depending on where you install node previously), there should be some folders like `scrypt` , `nan` etc. 
what i did was erase everything using `sudo rm -rf /home/<myusername>/node_modules/*`
**(be very careful about this step, It works for me, but please make sure you know what you are doing before deleting)**

3. Final step was reinstalling using the original:
`sudo npm install -g truffle ethereumjs-testrpc`

And everything works like magic. Of course, you could test by typing `testrpc` and bash should give you 10 available accounts and their respective private keys. and typing 'truffle' and bash should give you a hint of list of available command. 

This problem hunts me for two days. And finally with the help of my colleague and smart choice of a total **re-installation and downgrade of node version**, the problem has been finally solved. 

Hopefully it helps! Cheers!

**Comment by axelhodler** [comment]
occured using __node v8.2.1__ after adding/installing an explicit dependency to `web3` when `ethereumjs-testrpc` was already present and installed as a dependency.

throwing away `node_modules` and going for `npm i` afterwards fixed the issue.

**Comment by OR13** [comment]
I get this same error when including web3 in typescript library and running jest tests.

It seems that jest module resolver is getting lost when traversing web3 dependencies...

```
 FAIL  src/MetaCoinAPI/MetaCoinAPI.spec.ts
  ● Test suite failed to run

    Cannot find module './build/Release/scrypt' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/web3/packages/web3-eth/node_modules/web3-eth-accounts/node_modules/scrypt/index.js:3:20)
```

**Comment by fraylopez** [comment]
I had this issue on windows 10 too. Fixed by installing Visual C++ 2015 Build Tools through Visual Studio, then deleting `node_modules ` and `npm i` made the trick.

**Comment by ColdFire87** [comment]
On Windows 7 x64, Node v8.9.3:
1. delete `node_modules` folder
2. start an elevated command prompt (run as administrator)
3. install build tools: `npm install --global --production windows-build-tools`
4. run `npm install` which will use the build tools to compile scrypt

NOTE: `npm install` must be run from the same elevated command prompt (compiling scrypt without admin rights will fail).

**Comment by confused1108** [comment]
May be this was just with me:
I was using const ganache=require('ganache');

which was giving me this error
It is actually require('ganache-cli');

Silly mistake but it fixed

**Comment by PeterLinX** [comment]
open /usr/local/lib/node_modules/remix-ide/node_modules/scrypt/index.js and change it to 
 require("./build/Release/scrypt")改为require("scrypt"), problem solved.

**Comment by yairmark** [comment]
I had this issue with a fresh install of Ubuntu 19.04. The issue was caused by node-gyp failing higher up in the process as it needs python2.7 which is easily fixed:

```bash
sudo apt install python2.7
sudo ln -s /usr/bin/python2.7 /usr/bin/python
```

Restart your shell or source your `.bashrc` and the issue should be sorted.

**Comment by sudhiryadav** [comment]
change this line require("./build/Release/scrypt") to require("scrypt") from '/node_modules/scrypt/index.js'

**Comment by yazinsai** [comment]
@sudhiryadav can confirm this worked for me, thanks!

**Comment by inje** [comment]
You can also run this and it should fix the issue:
`sed -i -e 's/.\\/build\\/Release\\/scrypt/scrypt/' node_modules/scrypt/index.js`

**Comment by nolanjacobson** [comment]
Create a `patch-scrypt.js` file and add the following contents to it

```const replace = require('replace-in-file')
const options = {
  files: './node_modules/scrypt/index.js',
  from: /\.\/build\/Release\/scrypt/g,
  to: 'scrypt'
}

replace(options)
  .then(results => {
    console.log('Replacement results:', results)
  })
  .catch(error => {
    console.error('Error occurred:', error)
  })
```
After adding the above content to the file, run `node ./patch-scrypt.js`
