### ISSUE TITLE
eth_newFilter does not filter events properly

### ISSUE THREAD

**Issue by zihehuang** [ConsenSys-archive/ganache-cli-archive#135]
When using the filter function, testrpc grabs all events instead of events from a specific contract address.
## Expected Behavior

When a new filter is created with the parameters like following:
`{"fromBlock":"0x1",
      "toBlock":"latest",
      "address": "0x278d5bd96e443558756b33727112aa43ec98c939",
      "topics":["0xb03a40895f6223867180978a41833156"]}`

When calling `getFilterLogs` with the filter ID should return an array of events that are relevant to the `address`
## Current Behavior

Currently, this feature is broken since calling `getFilterLogs` will give all the events regardless of which contract address you specify. 
## Possible Solution

The current work around is to use Geth instead of testrpc. 
## Steps to Reproduce (for bugs)

1. Deploy contract A wth events
2. Send a transaction to contract A that emits events
3. Deploy contract B with events
4. Send a transaction to contract B that emits events
5. Create a filter and call getFilterLogs
## Your Environment

- Version used: 2.1.0

**Comment by tcoulter** [comment]
Fixed in version 2.2.1. Thanks for the report!
