### ISSUE TITLE
No connections via IPv4 under Ubuntu Linux

### ISSUE THREAD

**Issue by UnSciPreneur** [ConsenSys-archive/ganache-cli-archive#139]
## Expected Behavior

I want to run testrpc on a server and connect to it using IPv4 from my client. Starting it via `testrpc` should spawn a process that listens on port 8545 for IPv4.
## Current Behavior

If I run testrpc the server only listens to port 8545 for the IPv6 protocol. No connection via IPv4 is possible.
Here is the output of `netstat -tulpn |grep 8545`:

tcp6       0      0 :::8545                :::\*                    LISTEN      16568/node    
## Possible Solution

This could be related to https://github.com/nodejs/node-v0.x-archive/issues/9195
## Your Environment

- Version used: EthereumJS TestRPC v2.1.0
- Server type and version: node v6.2.0, npm 3.8.9 
- Operating System and version: Ubuntu 14.04 LTS 64 bit

**Comment by tcoulter** [comment]
I've added a `--hostname` parameter which you can use to set the port the server listens on. This is on master, but will go out with the next release. This should solve your issue. 

I'm going to close this ticket, but please reopen if it doesn't work for you. Cheers!

**Comment by UnSciPreneur** [comment]
Many thanks. That's exactly what I have been looking for.

**Comment by amanuelz91** [comment]
--port <portNumber> will override the default 8545 port setting
