### ISSUE TITLE
Problem with the installation of the latest build

### ISSUE THREAD

**Issue by davidg2202** [ConsenSys-archive/ganache-cli-archive#15]
I have an issue when I try to install the latest build  on windows using the latest version of node.js v5.6.0 
it failed t the secp256k1@2.0.10 install script 'npm run rebuild'
please find attached the log  
I use the following version of node.js and rpm 
node v5.6.0
npm  v3.7.3

I am very new here so my error might be quite simple to resolve 
thanks 

[npm-debug.txt](https://github.com/ethereumjs/testrpc/files/139653/npm-debug.txt)

**Comment by step21** [comment]
same here :-/

**Comment by step21** [comment]
I think it is related to node trying to compile native code, but something not being present like c compiler or headers. example of the same/similar on os x : https://github.com/cryptocoinjs/secp256k1-node/issues/48

**Comment by tcoulter** [comment]
@davidg2202 You're running Windows. Unfortunately that's a platform I've never tried to install on. 

This does look like a problem compiling secp256k1. I'll talk to the maintainer (@wanderer) and see if he has any ideas.

**Comment by tcoulter** [comment]
More information here. Looks like there's steady progress. If there's none soon (i.e., next week) I'll likely pick it up myself. https://github.com/cryptocoinjs/secp256k1-node/issues/20

**Comment by cypher437** [comment]
I had a similar issue with secp256k1, judge if its related.

Windows 10 64bit
npm 3.8.0
node 5.7.1

> gyp ERR! System Windows_NT 10.0.10240
> gyp ERR! command "C:\nodejs\node.exe" "C:\Users\Cypher\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Cypher\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\eth-lightwallet\node_modules\secp256k1
> gyp ERR! node -v v5.7.1
> gyp ERR! node-gyp -v v3.3.0
> npm ERR! Failed at the secp256k1@2.0.10 rebuild script 'node-gyp rebuild'.

I worked on it for a couple of hours. I initially built secp256k1 separately however I found the latest version installed just fine. I then went about installing the individual packages separately from the testrpc package.json list and updating those that failed on a local install which were:

```
    "ethereumjs-util": "^4.0.0"
    "web3-provider-engine": "^6.1.0"
```

After updating those, it appears to be working. I hope that helps shed a little more light on the issue for someone else.

**Comment by tcoulter** [comment]
Unrelated, @FlashDave. But that will be fixed in a day or two. :)

**Comment by tcoulter** [comment]
@FlashDave Whoops, looks like yours was related - I was responding via email. That said, I just bumped testrpc to v1.1.0 which can now be cleanly installed on Windows. Please see the [Windows install guide](https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows) before running `npm install` as there are a few dependencies that need to be manually installed first.

Closing this ticket, as we now support windows! :tada:

**Comment by tcoulter** [comment]
@davidg2202 @step21 @FlashDave Could you guys give 1.1.0 a test after following the [Windows install guide](https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows)? Would love to know if there are other dependencies required that I already have installed but others do now. Cheers!

**Comment by moinakbh** [comment]
Hi,
I am having problems with installing ethereumjs-testrpc in Windows Server 2012 R2/Visual Studio2015 Community Edition/Python2.7.11/OpenSSL. Here is the error I get everytime I run npm:

secp256k1@3.0.1 install D:\stage\ethereumjs-testrpc\testrpc-master\node_modules\secp256k1

> npm run rebuild
> 
> secp256k1@3.0.1 rebuild D:\stage\ethereumjs-testrpc\testrpc-master\node_modules\secp256k1
> node-gyp rebuild

D:\stage\ethereumjs-testrpc\testrpc-master\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\119078\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [D:\stage\ethereumjs-testrpc\testrpc-master\node_modules\secp256k1\build\secp256k1.vcxproj]

Thanks.

**Comment by ResourceHog** [comment]
I too am having this problem
