### ISSUE TITLE
Event.watch cannot receive history events

### ISSUE THREAD

**Issue by libreoscar** [ConsenSys-archive/ganache-cli-archive#156]
`MyContract.event1({fromBlock: 0, toBlock: 'latest'}).watch(handler)`
## Expected Behavior

handler get called with event logs in all block, one by one, chronologically. 
## Current Behavior

handler won't get called with event log in non-latest blocks.
## Possible Solution

Not sure. But please note that `MyContract.allEvents` does not have this bug. The watch handler can receive all history events of MyContract.
## Your Environment

Version used: 2.2.3
Ubuntu 16.04
Mac OS 10.12

**Comment by tcoulter** [comment]
Regarding your expected behavior:

> handler get called with event logs in all block, one by one, chronologically.

I don't think that's how events are supposed to work. Do you have any documentation that shows that the callback is called once per event? Also, can you demonstrate that ethereumjs-testrpc isn't returning the correct events?

**Comment by JMLX42** [comment]
+1 this is a bug.

This won't work with testrpc but works with geth:

``` javascript
  var voterRegisteredEvent = voteInstance.VoterRegistered();
  var voteErrorEvent = voteInstance.VoteError();

  voterRegisteredEvent.watch((err, e) => {
    // never triggered...
  });

  voteErrorEvent.watch((err, e) => {
    // never triggered
  });

  voteInstance.registerVoter.sendTransaction( //...
```

Here is what I get in the testrpc logs:

```
eth_newFilter
eth_newFilter
eth_newFilter
eth_sendTransaction
eth_getFilterLogs
eth_getFilterChanges
eth_getFilterLogs
eth_getFilterLogs
eth_getFilterLogs

  Transaction: 0xda7c3a2382cbf978ee5e4069b2b0b1f3e6a6f2ef0f20d92144aed807496bda4c
  Gas usage: 0xadb9
  Block Number: 0x1a
  Block Time: Mon Oct 10 2016 18:49:40 GMT+0000 (UTC)

eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
...
```

Those `ethègetFilterChanges` never stop and the events are never triggered.

The smart contract is here:

https://github.com/promethe42/cocorico/blob/master/contract/Vote.sol

**Comment by tcoulter** [comment]
Regarding eth_getFilterChanges going on forever: Have you upgraded to TestRPC 3.0 released last week?

**Comment by JMLX42** [comment]
Yes:

```
$ cat /usr/lib/node_modules/ethereumjs-testrpc/package.json 
{
  "name": "ethereumjs-testrpc",
  "version": "3.0.0",
...
```

**Comment by tcoulter** [comment]
@promethe42 Your code is no different from [these tests](https://github.com/ethereumjs/testrpc/blob/master/test/events.js) as far as I can tell. I suspect something else is at play here.

**Comment by JMLX42** [comment]
@tcoulter As far as I can tell, those tests are [triggering events manually on a "local" instance](https://github.com/ethereumjs/testrpc/blob/master/test/events.js#L77):

``` javascript
instance.triggerEvent(5, 6, {from: accounts[0]}, function(err, result) {
```

My events are triggered by the smart contract execution and are listened to using the RPC API on `http://127.0.0.1:8545`.

**Comment by tcoulter** [comment]
These tests are triggered by the smart contract execution as well. In the case of the test, `instance` is analogous to your `voteInstance` - it's a contract abstraction that talks to the testrpc, executes contract code on the vm that then triggers events.

> My events are triggered by the smart contract execution and are listen to using the RPC API on http://127.0.0.1:8545.

Regardless of whether or not TestRPC is being used as a server or a library, the same code and API is used to process transactions, so the execution should be no different.

**Comment by JMLX42** [comment]
@tcoulter Here is the whole code if it can help:

https://github.com/promethe42/cocorico/blob/master/blockchain-worker/src/ballot-queue-worker.js#L90

`voterRegisteredEvent` and `voteErrorEvent` are never triggered. Could there be any valid reason for this? 

I'm starting testrpc with this command line:

https://github.com/promethe42/cocorico/blob/feature/api-tests/provisioning/roles/blockchain/templates/blockchain-miner.upstart.conf.j2#L24

Am I missing something?
Could it be the missing gasLimit ? I'm running my local `getth` with a genesis block with a specific gas limit. I'll try running `testrpc` with the same limit and report.

**Update**: setting the gas limit with `--gasLimit` did not fix it.

**Comment by IstoraMandiri** [comment]
related
https://github.com/ethereum/web3.js/issues/509
https://github.com/ethereumjs/testrpc/issues/150

**Comment by dwalintukan** [comment]
I was getting the same issue with `eth_getFilterChanges` repeating endlessly. I solved it by calling `watcher.stopWatching()` at the end of my test:

```
let watcher = testContract.FunctionName().watch((error, response) => {
    /* watch code */
});

/* test code */

watcher.stopWatching();
```

**Comment by monkybrain** [comment]
Any progress here? I'm also unable to return any but the latest triggered events. Seeing as the event log is a very cheap form of storage I find it critical to develop good dApps. Would be nice to able to test this functionality with testrpc.

**Comment by benjamincburns** [comment]
@libreoscar are you sure that code is correct? in our test, we show the `{fromBlock ...` as the _second_ argument to the web3 event... Perhaps this is the problem?

cc @monkybrain

**Comment by khaschuluu** [comment]
Same here. I runs my RPC on geth in Google Cloud by following command:
`$ geth --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0" --cache=1024`
But my listener isn't tirggers:
```
          var fltr = web3.eth.filter({fromBlock: 4363762, toBlock: 'pending', address: '0xF8967e9d70B6BdA12eD5db727c2D55C004564046'});
          fltr.get(function(err, res) {
            console.log('egereg get: ', err || res);
          });

          fltr.watch(function(err, res) {
            console.log('egereg watch: ', err || res);
          });
```

**Comment by mikeseese** [comment]
Closing as this doesn't seem to be an issue anymore. Our tests ensure this works.
