### ISSUE TITLE
testrpc always creates exactly 10 accounts upon startup

### ISSUE THREAD

**Issue by ephemeralriggs** [ConsenSys-archive/ganache-cli-archive#157]
The "-a" option does not seem to change the number of accounts created on startup 
## Expected Behavior

Running "testrpc -a 100" creates 100 accounts at startup
## Current Behavior

Running "testrpc -a 100" creates 10 accounts at startup. Omitting "-a 100" also creates 10 accounts at startup.
## Steps to Reproduce (for bugs)
1. Run "testrpc -a 100"
2. Observe / verify by attaching a console that only 10 accounts are available

**Comment by davebryson** [comment]
The problem is here: 

https://github.com/ethereumjs/testrpc/blob/master/lib/statemanager.js#L61

`this.total_accounts` is always null.  It should be `options.total_accounts`:

``` javascript
var total_accounts = options.total_accounts || 10;
```

This fixes the problem

**Comment by chevdor** [comment]
I noticed that issue and included the fix into PR #165.
Once the PR is merged, `testrpc -t 100` will have the expected result.

**Comment by chevdor** [comment]
PR #167 also improves that. With it, you can specify a single account (with as much ETH as you wish) and let testrpc create a bunch of addresses for you. Samples in the PR comments.

**Comment by chevdor** [comment]
By the way @riggs-, I was very confused as well as the doc did not match the code but here is how the options work:
- -a / --account is to provide a list of accounts (not a number)
- -t / --total_accounts is the number of accounts you want.

Once my PRs are merged, you can use the `--help` option to remember and `-t 100` to get what you need.

**Comment by ephemeralriggs** [comment]
Thanks for helping and investigating. I hope the pull requests solving the problem will be merged soon. For now I can live with a locally patched testrpc, but eventually this should make it into the next release.

**Comment by chevdor** [comment]
@riggs- I am very confused atm regarding the options but if you test with 3.0.0, the -a flag will work as you expect it to work (unlike what I wrote above).

**Comment by benjamincburns** [comment]
Fixed by `-a` in current version.
