### ISSUE TITLE
eth_estimateGas out of gas exception when setting a variable to 0 in a contract

### ISSUE THREAD

**Issue by tokyo3** [ConsenSys-archive/ganache-cli-archive#158]
## Expected Behavior

return the estimated gas amount

## Current Behavior

an exception ocurrs which can interrupt the transaction flow when the expected value is not returned for example when using metamask

## Steps to Reproduce (for bugs)

the following contract on browser-solidity with metamask throws the exception when unsetX() is called after x being set

```
contract exTest {
  uint x;
  function setX() {
      x = 1;
  }
  function unsetX() {
      x = 0;
  }
}

```

```
Error: Error: VM Exception while executing eth_estimateGas: out of gas
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:124:17
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:59:5
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:726:13
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:52:16
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:269:32
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:44:16
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:723:17
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:167:37
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:55:9
    at /home/user/node-v4.4.7-linux-x64/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/cache.js:107:7
```
## Your Environment

browser-solidity 
testrpc 2.2.4
metamask

**Comment by redsquirrel** [comment]
I'm seeing something similar. Same stack trace... same error. Inexplicably running out of gas on `estimateGas`. 😞

**Comment by chevdor** [comment]
Indeed...
I tried with 3.0.0 and I see the same error.

https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.2+commit.af6afb04.js&optimize=true&gist=e9c76a6462cae8a19a6a339f9e6815af

I deployed against testrpc, it works fine.
Calling unset and then set **does** work.
Calling set and then unset returns indeed the error mentioned above.

**Comment by chevdor** [comment]
I don´t get the issue 100% of the time

**Comment by tokyo3** [comment]
you should get the exception when setting a value to 0 from other value different than 0, the default value for an uint when it's declared is 0, that is why calling unset first and then setting the value to 1 doesn't throw the exception, which is equivalent to setting the value of x from 0 to 0, and then to 1. 

I think the issue is related to the gas refund that is made when a variable gets [deleted](https://solidity.readthedocs.org/en/latest/types.html#delete) which is equivalent to setting a variable with existing data to 0. you can get the same exception if you change "x=0;" to "delete x;" in the unsetX() function, in some way the EVM considers 0 to be an empty variable.

in the EVM a gas refund is made when selfdestruct or delete on existing data is made, the OPCODE when you delete a variable is STORAGEKILL and it should refund a gas value of -15000, there is some info about this here: http://ethereum.stackexchange.com/questions/540/what-type-of-operations-have-negative-gas-costs

**Comment by benjamincburns** [comment]
I _think_ this is likely expected behavior. @tokyo3 Do you still consider this a problem?

Bear in mind that `eth_estimateGas` is intended to behave essentially identical to `eth_call`, so you need to set a gas limit, and this gas limit will be obeyed. In TestRPC we actually process the call, and just return the amount of gas used rather than using a heuristic which might be inaccurate.

@tokyo3 if this doesn't answer your question or if you think there' still a bug, please reopen.

**Comment by chris-shyft** [comment]
One of the issues with this is that when you use Remix connected to ganache-cli, it will throw a "VM Exception while processing transaction: out of gas" error instead of processing the function (at all).
