### ISSUE TITLE
error while installing testrpc

### ISSUE THREAD

**Issue by coderwithattitude** [ConsenSys-archive/ganache-cli-archive#160]
Trying to install testrpc and keep getting this error
## Current Behavior

.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB
8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version
in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\user\AppDa
ta\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\copied_files.vcxproj]
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB
8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version
in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\user\AppDa
ta\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\scrypt_wrapper.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\
build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_
modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
C:\Users\user\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\npm
-cli.js" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v6.3.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log
npm ERR! code 1
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by jmdfm** [comment]
The error output clearly shows: 

`The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version`

Do you have Windows SDK version 8.1 installed?

**Comment by tcoulter** [comment]
Can you give the TestRPC `beta` a try? First uninstall the normal one, if installed (or partially installed):

```
$ npm uninstall -g ethereumjs-testrpc
```

And then install the beta version: 

```
$ npm install -g ethereumjs-testrpc
```

The beta version significantly improves installation and should bypass your installation issues. 

Since this is a beta version, I'd very much appreciate feedback on how it works for you and if you run into any errors during use.

**Comment by jjc12** [comment]
`$ npm install -g ethereumjs-testrpc` worked. Can we close this now?

**Comment by benjamincburns** [comment]
Please reopen if this is an issue in the latest version.
