### ISSUE TITLE
Following contract events freezes browser

### ISSUE THREAD

**Issue by madvas** [ConsenSys-archive/ganache-cli-archive#168]
Hi, 

I posted this issue on web3.js first, but then I found out it's actually `testrpc` issue. Please see 
https://github.com/ethereum/web3.js/issues/495. Or maybe it's not, I don't know, but this happens only on `testrpc` network, not normal one

**Comment by chevdor** [comment]
Can you mention what version of testrpc you used? 
You may want to test again, v3.0.0 is out so it would be interesting to know whether or not you still run into the issue.

**Comment by madvas** [comment]
Looks like issue disappeared in v3.0.0. Thanks!
