### ISSUE TITLE
Bump solidity compiler version to ^0.4

### ISSUE THREAD

**Issue by tymat** [ConsenSys-archive/ganache-cli-archive#169]
## Expected Behavior

testrpc eth_compileSolidity should track latest version of solidity ^0.4
## Current Behavior

testrpc eth_compileSolidity uses older version of solidity which does not support `pragma` annotation.
## Possible Solution

Update to latest solc.js library
## Steps to Reproduce (for bugs)

Compile the following:

```
pragma solidity ^0.4.0;

library MyTestLibrary {
  function testFunction(uint256 a, uint256 b) returns (bool success) {
    success = true;
    return success;
  }
}
```
## Context

TestRPC is a very useful tool for development and testing of Solidity contracts.  It should support the latest solidity versions which is continuously being improved with each version release.

**Comment by tcoulter** [comment]
Partially fixed on `develop`. Requires [this PR in the provider engine](https://github.com/MetaMask/provider-engine/pull/86) to be merged and a provider engine version bump.
