### ISSUE TITLE
--accounts flag broken in 2.2.7 ?

### ISSUE THREAD

**Issue by Bunjin** [ConsenSys-archive/ganache-cli-archive#171]
testrpc --accounts 100 

(or any other number) creates only 10 accounts

this behavior is seen on ubuntu 14 and ubuntu 16

it worked 2 months ago when I used another version of testrpc.

**Comment by Bunjin** [comment]
please pull the fix :)
https://github.com/ethereumjs/testrpc/pull/165/files

I implemented it by hand locally and "testrpc -t 100" works as intended

**Comment by chevdor** [comment]
There are currently some confusion about the flags. There is no technical problem but to chose which flag does what.

The issue you report is known and has been fixed.

Some details:
- use `-a N`to get N accounts
- use --accounts "<privateKey>,<balance>" to generate a specific account

Feel free to follow the situation in #165.
For now, if you use `-a 100`, it should work. If so, please close the issue and follow up in #165.
