### ISSUE TITLE
Gas limit seems to not be considered

### ISSUE THREAD

**Issue by chevdor** [ConsenSys-archive/ganache-cli-archive#178]
Using v3.0.0, started with a gas limit set at 5800000:
`testrpc -d -t 3 --account="0x558ad1........94101a5926c9, 100..." --account="0x558ad19776d....26c8, 100..." -l 5800000`
## Expected Behavior

Provided limit should be applied.
## Current Behavior

Limit seems to be ignored and use the new default: 90000

```
Available Accounts
==================
(0) 0x139f459f164a2c96114f2d08638c12b2c4a74037 🔓  - 100 ETH
(1) 0xe18593cba7a64aca8532bf71b6f3c13681774d86 🔓  - 100 ETH

Private Keys
==================
(0) 558ad19776d1eb5289118bf70cc2b6c3e8abd925b1e3cf64fbc894101a5926c9
(1) 558ad19776d1eb5289118bf70cc2b6c3e8abd925b1e3cfd4fbc894101a5926c9

Gas Limit
==================
5800000                                                   <== OK, that´s what I requested

Listening on localhost:8545
<...>
eth_accounts
eth_sendTransaction

  Transaction: 0x3b26242e3e7e3283cf8270b6318f96b89eee83e1bd96459fa23fcdcbb8bc16ab
  Contract created: 0x6893cb1d8a837d01677871a0699b65dc45acc424
  Gas usage: 0x015f90                                     <== Not OK, that´s 90000
  Block Number: 0x01
  Block Time: Fri Oct 07 2016 21:16:23 GMT+0200 (CEST)
  Runtime Error: out of gas
```

**Comment by tcoulter** [comment]
Hi @chevdor. That flag sets the block gas limit and not the transaction gas
limit. If you want your transactions to have a higher gas limit, you should
specify that in the transaction request.

**Comment by chevdor** [comment]
Yep, I just saw that in https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L45

I opened [an issue](https://github.com/ConsenSys/truffle-solidity-loader/issues/5) in the webpack solidity-loader. That´s where the the gas limit for the tx should be defined, does not it?

I can run the migrations using `truffle migrate` but webpack fails.

**Comment by chevdor** [comment]
I did not submit a PR for that but I made a change to customize the tx gas limit:
https://github.com/chevdor/testrpc/commit/0b53b178f948e0a6c90b0cdaa24f914d4800d1ef

That is a working workaround for me atm.

I think we can close this issue. Let me know if the change can be interesting and I can put together a clean PR for it.

**Comment by axic** [comment]
@chevdor I do not think it is a good idea to override the default tx gas limit. Dapps should specify the gas limit for each of the calls they make. (This is how it works with real clients too, such as geth/parity.)

**Comment by chevdor** [comment]
I agree with you @axic, this is just a workaround.
I currently have an issue with the solidity-loader for webpack (see link above) that probably does not pass the gas as it should. So for now, this fix is the only option I have. Now, I agree that we may not want to add this feature, this is why I did not make a PR.

Hopefully the solidity-loader issue can be fixed soon, making this obsolete. In the meantime, I have at least this solution and I wanted to document a bit for the people who may run into the same issue.
