### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by axic** [ConsenSys-archive/ganache-cli-archive#182]
The license of testrpc is ambiguous at this moment:
- `LICENSE` specifies MIT
- `README.md` specifies MPL2.0
- `package.json` is lacking a license field

It would be useful deciding on a license :)

Update: `LICENSE` is there since the first commit and MPL2.0 was introduced via a README change: https://github.com/ethereumjs/testrpc/commit/ee7933b42b102a742bb22dbd7d1f2c1cc0192c49. Therefore it seems the whole repository is MIT?

**Comment by tcoulter** [comment]
@wanderer What's ethereumjs's official license?

The whole repository is likely MIT right now, but it looks like we might need to relicense to MPL2.0 to be in line with ethereumjs. Good catch.

**Comment by axic** [comment]
It would be quite a chore relicensing to MPL2.0 as you'd need to ask every* contributor to testrpc.

**Comment by wanderer** [comment]
@tcoulter its at the authors discussion

**Comment by benjamincburns** [comment]
From talking to @tcoulter I think that it was a mistake to have committed the MPL license to the README. Given that the LICENSE file was there from the start and that this came later, adding a license conflict, I think it's fair to resolve this conflict by updating the notice in the README to be aligned with the LICENSE file. I'll take this one on.

**Comment by benjamincburns** [comment]
Fixed as of a85c95a.

Also took care of ganache-core in [trufflesuite/ganache-core/3faf4ac](https://github.com/trufflesuite/ganache-core/commit/3faf4ac71441e9e1a3ff5ccd912ffccd625ddf2c).
