### ISSUE TITLE
testrpc can't work!The  console echos "<generator object main at 0x7ff478828370>".Detail in post.

### ISSUE THREAD

**Issue by Aireed** [ConsenSys-archive/ganache-cli-archive#186]
npm: v3.10.8
node: v6.8.1
ubuntu: Linux ls017 3.16.0-67-generic #87~14.04.1-Ubuntu SMP Fri Mar 11 00:26:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

i use cmd " npm install -g ethereumjs-testrpc" to install testpc.
![testrpc_issue](https://cloud.githubusercontent.com/assets/8862395/19591724/f4523180-97aa-11e6-8aa9-7538c02de7d2.png)

**Comment by benjamincburns** [comment]
I think this is no longer relevant in latest version. Please reopen if I've missed something.
