### ISSUE TITLE
Uncaught ReferenceError: blockNumber is not defined

### ISSUE THREAD

**Issue by derektiffany** [ConsenSys-archive/ganache-cli-archive#187]
The following error is being thrown:

```
ReferenceError: blockNumber is not defined
    at async.series.previousBlockHash (/node_modules/ethereumjs-testrpc/lib/subproviders/delayedblockfilter.js:74:13)
    at /node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I do not have a simple test case to reliably throw this error.  However, see the following [code](https://github.com/ethereumjs/testrpc/blob/master/lib/subproviders/delayedblockfilter.js#L41):

```
DelayedBlockFilter.prototype.handleGetFilterChanges = function(payload, next, end) {
  // ...
        if (result.length != 0) {
          // blockNumber does not get declared
          c();
        } else {
          // blockNumber gets declared
          c();
        }
      function(c) {
        if (blockNumber) return c();
      }
}
```

I have a test project which:
1. Deploys several libraries
2. Deploys several contracts (using web3 [.new](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract) with constructor parameters).
3. Uses default testrpc initialization (auto-mining, etc.)

The above error is reliably thrown, though exactly when it is thrown is a bit unpredictable.

 

## Expected Behavior

ReferenceErrors should not be thrown.  Variables should be declared (and / or the error appropriately caught).
## Current Behavior

```
ReferenceError: blockNumber is not defined
    at async.series.previousBlockHash (/node_modules/ethereumjs-testrpc/lib/subproviders/delayedblockfilter.js:74:13)
    at /node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
## Possible Solution

See pull request #183 
## Steps to Reproduce (for bugs)

Error thrown from [delayedblockfilter](https://github.com/ethereumjs/testrpc/blob/master/lib/subproviders/delayedblockfilter.js#L57) when `result.legth != 0`

```
        if (result.length != 0) {
          // blockNumber does not get declared
          c();
        } else {
          // blockNumber gets declared
          c();
        }
      function(c) {
        if (blockNumber) return c();
      }
```
## Context

I have a test project which:
1. Deploys several libraries
2. Deploys several contracts (using web3 [.new](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract) with constructor parameters).
3. Uses default testrpc initialization (auto-mining, etc.)

The above error is reliably thrown, though exactly when it is thrown is a bit unpredictable.

I have not tried changing the project to use a raw `sendTransaction` or some other method that avoids using the web3 [checkForContractAddress](https://github.com/ethereum/web3.js/blob/e4eb9606aa0aa10fd3eeb0a5e5d67c4fff43e814/lib/web3/contract.js#L96) , nor have I tried playing around with testrpc settings, so, perhaps there could be work-arounds.
## Your Environment

- Version used: 3.0.0 (project works under previous versions of testrpc)
- Operating System and version: Multiple, replicated on Mac OS X Yosemite, Windows 10, and Ubuntu.  Generally node v4.5.0 and web3@0.16.0 though the error appears reproducible across multiple OS/dependencies.

**Comment by derektiffany** [comment]
## Workaround

Changing from [Contract.new](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract) to using [.sendTransaction](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction) (which requires encoding any constructor arguments) in tests also appeared to resolve the issue.

**Comment by jmdfm** [comment]
Closing as the PR was merged: https://github.com/ethereumjs/testrpc/pull/183
