### ISSUE TITLE
Installing instruction of ethereumjs-rpc lost the part of installing node.js

### ISSUE THREAD

**Issue by franklili** [ConsenSys-archive/ganache-cli-archive#192]
In the Installing instruction of ethereumjs-rpc , there lost the part of installing instruction of node.js.
## Expected Behavior

Add installing instruction of node.js in the Installing instruction of ethereumjs-rpc .

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by jmdfm** [comment]
It's not clear what you're saying the issue is here. The README clearly states this is a project written in Node and distributed via npm - both tools have extensive installation instructions on their websites.
