### ISSUE TITLE
I can not open Http server.

### ISSUE THREAD

**Issue by franklili3** [ConsenSys-archive/ganache-cli-archive#193]
I want to open HTTP server on Mac. I have copied javascript code on the testrpc page into a httpserver.js file under testrpc folder. On the bash, I move to testrpc folder, and run "node httpserver.js". The error appears as "/Users/linda/testrpc/httpserver.js:1
(function (exports, require, module, __filename, __dirname) { {\rtf1\ansi\ansicpg936\cocoartf1404\cocoasubrtf470
                                                               ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
"  . How can I do?

 
## Expected Behavior

I want to access testrpc through HTTP protocol.

## Current Behavior

On the localhost:8545, there appears,"400 bad request "

## Steps to Reproduce (for bugs)

1.On the bash, run "testrpc"
2.copy "var TestRPC = require(“ethereumjs-testrpc”);
var server = TestRPC.server();
server.listen(port, function(err, blockchain) {...});" into a httpserver.js under testrpc folder.
3.On the bash, move to testrpc folder, run"node httpserver.js"
4.
## Your Environment

- Version used:testrpc
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):node 5.0
- Server type and version:
- Operating System and version:Mac OS X
- Link to your project:

**Comment by jmdfm** [comment]
I honestly don't understand what you're trying to do here. The `testrpc` already is available over HTTP as it sets up its own server. Why are you copying files into the testrpc folder?
