### ISSUE TITLE
there lost the installing instruction of windows SDK 8.1 on the the installing instruction for windows. 

### ISSUE THREAD

**Issue by franklili3** [ConsenSys-archive/ganache-cli-archive#194]
## Expected Behavior
I can install testrpc successfully by installing instruction.

## Current Behavior
When I install testrpc by installing instruction for windows, the error appears " The Windows SDK version 8.1 was not found." I think the most person will not install this for windows PC.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by jmdfm** [comment]
Updated the Wiki with the additional step https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows
