### ISSUE TITLE
Calling estimateGas before sendTransaction causes nonce to not increment correctly

### ISSUE THREAD

**Issue by gaiazov** [ConsenSys-archive/ganache-cli-archive#199]
Running `eth_estimateGas` right before `eth_sendTransaction` causes nonce to not increment correctly

## Expected Behavior
The bug is rather strange as it only seem to happen in a specific scenario
 1. call `eth_estimateGas`
 2. call `eth_sendTransaction` to create a contract
 3. call `eth_estimateGas` again (could be different data, does not matter)
 4. call `eth_sendTransaction` to create another contract

The expected behavior is that two transactions have different `nonce` and hence contracts get created with different `contractAddress`. 

## Current Behavior
The actual behavior is that the `nonce` gets recycled and both contracts get created at the same `contractAddress`.

## Possible Solution
I'm honestly stumped. Adding a `eth_getTransaction` right after `eth_sendTransaction` seems to fix it. I don't know why it fixes it.

## Steps to Reproduce (for bugs)
I forked the repo and created a unit test that illustrates the behavior
https://github.com/gaiazov/testrpc/blob/master/test/nonce-estimate-gas.js

## Context
I have a deployment script that deploys several contracts. I want to deploy the contracts in sequence and then wait for all the contracts to be mined. I also don't want to hardcode a deployment gas since some contracts are small in size and due to the recent DoS attacks, small contracts get mined faster. 

This deployment script is used in our project's unit contract unit tests because the deployment process is complicated.

The script works when running against geth or parity but not when running in testrpc.

## Your Environment
* Version used: 3.0.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Node v4.4.4
* Server type and version: 
* Operating System and version: Windows 10
* Link to your project: https://github.com/gaiazov/testrpc/blob/master/test/nonce-estimate-gas.js

**Comment by gaiazov** [comment]
Tested with `ethereumjs-vm@2.0.1` and still doesn't work

**Comment by tcoulter** [comment]
Sounds like a good bug. Thanks for reporting!

**Comment by benjamincburns** [comment]
Added "needs validation" ticket because I need to update the test to run in the latest version. This is a great bug submission, thanks @gaiazov.

**Comment by benjamincburns** [comment]
Closing this one as it's quite old and we now have tests which show the behavior described is no longer problematic
