### ISSUE TITLE
TypeError: Class constructors cannot be invoked without 'new'

### ISSUE THREAD

**Issue by itech4ever** [ConsenSys-archive/ganache-cli-archive#202]
Hi guys, I am trying to set up examples from both Embark (embark demo) and Truffle (truffle conference). 

I installed testrpc using npm command (version 3.0.0). However, I cannot deploy contracts at both platforms, that is, I cannot run embark run or truffle migrate. The error message from testrpc was always:

TypeError: Class constructors cannot be invoked without 'new' at at FakeTransaction.Transaction (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-tx/index.js:37:15).....

My working environment is:

OS: OS X 10.11.5 El Captain
Node: 5.7.0
Truffle: 2.1.1
Embark: 2.1.4
testrpc: 3.0.0 (listening on localhost:8545)
Truffle conference example: https://github.com/eshon/conference

Thanks a lot!

**Comment by tcoulter** [comment]
We just released v3.0.1 to resolve a dependency issue. Please update your
installation of the TestRPC.

**Comment by itech4ever** [comment]
Thank you tcoulter, yes, it was fixed, all good now. Cheers!
