### ISSUE TITLE
getting account keys

### ISSUE THREAD

**Issue by omryr** [ConsenSys-archive/ganache-cli-archive#203]
I am looking for a way to add dynamically and get accounts ( key and address), i want to create a fully functioning test enviorment which can initiate account creation and i want to be able to pass the key and address from outside, is it possible?

**Comment by benjamincburns** [comment]
@omryr Sorry this went unanswered for so long! Chances are you want the `--account` option, or alternatively you can set the mnemonic using the `--mnemonic` flag. These details are in the README.md file on the main page of the repo, but please post back here if you need any further clarification.
