### ISSUE TITLE
testRPC should handle estimateGas calls if gas limit is over block limit.

### ISSUE THREAD

**Issue by simondlr** [ConsenSys-archive/ganache-cli-archive#207]
## Expected Behavior

In Geth & Parity, when doing estimateGas, one can choose the gas limit in such a way that it is over the block limit. It still returns the estimated amount. It is expected that testRPC would do the same. Say, passing through 1 billion gas, regardless of block limit, it should return the amount of gas used.

## Current Behavior
Currently, testRPC throws an error saying that gas limit is over the block limit when doing an estimateGas where the gas limit is over the block limit.

## Possible Solution
Change that estimateGas does not take into block limit when estimating gas.

## Steps to Reproduce (for bugs)
1. Set gas to 1 billion for an estimateGas
2. Call estimateGas

## Context
Metamask recently updated to have 1 billion gas for its gas estimation calls. This meant that any interaction with Metamask and testRPC is now broken, since Metamask calls estimateGas before every transaction.

**Comment by kumavis** [comment]
fix published moments ago as 2.13.10 , plugin will auto update within the hour

**Comment by tcoulter** [comment]
@kumavis is this a provider engine issue?

**Comment by kumavis** [comment]
no, metamask

**Comment by kumavis** [comment]
its resolved now
