### ISSUE TITLE
RPC method personal_newAccount not supported.

### ISSUE THREAD

**Issue by VictorAlbertos** [ConsenSys-archive/ganache-cli-archive#215]
If I set `testrpc` as the provider for `web3` 

```javascript
const TestRPC = require("ethereumjs-testrpc");
const web3 = new Web3(TestRPC.provider());
```

and I try to create a new account:

```javascript
web3.personal.newAccount(password, (error, address) => {
        
});
```

I get the next error:

> RPC method personal_newAccount not supported.

If this a current limitation of `testrpc`? If that so, are you planning to give support to expose this API thought `testrpc`?

Thanks.

**Comment by benjamincburns** [comment]
Thanks for the bug report @VictorAlbertos  - thanks to @axic's hard work in #262, this is now fixed/implemented.
