### ISSUE TITLE
update ethereumjs-util to solve bug concatenating signature 

### ISSUE THREAD

**Issue by denisgranha** [ConsenSys-archive/ganache-cli-archive#219]
testrpc is using ethereumjs-util version 4.5.1

in order to solve this bug https://github.com/ethereumjs/ethereumjs-util/issues/57

it needs to be updated to version 5.0.1

**Comment by benjamincburns** [comment]
Apologies we didn't get to this one sooner. `ganache-core` has been updated to use `ethereumjs-util` v5.0.1 for some time now.

Thanks for letting us know!
