### ISSUE TITLE
Quantities such as from eth_getTransactionCount have leading zeroes

### ISSUE THREAD

**Issue by vethan** [ConsenSys-archive/ganache-cli-archive#220]
## Expected Behavior

The [JSON RPC specification](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) specifies that hex values or quantities should be encoded in the most compact representation, i.e. 0x1.

## Current Behavior

Currently the result from testrpc's eth_getTransactionCount, and other quantity calls is padded to an even number of digits, i.e. 0x01.  

## Context

When using testrpc with web3j, calling eth_getTransactionCount causes an exception within web3j, due to its strict adherence to the specification.

## My Investigation so far
1. Changes made in PR ethereumjs/ethereumjs-util#62 don't fully solve the problem
2.  Changing the hex function in [/lib/utils/to.js](https://github.com/ethereumjs/testrpc/blob/master/lib/utils/to.js) to remove leading zeroes in the "object" case fixes the issue, but breaks some addresses.

**Comment by fabioberger** [comment]
Encountered this issue as well when using geth libraries together with testrpc.

**Comment by natanrolnik** [comment]
@fabioberger how did you solve this?

**Comment by natanrolnik** [comment]
@fabioberger @vethan I've opened the PR below to fix it!
