### ISSUE TITLE
Test runtimeBytecode after getCode

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#221]
https://github.com/ethereumjs/testrpc/blob/master/test/requests.js#L332-L334

Solc should return the runtimeBytecode, which is what is to be expected

**Comment by aakilfernandes** [comment]
Fixed here https://github.com/ethereumjs/testrpc/pull/224

**Comment by tcoulter** [comment]
Good fix. `runtimeBytecode` didn't exist when these tests were first written (didn't exist or I didn't know about it). Thanks.
