### ISSUE TITLE
Remove state tree manipulations that cause race condition

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#234]
https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L405-L409
https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L448-L452
https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L486-L490

By temporarily mapulating the stateTrie root, the blockchain will return false values until it is reverted (when the callback excutes)

I'm working on a fix to the Trie class to allow passing in a custom root, which should solve this

**Comment by benjamincburns** [comment]
Bear in mind that it's my first day on the job, but I think we could sidestep this by making processing of simultaneous requests share fewer resources, including especially the VM, provided this doesn't require significant memory/CPU overhead.

**Comment by mikeseese** [comment]
We're now tracking this in #453
