### ISSUE TITLE
Rename ethreumjs-testrpc into testrpc

### ISSUE THREAD

**Issue by chevdor** [ConsenSys-archive/ganache-cli-archive#245]
Why is testrpc published in npm as "ethreumjs-testrpc" and not simply "testrpc" ?

**Comment by Moejoe90** [comment]
I assume that the team has a future plan of adding different frameworks i'm not sure but already there is truffle-testrpc for example

**Comment by benjamincburns** [comment]
Thanks for the issue, @chevdor -- the prefix bugs me as well. The good news is, as of tomorrow, we'll actually be renaming testrpc to ganache-cli.

http://truffleframework.com/ganache/
