### ISSUE TITLE
eth_call commands are executed with block.number="latest", even if set to "pending"

### ISSUE THREAD

**Issue by drcode** [ConsenSys-archive/ganache-cli-archive#249]
In a full ethereum node such as geth, an eth_call with the block number param set to "pending" is executed in the "pending" block environment, with respect to the value of block.number. However, testrpc acts differently by setting the block number equal to the current block. This is problematic when working with apps that disallow multiple transactions of a certain type in the same block (since this causes testrpc to trigger many false negatives) 

## Expected Behavior
If the latest block has a block number= 20026:

- An eth_call with block="latest" should set block.number=20026
- An eth_call with block="pending" should set block.number=20027

## Current Behavior
If the latest block has a block number= 20026:

- An eth_call with block="latest" is set to block.number=20026
- An eth_call with block="pending" is also set to block.number=20026

## Steps to Reproduce (for bugs)

1. Create the following contract:

```
contract Preflight {
    uint public n;
    function foo() returns (uint) {
        n=block.number;
        return block.number;
    }
}
```

2. call the `foo` function with eth_call and set block number = "latest"
3. call the `foo` function with eth_call and set block number = "pending"
4. call the `foo` function via eth_sendTransaction and check the value set for state variable `n`

In testrpc, the value from 2 and 3 will be the same and the value from 4 will be different
In geth, the value from 2 and 3 will be different, and the values from 3 and 4 may be the same (though they are usually different as well, due to delays in mining caused by the default mining behavior in ethereum)

## Context
We're writing a (still privately developed) ethereum app that disallows certain transactions to share the same block. This issue is not a major blocker for us or anything (we can work around it) but thought it was worth mentioning to help testrpc reach parity with the full ethereum clients. 

## Your Environment
Using EthereumJS TestRPC v3.0.0 on MacOS

**Comment by 13rac1** [comment]
This code has moved to `trufflesuite/ganache-core`. The problem is:
https://github.com/trufflesuite/ganache-core/blob/4d2a063b475f362eaa08d5d681e95653177e46d8/lib/blockchain_double.js#L179-L180
```
    if (number == "latest" || number == "pending") {
      return this.latestBlock(callback);
```

**Comment by Eenae** [comment]
\+ even if set to specific block

Here we could see that the block_number parameter is ignored: https://github.com/trufflesuite/ganache-core/blob/4d2a063b475f362eaa08d5d681e95653177e46d8/lib/subproviders/geth_api_double.js#L286

And later, in implementation of eth_call we are heading straight to the latest block: https://github.com/trufflesuite/ganache-core/blob/4d2a063b475f362eaa08d5d681e95653177e46d8/lib/blockchain_double.js#L408

**Comment by mikeseese** [comment]
A test exists for this, so closing this as it got fixed somewhere else.
