### ISSUE TITLE
transactionIndex is always 0

### ISSUE THREAD

**Issue by mpolci** [ConsenSys-archive/ganache-cli-archive#252]
I started testrpc with the option -b 10 to mine a block every 10 senconds.
If I have many transactions in the same block, all transactions have the transactionIndex field equal to 0.

**Comment by mpolci** [comment]
see PR https://github.com/ethereumjs/testrpc/pull/253

**Comment by benjamincburns** [comment]
This should have been closed when Tim merged the PR. Thanks again for your contribution, @mpolci!
