### ISSUE TITLE
eth_sign fails on adresses prefixed with 0

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys-archive/ganache-cli-archive#26]
<img width="1431" alt="screen shot 2016-03-09 at 8 12 39 am" src="https://cloud.githubusercontent.com/assets/92629/13641824/d8b745f2-e5ce-11e5-977e-66f0c7fece90.png">

CC @MrChico

**Comment by MrChico** [comment]
Will take a look

**Comment by tcoulter** [comment]
Just fixed the test!
