### ISSUE TITLE
Installing testrpc in Ubuntu cannot be used

### ISSUE THREAD

**Issue by BobLiuzhongkui** [ConsenSys-archive/ganache-cli-archive#260]
ubuntu 16.04 LTS
Istall:npm install -g ethereumjs-testrpc
command:testrpc
exception:/usr/local/.../node_modules/web3-provider-engine/node_modules/ethereumjs-util/index.js
                 exports.SHA3_NULL=Buffer.from(exports.SHA3_NULL_S,'hex')
TypeError:hex is not a fuction
...

**Comment by fanatid** [comment]
Probably it's because node 4.5 minimum is required :(

**Comment by tinder-dyakobian** [comment]
should probably be surrounded with a try catch and then print that environment should be upgraded

**Comment by fanatid** [comment]
@tinder-dyakobian then `engines` filed should be added https://docs.npmjs.com/files/package.json#engines
do you want make a PR? I think testrpc team will be happy accept such changes

**Comment by tinder-dyakobian** [comment]
Ya thats a good idea, I will do once I switch to my personal account after work

**Comment by Moejoe90** [comment]
What version is your node?

**Comment by tcoulter** [comment]
Can all of you give the TestRPC `beta` a try? First uninstall the normal one, if installed (or partially installed):

```
$ npm uninstall -g ethereumjs-testrpc
```

And then install the beta version: 

```
$ npm install -g ethereumjs-testrpc
```

The beta version significantly improves installation and should bypass your installation issues. 

Since this is a beta version, I'd very much appreciate feedback on how it works for you and if you run into any errors during use.

**Comment by ghost** [comment]
I'm still not able to install testrpc.  The beta for truffle worked fine, but for testrpc:

npm ERR! code 1
npm ERR! Command failed: /usr/bit/git clone --depth=1 -q -b master https://github.com/debris/bignumber.js.git /home/<myusername>/.npm/_cacahe/tmp/git-clone-10a327a5/.git: Permission Denied
npm ERR!

npm ERR! A complete log of this can be found in:
........

Using Ubuntu 16.04

Using: sudo npm uninstall -g ethereumjs-testrpc, then the install still give this error set

**Comment by mikeseese** [comment]
Closing due to age.
