### ISSUE TITLE
Configurable Default Balance

### ISSUE THREAD

**Issue by IstoraMandiri** [ConsenSys-archive/ganache-cli-archive#265]
In https://github.com/ethereumjs/testrpc/pull/109, the default balance was reduced. Whilst it makes sense to do this by default, there are situations where you want to test with larger amounts of ETH.

The only way to do this currently, as far as I can tell, is to pass in a bunch of private keys along with a specific balance.

It would be more convenient to have something like a `--balances` option, which would set the default balance of all the accounts, without requiring private keys (or having a string of `--account`s) to be passed.

* Version used: `3.0.3`

**Comment by TwilightDuck** [comment]
Agreed.

**Comment by trivikramak** [comment]
Any updates on this ? It would be a really handy feature.

**Comment by Stickerpants** [comment]
+1 to this feature, doing testing that involves a large amount of addresses makes explicitly setting each balance an infeasible task.

**Comment by soulmachine** [comment]
+1

**Comment by benjamincburns** [comment]
@hitchcott, @NickJorens, @trivikrama619, @Stickerpants, & @soulmachine - I'm new (just starting today) but will be managing TestRPC development from the Truffle team from here on.

I'll take a look at @hitchcott's PR, but in the mean time, I'm wondering if you all have seen issue #23? What are your thoughts on that feature vs this one?

**Comment by jwasinger** [comment]
@benjamincburns Exciting news!  I'm a developer working on EthereumJS VM among other things.  I have an existing PR that updates ganache-core to be compatible with Byzantium.  Could you take a look when you get a chance? https://github.com/trufflesuite/ganache-core/pull/19

Feel free to reach out in the public ethereumjs gitter channel if you need to get in contact with me.

**Comment by benjamincburns** [comment]
@jwasinger will definitely be looking into that shortly, and thanks in advance for the change! 

Small nitpick, however: please keep issues on topic... Feel free to ping me from the PR itself next time, rather than posting in an unrelated comment. :-)

**Comment by Stickerpants** [comment]
@benjamincburns The `genesis.json` proposal #23 would be a fantastic way to resolve this issue. Thank you for the checking in!

**Comment by bwheeler96** [comment]
Why is the default balance `100` ETH anyways? Seems silly to limit the amount of fake money like that. Base 10 numbers are great for writing tests with from a mental math perspective

**Comment by benjamincburns** [comment]
I've accepted trufflesuite/ganache-core#18 with some light modifications - just wiring it up to `ganache-cli` now.

**Comment by benjamincburns** [comment]
Done. Note that the changes to `ganache-cli` will have no effect until a release of `ganache-core` which contains trufflesuite/ganache-core#18 is made, and this project is updated to make use of that release.
