### ISSUE TITLE
**Command failed: git -c core.longpaths=true config --get remote.origin.url**

### ISSUE THREAD

**Issue by thatslibran** [ConsenSys-archive/ganache-cli-archive#266]
--- Having issue while installed ethereumjs-testrpc - desperately looking for a solution
--- I've configured HTTP.proxy setting/cred, as I'm working behind corporate proxy
--- Set-ExecutionPolicy configured to 'Unrestricted'
--- Windows 7 - 32Bit OS

PS C:\Windows\system32> **npm install -g ethereumjs-testrpc**
npm WARN addRemoteGit Error: **Command failed: git -c core.longpaths=true config --get remote.origin.url**
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:192:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:890:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:189:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
npm WARN addRemoteGit  git+https://github.com/debris/bignumber.js.git#master resetting remote C:\Users\*****\AppData\
ming\npm-cache\_git-remotes\git-https-github-com-debris-bignumber-js-git-master-df3f1ce1 because of error: { **Error: C
and **failed: git -c core.longpaths=true config --get remote.origin.url****
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:192:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:890:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:189:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\*****\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://githu
om/debris/bignumber.js.git C:\Users\*****\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-debris-bignumbe
s-git-master-df3f1ce1: Cloning into bare repository 'C:\Users\*****\AppData\Roaming\npm-cache\_git-remotes\git-https-
hub-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! git clone --template=C:\Users\*****\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://githu
om/debris/bignumber.js.git C:\Users\*****\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-debris-bignumbe
s-git-master-df3f1ce1: fatal: unable to access 'https://github.com/debris/bignumber.js.git/': Failed to connect to gi
b.com port 443: Timed out
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\*****\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\
m-cli.js" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\*****\AppData\Roaming\npm-cache\_git-re
es\_templates --mirror https://github.com/debris/bignumber.js.git C:\Users\*****\AppData\Roaming\npm-cache\_git-remot
git-https-github-com-debris-bignumber-js-git-master-df3f1ce1
npm ERR! Cloning into bare repository 'C:\Users\*****\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-deb
-bignumber-js-git-master-df3f1ce1'...
npm ERR! fatal: unable to access 'https://github.com/debris/bignumber.js.git/': Failed to connect to github.com port
: Timed out
npm ERR!

**Comment by thatslibran** [comment]
Issue persist even on installing downloaded source code

**Comment by thatslibran** [comment]
My bad! Turned out to be an issue with proxy settings :( It seems we need to set proxy settings in both  PowerShell as well as git config.

**Comment by bertyhell** [comment]
If anyone else runs into this, make sure you don't have any custom dns settings on your network adapter configuration:
https://developers.google.com/speed/public-dns/docs/using#windows

**Comment by koertvankleef** [comment]
Can also be caused by an outdated npm version. In my case updating npm v 3.1.0 to 5.6.0 fixed this problem.
