### ISSUE TITLE
AssertionError: The field value must not have more 32 bytes

### ISSUE THREAD

**Issue by illuzen** [ConsenSys-archive/ganache-cli-archive#268]
I found a bug. It is caused by a Truffle test I'm running in which I send 1e24 + 1 wei to a function. It's a big number added to an int. 

> /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
> (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS
> AssertionError: The field value must not have more 32 bytes
>     at FakeTransaction.setter [as value] (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-util/index.js:642:9)
>     at Object.exports.defineProperties (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-util/index.js:694:22)
>     at FakeTransaction.module.exports (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-tx/index.js:92:11)
>     at new FakeTransaction (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-tx/fake.js:40:26)
>     at /usr/local/lib/node_modules/ethereumjs-testrpc/lib/statemanager.js:308:14
>     at /usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain_double.js:228:5
>     at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:76:5
>     at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:442:14
>     at Object.return (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:461:9)
>     at processNode (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:284:30)

I'm running a bunch of tests for a crowdsale. 
OSX 10.11.6 
Truffle v3.1.2
TestRPC v3.0.3

Running testrpc with

> testrpc --debug --account="0x1024102410241024102410241024102410241024102410241024102410241024,100000000000000000000000000" --account="0x1024102410241024102410241024102410241024102410241024102410241023,100000000000000000000000000" --account="0x1024102410241024102410241024102410241024102410241024102410241022,100000000000000000000000000" --account="0x1024102410241024102410241024102410241024102410241024102410241021,100000000000000000000000000" --account="0x1024102410241024102410241024102410241024102410241024102410241020,100000000000000000000000000"

Fix: I changed it to use the BigNumber api .add(1) instead of +1 and it no longer crashes. 

I will check soon whether this breaks testnet nodes. Probably not, but just to be safe.

**Comment by benjamincburns** [comment]
I've just published `ganache-cli@7.0.0-beta.0` which I believe fixes this bug, as well as adds support for websockets, and contains numerous other fixes. You can get it by doing `npm install -g ganache-cli@beta`.

Closing this case for now, but please reopen if I've got it wrong and this problem shows its ugly face again.

**Comment by chatch** [comment]
I got the exact same error when setting a transaction value of 1/3 of a finney:
    web3.toWei(web3.toBigNumber(1), 'finney').dividedBy(3)

Can confirm for this value that 7.0.0-beta.0 fixed this issue.

Any chance of porting it back to ganache v6 and also the next version of truffle? My test breaks inside the "truffle develop" environment ..

**Comment by benjamincburns** [comment]
Hi Chris. Check the releases page :-)
