### ISSUE TITLE
Improve log performance when forking

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys-archive/ganache-cli-archive#276]
See the way logs are done here: https://github.com/ethereumjs/testrpc/pull/179

i.e., instead of making n requests to the forked chain, make 1.

**Comment by benjamincburns** [comment]
Issue moved to [trufflesuite/ganache-core #145](https://github.com/trufflesuite/ganache-core/issues/145) via [**ZenHub**](https://www.zenhub.com/)
