### ISSUE TITLE
Return value for net_listening is wrong.

### ISSUE THREAD

**Issue by digitaldonkey** [ConsenSys-archive/ganache-cli-archive#279]
net_listening returns true instead of the hexadecimal representation of the value. 

The expected return value according to [Ethereum Wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_listening) would be: 

```
curl -X POST --data '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":67}' localhost:8545
{"id":67,"jsonrpc":"2.0","result":true}
```

## Expected Behavior
`0x0000000000000000000000000000000000000000000000000000000000000001`
## Current Behavior
`true`

## Context
Can't implement consistent return value across clients in my PHP implementation.

**Comment by mikeseese** [comment]
The expected behavior is now `true` from the JSON RPC. Closing due to now being compliant!
