### ISSUE TITLE
Returns internal transaction instead of returned value on new contract.

### ISSUE THREAD

**Issue by xavierlepretre** [ConsenSys-archive/ganache-cli-archive#280]
My contract function:

* creates a new instance of another contract
* immediately calls this other contract and returns the result of the call

If I call this function with a `.call`, what I do get, is not the returned value but the internal transaction.

My contracts are:
```
pragma solidity ^0.4.4;

contract Store {
    uint public num;
}

contract Caller {
    function callNum() returns (uint) {
        Store c = new Store();
        return c.num();
    }
}
```

## Expected Behavior

With Geth:

* I deploy `Caller` to `callerAddress`
* In Javascript, I do `Caller.at(callerAddress).callNum.call()`

This returns me `0`, as I expect.

## Current Behavior

With TestRPC:

* I deploy `Caller` to `callerAddress`
* In Javascript, I do `Caller.at(callerAddress).callNum.call()`

This returns me `0x4e70b1dc00000000000000000000000000000000000000000000000000000000`.
Notice how `4e70b1dc` is the function signature of `num()`.

## Steps to Reproduce (for bugs)
As above

## Your Environment

* Version used: 3.0.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): NodeJs v6.10.0
* Server type and version: 
* Operating System and version: vagrant-ubuntu-trusty-64
* Link to your project:

**Comment by mikeseese** [comment]
Closing due to age/inactivity. @benjamincburns is fairly confident this is now working due to `call` reworking since this issue.

Please open a new issue if you're still having problems. Thanks!
