### ISSUE TITLE
Transaction is not begin to mine

### ISSUE THREAD

**Issue by iFA88** [ConsenSys-archive/ganache-cli-archive#281]
Transaction is not begin to mine after mining several transactions.
My script sends transactions after another and wait until they mining out.

```
  Transaction: 0x4d18676cbc820e220f9c737caa545c24344e4ae2c2d14992f3dc7bbc94cba813
  Gas usage: 0x01cf96
  Block Number: 0x0d
  Block Time: Thu Mar 23 2017 08:18:07 GMT+0100 (CET)

eth_getTransactionReceipt
eth_call
eth_estimateGas
eth_sendTransaction
eth_getTransactionReceipt
eth_getTransactionReceipt...forever
```

This issue is really frequently. After this issue I need to restart the whole TestRPC server, because If I send another transactions it would not be mined.
Normally my script runs without any problem.

* Version used: EthereumJS TestRPC v3.0.3
* Operating System and version: Raspbian Jessie
* I use `--debug` too.

**Comment by piyush-ramavat** [comment]
I'm facing the same issue.
My contracts gets deployed and some time one transaction goes through.
But after that no transactions are mined.

console keeps showing:
eth_getTransactionReceipt 

I was facing same issue in Geth as well, but I realised that I wasn't running any Miner.
Once I started Miner in Geth, everything started working.

But Geth is actual private network and Contracts are eternal. So I can't use it while development.

Can anyone help? I'm sure that if testrpc starts one miner, it would resolve the issue.
Is there a way we can start miner explicitly?

Thanks.

**Comment by 7flash** [comment]
Maybe you need to unlock your account

**Comment by bijeebuss** [comment]
I was having this problem and for some reason specifying gas in the transaction options object fixed it for me.

**Comment by iFA88** [comment]
Account is unlocked, gasprice and gaslimit are specified :)

**Comment by bijeebuss** [comment]
Are you using https://www.npmjs.com/package/web3-provider-engine? this also happened to me when I configured it incorrectly

**Comment by iFA88** [comment]
I will close this issue, because it was long time ago, since I have reinstalled (maybe better version with fixes) and works fine. Thank you!
