### ISSUE TITLE
Race condition error, provider accepts calls before first block has been added

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#287]
Looks like provider accepts calls (and passes them to web3-provider-engine) before the first block has been added. This causes a race condition.

https://gist.github.com/aakilfernandes/e63a6354c82983f0db663d77539b7cb7

https://github.com/MetaMask/provider-engine/blob/master/subproviders/vm.js#L163

**Comment by benjamincburns** [comment]
@aakilfernandes this should be fixed in the latest release. If you still have troubles, please let me know.
