### ISSUE TITLE
Docker instructions in README.md no longer valid

### ISSUE THREAD

**Issue by pszabop** [ConsenSys-archive/ganache-cli-archive#288]
Docker instructions in README assume testrpc is still being published to Dockerhub as `ethereumjs/testrpc:latest`,  There is no ethereumjs on docker hub anymore.

## Expected Behavior
`docker run -d -p 8545:8545 ethereumjs/testrpc:latest` per the README should work.

## Current Behavior
`docker run -d -p 8545:8545 ethereumjs/testrpc:latest` fails to find the image.

## Possible Solution
Remove this instruction from the README.md, tell users they must build their own docker image.

## Context
New users will be confused or think the project is defunct.

## Your Environment
OSX Docker community version (latest as of April 2, 2017)

**Comment by EternalDeiwos** [comment]
would also be really great if the maintainers published the docker image to docker hub.

**Comment by Zolmeister** [comment]
workaround (if you trust me) - v4.1.1
[zolmeister/testrpc](https://hub.docker.com/r/zolmeister/testrpc/)

**Comment by benjamincburns** [comment]
There are some changes coming to TestRPC soon. We'll definitely be tightening up the docs and releasing an official docker image on docker hub as part of that. Watch this space!

**Comment by benjamincburns** [comment]
This is closed as of the changeover to ganache-cli.
