### ISSUE TITLE
Throws error on getBlockByNumber with blockNumber > blockchain head

### ISSUE THREAD

**Issue by kumavis** [ConsenSys-archive/ganache-cli-archive#290]
Testrpc throws error on `eth_getBlockByNumber` when requesting a block with `blockNumber` greater than the current block. Other clients simply return `null`. This breaks `provider-engine@12.x.x`.

parity
```
$ curl -H "Content-Type: application/json" -X POST --data '{"id":120,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x457f7c", false]}' https://pmainnet.infura.io | jq
{
  "jsonrpc": "2.0",
  "result": null,
  "id": 120
}
```

geth
```
$ curl -H "Content-Type: application/json" -X POST --data '{"id":120,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x457f7c", false]}' https://gmainnet.infura.io | jq
{
  "jsonrpc": "2.0",
  "id": 120,
  "result": null
}
```

testrpc
```
$ curl -H "Content-Type: application/json" -X POST --data '{"id":120,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x457f7c", false]}' http://localhost:8545 | jq   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1744    0  1657  100    87  54605   2867 --:--:-- --:--:-- --:--:-- 55233
{
  "id": 120,
  "jsonrpc": "2.0",
  "error": {
    "message": "Error: Couldn't find block by reference: 0x457f7c\n    at BlockchainDouble.getBlock (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/lib/blockchain_double.js:130:21)\n    at GethApiDouble.eth_getBlockByNumber (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:119:25)\n    at GethApiDouble.handleRequest (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:61:10)\n    at next (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at SolcSubprovider.handleRequest (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/solc.js:28:7)\n    at next (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at VmSubprovider.handleRequest (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:40:12)\n    at next (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at GethDefaults.handleRequest (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:17:12)\n    at next (/Users/kumavis/.nvm/versions/node/v6.10.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)",
    "code": -32000
  }
}
```

**Comment by danfinlay** [comment]
This is a seriously important issue to address. Provider-Engine has updated its block polling logic in the latest version, and is no longer compatible with `testrpc` until this is fixed, and it should be fairly simple to fix.

The next version of MetaMask really needs to include the provider-engine update, so we're in danger of having a release that breaks compatibility with `testrpc` unless this is addressed.

Sorry for the urgent issue, I'll poke in the codebase to see if it would be easy for me to fix myself.

**Comment by tcoulter** [comment]
This should be an easy fix, and you should do it in geth_api_double.js by
catching the error. Even if this is fixed now you're going to have people
on different versions of the testrpc based on when they installed it, so
you should insulate yourself from that regardless, perhaps by catching the
error on your end.

**Comment by alex-miller-0** [comment]
I have somehow run into this state by running truffle tests. Now this error persists every time I run a truffle test even when I:

- Reboot testrpc

- Clear out my testrpc/build

- Reboot my OS

Is there a way to manually clear out this state? Does this have to do with the new persist features of testrpc?

**Comment by kumavis** [comment]
@alex-miller-0 are you using persistent testrpc by chance?

**Comment by alex-miller-0** [comment]
@kumavis Not unless it's on by default. 

I have been able to circumvent this by manually running `truffle compile && truffle migrate` followed by running `truffle test test/foo.js` for *individual* tests. However, if I run `truffle compile && truffle migrate && truffle test`, I consistently get this error.

Sorry this report is light on the details. I'm honestly not sure what changed to present the error in the first place - I was just writing contracts and adding tests and all of a sudden this seems to happen consistently.

**Comment by nicholasjpaterno** [comment]
After review and discussion with @seesemichaelj, we're going to close this issue unless further details can be provided.

It seems, https://github.com/MetaMask/eth-block-tracker/pull/3 prevents the error on metamasks side, while https://github.com/trufflesuite/ganache-cli/pull/295 fix's the issue on ganache's side.

Hope this helps!
