### ISSUE TITLE
testrpc fails to clear mapping storage slots

### ISSUE THREAD

**Issue by o0ragman0o** [ConsenSys-archive/ganache-cli-archive#294]
**testrpc** fails to delete a non empty mapping store instead presenting the error:
`callback contain no result Error: Error: base fee exceeds gas limit`
If the mapping value has not been previously set, the transaction is processed normally

```
contract TestRPCtest {
    mapping (uint => uint) public uints;
    
    // Sets the uints[1] slot to a value;
    function store(uint _uint) { uints[1] = _uint;}
    
    // Fails under testRPC provider on non empty store
    // "callback contain no result Error: Error: base fee exceeds gas limit"
    function clear() { delete uints[1];}
}
```

## Expected Behavior

A  call containing `delete <mappingVariable>[<key>]` should delete data stored at that key.

## Current Behavior

A call containing `delete <mappingVariable>[<key>]` appears to fail to lodge a transaction.

## Steps to Reproduce (for bugs)

1. Paste `TestRPCtest` from above into BrowserSolidity or Remix
2. Run testRPC and select it as provider
3. Compile and create
4. Check getter `uints()` returns `0`
5. Check `clear()` creates a returned transaction
6. Call and check `store(1)` creates a returned transaction
7. Check getter `uints()` returns `1`
8. Calling `clear()` fails to create and return a transaction 
9. Getter `uints()` still returns `1`.  Storage is not deleted

## Context

Annoyance meaning that private test chain must be used for development

## Your Environment

* Version used: EthereumJS TestRPC v3.0.3
* Operating System and version: Linux Mint 17

**Comment by benjamincburns** [comment]
@o0ragman0o thanks for reporting this -- I can't believe none of us got back to you until now!

Is this still a problem for you? If so, I think it'd be an EVM bug, but I'm happy to dive in and help diagnose to make sure. That said, we're now beta testing ganache-cli v7.0.0... I think we've had many improvements to the EVM since testrpc 3.0.3!
