### ISSUE TITLE
ethereumjs-testrpc depends on deprecated version of ethereumjs-utils

### ISSUE THREAD

**Issue by Tectract** [ConsenSys-archive/ganache-cli-archive#299]
ethereumjs-testrpc depends on deprecated version of ethereumjs-utils, causing signing issues.

## Expected Behavior
myContract.new({from:web3.eth.accounts[0],data:code,gas:gasEstimate}.... SHOULD SUCCEED
see issue: http://stackoverflow.com/questions/41595996/pubtoaddress-method-from-ethereumjs-util-throws-assertionerror-false-true

## Current Behavior
myContract.new({from:web3.eth.accounts[0],data:code,gas:gasEstimate}.... FAILS ON ASSERTION

## Proposed Solution
update package.json to reflect new version of ethereumjs-utils, 5.1.1 is the latest right now, and it fixes this issue.

**Comment by Moejoe90** [comment]
Why not do a PR for this?

**Comment by Tectract** [comment]
Why should I have to make a whole PR for the project devs to update a single outdated dependency? Do it yourself! Be good project maintainers!

**Comment by benjamincburns** [comment]
This has long since been updated. As such I'm closing this case, like a good project maintainer...
