### ISSUE TITLE
Accesing testRPC from a server

### ISSUE THREAD

**Issue by R1j1t** [ConsenSys-archive/ganache-cli-archive#306]
I created a dAPP for a competition and only used to test it on testRPC. When deploying it on a server, we tried to implement the contracts on a server (which had testRPC running in the background) and then making transactions via UI, the problem is we are not able to make access testRPC from the hosted app via public IP

## Expected Behaviour
I think I should be able to access testRPC from a server. If not then what is the right way to do so?

## Current Behavior
I tried deploying it on a server which had testrpc running, but when I did a transaction, it didn't work. 

## Steps to Reproduce (for bugs)
1. Deploy the contracts on testrpc
2. Using the UI to create transaction
3. No transaction happened

## Context
I thought I could access test RPC on a remote machine. If not then can you suggest a better way access the blockchain without actually using Ethereum Global Network 

## Your Environment
* Version used: 3.1.2
* Operating System and version: Ubuntu 16.04.2 LTS 64-bit

**Comment by mikeseese** [comment]
You can change which network interface/IP you listen on to open your RPC to the public world (i.e. instead of `-h 127.0.0.1`, you can do `-h your-public-ip`). I don't recommend this as opening your RPC endpoint to the public is **dangerous**
