### ISSUE TITLE
How --db option is working ? 

### ISSUE THREAD

**Issue by cooorentin** [ConsenSys-archive/ganache-cli-archive#307]
I wanted to know if there is a database (or a file) where I can have all the informations, transaction etc. that happen on my testrpc. I thought using the option --db but it didn't work in my case. I tried with different formating like **testrpc --db="path/to/the/directory"**, without the "", without the equal sign... 
How does it works ? Is there another solution ? I didn't find anything about where testrpc is storing the ledger/datas. 
Thanks in advance for the help!

**Comment by popra** [comment]
bump

**Comment by kokipsiho** [comment]
I have same issue. Can anybody help?

**Comment by PavloPoliakov** [comment]
in my case it doesn't work as well

@tcoulter @iurimatias

**Comment by domalaq** [comment]
Me too. Had to go hard way working with geth to do what I wanted :)

**Comment by PavloPoliakov** [comment]
actually, in the version which is being installed right now the `--db` is not mentioned in the readme.
https://github.com/ethereumjs/testrpc/tree/2ea36d21057a971c3c362898286d3afa62a4667d

**Comment by domalaq** [comment]
I think it's just quietly ​being taken off

**Comment by PavloPoliakov** [comment]
@domalak 
no, it just was not released yet, actually. And current `master` README.md is ahead of the one we download.

Problem solved, but not in the best possible way :)

In order to use `--db` we need to do the next:
```
npm i ethereumjs-testrpc@beta
testrpc --db=$(pwd)/data/testrpc --account="0xa0d6eabe72fd11a3c7e8bbba48899ab4864c2ca275b12fa917bb13e9386d34de, 1000000000000000000000" \
--account="0x3cf44c4d4252d9d9277f5503dac4e365f56c69cff5d1396da4f156dc115ddcac, 1000000000000000000000" \
--account="0x74bdd757948e186d1bc4461c0781dd9d6706d97d92ecb9f788f0793983a733aa, 1000000000000000000000" \
--account="0xdacb9f4a3dd45dce1a4ba8a1077b8631babf0eecf25c147a54f776418210ce7c, 1000000000000000000000" \
--account="0x327bca8f573280e431323dbbaca36b0431089f8702100c91d836b2eadf30c67d, 1000000000000000000000"
```

the directory should be created before launching the command

@tcoulter @iurimatias, do we expect the new release happening anytime soon?

**Comment by veqtor** [comment]
Would be nice with a relative path... how would I do this?

**Comment by pooleja** [comment]
Is the --db feature working with 4.0.0?  I am deploying contracts and then restarting and it doesn't seem like they are still deployed.  Just wanted to confirm since this issue is still open.

**Comment by aleebek** [comment]
has anyone used that feature ever?

**Comment by dkent600** [comment]
I am seeing stuff appear in the database folder upon contract migration.

But nothing appears to be reloaded on restart.

I use Ctrl-C to stop testrpc, then restart it using the -m option to result in the same accounts and keys.  However, I find that the database does not appear to be reloaded.

I'm using v4.0.0

**Comment by benjamincburns** [comment]
All,

To use the `--db` option, you must also specify the mnemonic and network ID.

I'll be making ganache remember these details in the database in a future release.  I'll track that under case #407. As such, please comment there if the workaround of specifying the mnemonic & network id isn't working for you.

**Comment by dkent600** [comment]
Providing the mnemonic and networkId as suggested is working for me!

**Comment by xdsarkar** [comment]
Without mnemonic, it works for me.

ganache-cli -d --db ganache_db -i 123456
