### ISSUE TITLE
Fail to install due to missing ?

### ISSUE THREAD

**Issue by otembajelle** [ConsenSys-archive/ganache-cli-archive#315]
I followed the detail instructions on https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows

yes I am a windows user, no I couln'd pin it down to windows

## Expected Behavior
testrpc is runnable

## Current Behavior
npm install -g ethereumjs-testrpc exits with an Error

## Possible Solution
I haven't the faintest

## Steps to Reproduce (for bugs)
1. do as suggested 
2. run npm install -g ethereumjs-testrpc
3. the error shows in the screen log ...

C:\Users\Jelle\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\Jelle\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\..\scrypt\win\include\config.h
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm▒glichen, m▒ssen Sie den Schalter "/m" hinzuf▒gen.
VCBUILD : error : project file 'C:\Users\Jelle\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\copied_files.vcproj' was not found or not a valid project file. [C:\Users\Jelle\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\binding.sln]

## Your Environment
Windows 10 German Version, Visual Studio 8 Express, etc a shown in the installation instructions

**Comment by 0xtuytuy** [comment]
I have the same problem... really frustrating.

**Comment by fanatid** [comment]
Install https://github.com/felixrieseberg/windows-build-tools and then testrpc

**Comment by 0xtuytuy** [comment]
@fanatid I have just tried, nothing changes, it still does not work

**Comment by otembajelle** [comment]
@fanatid Thank you for sharing your valuable expertise. Felix Riesebergs script, that you recommend, was smart to discover that I lack administrator access rights when running my GitBash. When I start GitBash as an admin then testrpc installs OK. Problem solved! (for me)

To the good people of testrpc. To keep an idiot like me at bay, you may want to consider a similar hint as Felix's?

**Comment by tcoulter** [comment]
Can all of you give the TestRPC `beta` a try? First uninstall the normal one, if installed (or partially installed):

```
$ npm uninstall -g ethereumjs-testrpc
```

And then install the beta version: 

```
$ npm install -g ethereumjs-testrpc
```

The beta version significantly improves installation and should bypass your installation issues. 

Since this is a beta version, I'd very much appreciate feedback on how it works for you and if you run into any errors during use.

**Comment by otembajelle** [comment]
Sorry for keeping you waiting. I was on a trip. Will do soon.
@tuytuy how did the beta version work for you?

**Comment by otembajelle** [comment]
@tcoulter I reinstalled and experienced no problems. All worked fine when I used the beta installer.
