### ISSUE TITLE
npm install failed on Windows & Ubuntu

### ISSUE THREAD

**Issue by 0xtuytuy** [ConsenSys-archive/ganache-cli-archive#316]
I have tried to install using the simple npm install command on both windows & ubuntu. Neither work.
I'll focus on Ubuntu for this issue

## Expected Behavior
npm install should install testrpc with no errors

## Current Behavior
I get this error:
![image](https://cloud.githubusercontent.com/assets/6547517/26765504/185f4500-4975-11e7-9d33-7cfc730e712c.png)

## Steps to Reproduce (for bugs)
1. fresh installation of ubuntu on VirtualBox
2. sudo apt-get install npm
3. npm install -g ethereumjs-testrpc

## Your Environment
Ubuntu (latest) on VirtualBox

**Comment by rpinolf** [comment]
Getting the same exact issue on WSL (as expected). Tried with different node 8 releases but not with node 7 or the LTS yet. Which node/npm releases are you using?

**Comment by tcoulter** [comment]
Can all of you give the TestRPC `beta` a try? First uninstall the normal one, if installed (or partially installed):

```
$ npm uninstall -g ethereumjs-testrpc
```

And then install the beta version: 

```
$ npm install -g ethereumjs-testrpc
```

The beta version significantly improves installation and should bypass your installation issues. 

Since this is a beta version, I'd very much appreciate feedback on how it works for you and if you run into any errors during use.

**Comment by rpinolf** [comment]
Yep. Big thanks, installing the @beta tagged build did the trick. But now similar issue with truffle...same permissions denied on .git but on a different package.

**Comment by rpinolf** [comment]
Ok. Too fast...installing Truffle with tag 3.2.93 that seems to be the mist recent build worked.

**Comment by ghost** [comment]
Should mention the @beta tag in the explanation above.  I've been trying to uninstall and reinstall without @beta, and been getting same errors until now.  

Installed now, but when I run "testrpc" I'm not getting the version and list of accounts, but:

/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:35271
function VM (opts = {}) {

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    ...
    (other areas as well)

**Comment by andreyFreeman** [comment]
@entelechii same here. Did you figure this out?

**Comment by benjamincburns** [comment]
@andreyFreeman chances are if you're still experiencing issues with `npm install -g ethereumjs-testrpc` (or `npm install -g ganache-cli` as it's now called), you're on a version of node older than 6.11.5. I suggest checking out NVM, or our shiny new [docker images](https://hub.docker.com/r/trufflesuite/ganache-cli).
