### ISSUE TITLE
No errors, module not found

### ISSUE THREAD

**Issue by jneljneljnel** [ConsenSys-archive/ganache-cli-archive#317]
[testrpc.txt](https://github.com/ethereumjs/testrpc/files/1066852/testrpc.txt)

## Expected Behavior
npm install -g ethereum-testrpc should work

## Current Behavior
npm install -g ethereum-testrpc does not work

**Comment by nickemmons** [comment]
Ran into this same problem.  Fixed it by running this command instead: `npm install -g ethereumjs-testrpc`

**Comment by benjamincburns** [comment]
@jneljneljnel and/or @nickemmons - was there some documentation you were following which instructed you to install `ethereum-testrpc`? If so can you please link to it here so that I can catch up with whomever maintains it and let them know to correct it?

**Comment by nickemmons** [comment]
@benjamincburns I was following [this guide](https://blockgeeks.com/guides/how-to-learn-solidity/) on Blockgeeks that told me to install `ethereum-testrpc`

**Comment by benjamincburns** [comment]
Great, thanks for the quick response!

It looks like someone already commented this correction a while ago. I'll ping some more well-connected folks at ConsenSys tomorrow to see if I can't reach out to someone there more directly. In the mean time, perhaps they'll notice a tweet: https://twitter.com/benjamincburns/status/923024465751101440

**Comment by benjamincburns** [comment]
I've reached out to the folks at Blockgeeks, but haven't heard back. Closing this, as there's not much else I can do. Sorry, guys.
