### ISSUE TITLE
Error with the mississippi module during `npm install -g ethereumjs-testrpc`

### ISSUE THREAD

**Issue by pyskell** [ConsenSys-archive/ganache-cli-archive#318]
## Expected Behavior

ethereumjs-testrpc installs correctly

## Current Behavior

Fails to install. I get the following output. Error is the same in both `Node.JS 6` and `Node.JS 8`:

```
root@me-VirtualBox:~# npm install -g ethereumjs-testrpc
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-12T16_23_20_447Z-debug.log
root@me-VirtualBox:~# tail -n 30 /root/.npm/_logs/2017-06-12T16_23_20_447Z-debug.log
827 http fetch GET 200 https://registry.npmjs.org/spdx-correct 2ms (from cache)
828 silly pacote range manifest for spdx-expression-parse@~1.0.0 fetched in 8ms
829 silly resolveWithNewModule spdx-expression-parse@1.0.4 checking installable status
830 silly pacote range manifest for spdx-correct@~1.0.0 fetched in 8ms
831 silly resolveWithNewModule spdx-correct@1.0.2 checking installable status
832 http fetch GET 200 https://registry.npmjs.org/spdx-license-ids 1ms (from cache)
833 silly pacote range manifest for spdx-license-ids@^1.0.2 fetched in 2ms
834 silly resolveWithNewModule spdx-license-ids@1.2.2 checking installable status
835 http fetch GET 200 https://registry.npmjs.org/camelcase 2ms (from cache)
836 silly pacote range manifest for camelcase@^3.0.0 fetched in 3ms
837 silly resolveWithNewModule camelcase@3.0.0 checking installable status
838 silly fetchPackageMetaData error for bignumber.js@git+https://github.com/debris/bignumber.js.git#master exited with error code: 128
839 http fetch GET 200 https://registry.npmjs.org/crypto-js 11ms (from cache)
840 http fetch GET 200 https://registry.npmjs.org/xmlhttprequest 12ms (from cache)
841 silly pacote range manifest for crypto-js@^3.1.4 fetched in 12ms
842 silly resolveWithNewModule crypto-js@3.1.8 checking installable status
843 silly pacote range manifest for xmlhttprequest@* fetched in 14ms
844 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
845 verbose stack Error: exited with error code: 128
845 verbose stack     at ChildProcess.onexit (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
845 verbose stack     at emitTwo (events.js:125:13)
845 verbose stack     at ChildProcess.emit (events.js:213:7)
845 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
846 verbose cwd /root
847 verbose Linux 4.4.0-79-generic
848 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "-g" "ethereumjs-testrpc"
849 verbose node v8.1.0
850 verbose npm  v5.0.3
851 error exited with error code: 128
852 verbose exit [ 1, true ]
```

## Steps to Reproduce (for bugs)

0. `apt-get remove npm` to get rid of the Ubuntu package
1. Install `nodejs` on Ubuntu 16.04 using the official nodejs install instructions from your README (ie. not using the Ubuntu-provided package).
2. Run `npm install -g ethereumjs-testrpc`

## Your Environment

* Version used: Tried both the beta (with -g flag to npm) and `npm install ethereumjs-testrpc`
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Attempted the install with both `Node.JS 6` and `Node.JS 8`.
* Server type and version: A Virtual Machine
* Operating System and version: `Ubuntu 16.04 LTS`

**Comment by fanatid** [comment]
is git installed on virtual machine?

**Comment by pyskell** [comment]
Yes, also just found this. Likely related. Going to attempt with the latest npm release and will let you know.

https://github.com/npm/npm/issues/16726

For reference I was on `npm 5.0.3` when the error happened.

**Comment by pyskell** [comment]
Latest version of npm also didn't resolve it. If you know of a particular version you'd like me test I'm more than happy to. I've tried everything from `5.0.0` to the latest `canary` version.

**Comment by pyskell** [comment]
Someone on the npm issue reported success with `npm 4.x` and I'm confirming that it installs correctly using `npm 4.6.1` (the latest of the 4.x releases).

Steps to fix (as root):
`npm install -g npm@4.6.1`
`npm install -g ethereumjs-testrpc`

Also works with `npm install -g ethereumjs-testrpc@latest`

**Comment by ghost** [comment]
This issue is resolved after deleting the node_module and re-install the npm "sudo npm install"

**Comment by mikeseese** [comment]
Closing due to age/inactivity. Also looks like it's no longer an issue per the prior comments
