### ISSUE TITLE
Feature request: Add easier way to make node mine N blocks or advance to block height X

### ISSUE THREAD

**Issue by maraoz** [ConsenSys-archive/ganache-cli-archive#320]
It'd be awesome for `evm_mine` to accept an extra parameter specifying how many blocks we want the node to advance, or alternatively, the target block height we want to reach.
Thanks!

**Comment by federicobond** [comment]
@maraoz IIRC you can do that with https://github.com/DigixGlobal/tempo

**Comment by mikeseese** [comment]
We talked about this on some other issue/PR, and decided that we won't fix this as you can call `evm_mine` in a loop.
