### ISSUE TITLE
testrpc@beta simple transaction doesn't work

### ISSUE THREAD

**Issue by PavloPoliakov** [ConsenSys-archive/ganache-cli-archive#327]
Hello,

I'm experimenting with `testrpc@beta` as it allows to have a persistence blockchain storage.
However, I found that the code which works for the current release version of the `testrpc` doesn't work for the `@beta` one.

Here is the gist:
https://gist.github.com/PavelPolyakov/32b11ff29f650a19de51d3e67352eeef

In order to test it we need to do next:
```
npm init -y
npm i web3 eth-lightwallet bluebird
npm install -g ethereumjs-testrpc
./testrpc.sh # run testrpc
./test-transaction.sh # try to: 1. create account, 2. top up, 3. do the transaction
```
After you'll see the error:
```
Unhandled rejection Error: Error: base fee exceeds gas limit
    at runCall (/Users/PavelPolyakov/.nvm/versions/node/v6.11.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82214:17)
    at /Users/PavelPolyakov/.nvm/versions/node/v6.11.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:12868:26
    at replenish (/Users/PavelPolyakov/.nvm/versions/node/v6.11.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:10034:17)
```
I've tried to provide the `gas` parameter to the object, but it didn't help.
While the same `gist` would successfully work with `EthereumJS TestRPC v3.0.5`.

Though I'm looking forward for the `beta` version as it supports `--db`.

Please, let me know if I can help.

@tcoulter, could you, please, share a light if we are going to have a new version anytime soon?

Regards,

**Comment by benjamincburns** [comment]
@PavelPolyakov is this still an issue for you with latest TestRPC?

**Comment by benjamincburns** [comment]
Also sorry it took us so long to respond!

**Comment by PavloPoliakov** [comment]
@benjamincburns 
I think that was error in my contract, not `testrpc`.

Thanks for reminding me to close the issue.
