### ISSUE TITLE
Aside: This was old instructions. Can someone verify if this is needed?

### ISSUE THREAD

**Issue by otembajelle** [ConsenSys-archive/ganache-cli-archive#329]
The instruction 5 of https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows is questioned by the author.

## Expected Behavior
Temp isn't needed.

## Current Behavior
Temp isn't needed.

## Possible Solution
I tried it out. The assumption turned out correct. Step 5 is unnecessary.

## Context
Windows 10

## Your Environment
Windows 10

**Comment by mikeseese** [comment]
Closing due to age; the instructions referenced no longer exist
