### ISSUE TITLE
getBlock should support returning transactions in that block.

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#330]
I'm testing a module with testrpc, that relies on getting an array of `transactions` when the `getBlock` second parameter is `true`.

You can try the failing test suite here:

https://github.com/MetaMask/eth-gas-price-suggestor

**Comment by tcoulter** [comment]
This appears to be supported, as shown by this code here: 

https://github.com/trufflesuite/ganache-core/blob/master/lib/subproviders/geth_api_double.js#L159

I'll leave this issue open as there still might be an issue. Will review when I can look into it in more detail.

**Comment by nicholasjpaterno** [comment]
This appears to be fully supported.

https://github.com/trufflesuite/ganache-core/blob/develop/lib/utils/block_helper.js#L27

and tested

https://github.com/trufflesuite/ganache-core/blob/develop/test/requests.js#L226

This should be safe to close.
