### ISSUE TITLE
Watching a filter doesn't not catch all events when automine rate is < 3 seconds

### ISSUE THREAD

**Issue by fullykubed** [ConsenSys-archive/ganache-cli-archive#338]
## Expected Behavior
All events on the blockchain should be caught by Web3.js library when it watches a filter applied to the blockchain.

## Current Behavior
If the automine functionality mines too fast, Web3.js does not pick up the events. Also, if instamine is enabled, the filter watchers will also miss events or fire the same event twice.

## Possible Solution
Wish I could be more help here. I can say that it seems to have to do with the speed of the mining. Web3.js event filters simply don't work consistently with fast automining or instamining. I don't think it has to do with the filters watchers because I believe they poll every 500 ms.

## Steps to Reproduce (for bugs)

1. Create a Solidity contract with an event
2. Initiate testrpc with the automine option set to 3 or less seconds
3. Load and deploy the contract with Web3.js
4. Create an filter and watch it with Web3.js
5. Initiate a series of transactions that fires the event
6. Realize that the filter misses events

## Context

The easy solution is to just put automine on 5 seconds; however, this is kindof annoying if I have a bucket of transactions with events i'd like to test.

Not a game changer, but would be nice to either have this quirk fixed or documented, so in the future developers can respond accordingly.

## Your Environment

*Testrpc 4.0.1
*Web3.js 0.0.19

**Comment by keepchen** [comment]
@jclangst 
Hello,could you give me a demo code about how to catch event with web3.js on testrpc.
Thanks a lot.

**Comment by abendigo** [comment]
I ran into the same issue (events firing twice) using Truffle.
here is my contract:

    pragma solidity ^0.4.15;

    contract Oracle {
        event GetDailyCandle(string instrument, uint64 timestamp);

        function getDailyCandle(string instrument, uint64 timestamp) {
            GetDailyCandle(instrument, timestamp);
        }
    }


and here is my unit test:

    let Oracle = artifacts.require("./Oracle.sol");

    contract('Oracle', function(accounts) {
      it("logs when message request events are recieved", function(done) {
        Oracle.deployed().then(function(instance) {
          let events = instance.GetDailyCandle();

          events.watch(function(error, result) {
            console.log('result', result.args)
          });

          instance.getDailyCandle("USD/CAD", 6);
          setTimeout(_ => {
            events.stopWatching();
            done();
          }, 2000);
        });
      });
    });

when this is run, you will see the result output twice.

**Comment by ylosbar** [comment]
same issue here with a very simple and basic contract. @jclangst  Did you find a workaround ?

**Comment by eshaben** [comment]
Thank you @jclangst for submitting this. I was unable to reproduce this bug with the latest version of Web3 and Ganache, therefore I am going to go ahead and close this issue.
