### ISSUE TITLE
testrpc --account="0xpk,1000000000000000000" creates balance of 0

### ISSUE THREAD

**Issue by mdance** [ConsenSys-archive/ganache-cli-archive#339]
## Expected Behavior

Running testrpc --account="0xpk,bal" creates an initial account with the correct balance specified by bal

## Current Behavior

Running testrpc --account="0xpk,bal" creates an initial account with a balance of 0, I have tried specifiying bal as 1 (ether), 1000000000000000000 (wei), hex, etc. and it doesn't seem to be working

## Possible Solution

Unknown

## Steps to Reproduce (for bugs)

1. Run the following:
testrpc \
--db data \
--blocktime 0 \
--port 10545 \
--gasPrice 20000000000 \
--gasLimit 0x47E7C4 \
--network-id 188 \
--account="0xpkexportedfrommetamask,1000000000000000000" \
--unlock 0 \
--account="0xpkexportedfrommetamask,1000000000000000000" \
--unlock 1 \
--debug

2 a. Using a Custom RPC server through metamask, check the balances, for me its 0

2 b. Check the balances in mist through the following command:

/Applications/Ethereum\ Wallet.app/Contents/MacOS/Ethereum\ Wallet \
--node "geth" \
--network "test" \
--rpc 'http://127.0.0.1:10545' \ 

## Your Environment

* Version used:
EthereumJS TestRPC v4.0.0 (ganache-core: 1.0.1)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
n/a
* Operating System and version:
OSX El Capitan 10.11.6
* Link to your project:

**Comment by atomical** [comment]
Any movement on this?

**Comment by benjamincburns** [comment]
@mdance is this one still giving you trouble? I've used the `--account` option numerous times lately with success, but I confess I haven't tested the balance portion of it rigorously.

**Comment by gixita** [comment]
Did you try to change of network, because it didn't update the amount automatically (go to main network and then on localhost). For me it works

**Comment by Cript** [comment]
Also have this problem with balance. The temporary solution is to start testrpc without **--account** option but with **--db**. Save private keys from output and then start testrpc with **--account** options with saved keys.

**Comment by freethejazz** [comment]
Looks like this is a bug. See: https://github.com/trufflesuite/ganache-cli/issues/475

**Comment by mikeseese** [comment]
I'm having issues reproducing this with Ganache CLI v6.1.4. I'm guessing this has been fixed since then.

Please update to the latest version of ganache-cli, and if the issue is still happening, open up a new issue.

Thanks everyone!
