### ISSUE TITLE
Testrpc gives "Error: VM Exception while processing transaction: invalid opcode" while test case with geth runs fine

### ISSUE THREAD

**Issue by inovizz** [ConsenSys-archive/ganache-cli-archive#345]
Error screenshot URL -  http://i.imgur.com/XqIE9x1.png

## Expected Behaviour
I'm expecting my test case to throw and consume all cumulative gas, even with that transaction should not fail and I should get a transaction receipt.

## Current Behaviour
I assume transaction is getting failed and that's why I'm getting "invalid opcode error".

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Clone this repo https://github.com/inovizz/lms.git
2. Go to branch: testrpc-issue
3. go to project directory "lms" and run "npm install"
4. run "testrpc" in another tab and then do "truffle migrate --reset" from project directory
5. run "truffle test test/testParent.js" to see errors

## Context
I'm trying to run some test case and test cases are getting passed easily when I run them using geth however with testrpc I get this error. Ideally, testrpc should behave same as geth. So it would be great if someone can look into this and fix it.

## Your Environment
* Version used: EthereumJS TestRPC v4.0.1 (ganache-core: 1.0.1)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Truffle(v3.2.5) and webpack
* Server type and version: Testing it locally yet
* Operating System and version: Ubuntu 16.04
* Link to your project: https://github.com/inovizz/lms/tree/testrpc-issue

**Comment by zman0225** [comment]
this stalled me a few days as well. For me, migrations have been incredibly flakey as well; `"invalid opcode error"`. However, (correct me if I'm wrong), I don't think it's essential for testing, right? I just created another network field in `truffle.js` and denied the deployment scripts from running the migrations with a `network !== "test"` if check.

**Comment by jaddison** [comment]
I get this intermittently but frequently with testrpc. If I restart testrpc, it works well for a test run, but I need to restart it a lot.

**Comment by jaddison** [comment]
I'm not positive, but I think the frequency increased once I started calling `eth_increasetime` and `eth_mine`, although it did happen infrequently before I added those calls to my JS tests.

**Comment by dwalintukan** [comment]
I'm receiving invalid opcode constantly on my local machine. On the Travis-CI machine, tests pass fine. I have deployed to the testnet with no issue either.

**Comment by jaddison** [comment]
I'm macos 10.12, if that helps.

**Comment by benjamincburns** [comment]
All - this issue should be fixed in the latest version of TestRPC. TestRPC v4.x didn't yet support the new opcodes introduced by the Byzantium update, so this was expected behaviour at that time. Please reopen if you are still receiving this error.

**Comment by ArjunMenon-96** [comment]
> I get this intermittently but frequently with testrpc. If I restart testrpc, it works well for a test run, but I need to restart it a lot.

pwoli saaanam work aayi
