### ISSUE TITLE
Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.

### ISSUE THREAD

**Issue by smtalimett** [ConsenSys-archive/ganache-cli-archive#347]
Windows 7 Professional Service Pack 1
4GB RAM and 64 bit O/S
Node.js version 6.11.1
I have Python 2.7+ and the latest version of OpenSSL and Node.js installed. When I run:
$ npm install -g ethereumjs-testrpc
 I get an error: Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.

**Comment by robertjchristian** [comment]
This happens to me when deploying to Windows on Azure.  Works fine on Mac.  Something to do with Webpack I believe.

**Comment by muysewinkel** [comment]
I have the same error when installing angularcli on Mac.

**Comment by max-bulygin** [comment]
I have th same error as muysewinkel has with angular cli on Mac. Any ideas how to fix it? Thanks

**Comment by mikeseese** [comment]
Closed due to age/inactivity
