### ISSUE TITLE
Does Testrpc use ethereumjs-vm ? - Update Readme

### ISSUE THREAD

**Issue by Janaka-Steph** [ConsenSys-archive/ganache-cli-archive#356]
I don't see ethereumjs-vm in the package.json and nowhere in the repo, but the readme says "NOTE: As of version 3.0.2, testrpc requires at least Node 6.9.1 to run - this is because the ethereumjs-vm@2.0.1 dependency is now shipping using ES2015 language features."

**Comment by cdetrio** [comment]
ethereumjs-vm is in the yarn.lock file.
