### ISSUE TITLE
Testrpc won't work if ran in background mode

### ISSUE THREAD

**Issue by rstormsf** [ConsenSys-archive/ganache-cli-archive#357]
If I run a testrpc with `&` in bash script and then I try to `truffle migrate`, it won't wait until the contract is deployed to save the address in contract's JSON

Example: 
```

if testrpc_running; then
  echo "Using existing testrpc instance"
else
  echo "Starting our own testrpc instance"
  # We define 10 accounts with balance 1M ether, needed for high-value tests.
  testrpc > /dev/null &
  testrpc_pid=$!
fi

cd contracts_src && ../node_modules/.bin/truffle compile && ../node_modules/.bin/truffle migrate && echo "done"
```

## Expected Behavior
I should be able to deploy contract even it commanded from bash script.
## Current Behavior
I get TxId as an output, but all transactions are not mined in testrpc

## Steps to Reproduce (for bugs)
Run the script above with some contracts from truffle located at `contracts_src`

## Your Environment

* Version used: EthereumJS TestRPC v4.0.1 (ganache-core: 1.0.1)
* Server type and version:
* Operating System and version: Mac Os Sierra

**Comment by rstormsf** [comment]
I figured out, I have to have at least some period of mining blocks: `testrpc -b 0.1` in order to guarantee that addresses will be available in json files

**Comment by benjamincburns** [comment]
@rstormsf You shouldn't need to set a block time. The behavior you're describing sounds like you're using async migrations in truffle.

In order to make this work correctly, you'll need to follow the following pattern in your migration file:

```javascript
module.exports = async function(deployer) {
  return deployer.then(async function() {
    // async deploy logic goes here
  }
}
```
