### ISSUE TITLE
Mining doesn't work after TestRPC was run on Mac

### ISSUE THREAD

**Issue by yuyaogawa** [ConsenSys-archive/ganache-cli-archive#358]
After deployed a simple contract, I called the balance on truffle console, it is always pending.
I am new but I think the block that I deployed a contract doesn't mine?
I can get an address when I call like below
HelloWorld.deployed().then(a => console.log(a.address))

## Your Environment

* Version used:EthereumJS TestRPC v4.0.1, Truffle v3.4.6 ( Solidity v0.4.13)
* Operating System and version:OSX 10.10.5
* Link to your project:

**Comment by yuyaogawa** [comment]
(a) did work! but (b) doesnt work... I should read reference carefully, but does anyone explain about this?

(a) HelloWorld.deployed().then(function(instance) {return instance.getBalance.call(account1)})
    >{ [String: '0'] s: 1, e: 0, c: [ 1000 ] }
(b) HelloWorld.deployed().then(a => console.log(a.getBalance.call(account1)))
    >Promise { pending }

**Comment by benjamincburns** [comment]
@yuyaogawa it sounds like you've resolved your issue now, and either way this question is quite old.

In the future if you're not sure how things are supposed to work please check our [docs](http://truffleframework.com/docs/) and [tutorials](http://truffleframework.com/tutorials/) pages, and ask questions in our [gitter channel](https://gitter.im/ConsenSys/truffle).
