### ISSUE TITLE
estimateGas bug - differences between Mainnet, Ropsten, and TestRPC

### ISSUE THREAD

**Issue by XertroV** [ConsenSys-archive/ganache-cli-archive#360]
A particular transaction for [ann.sol](https://github.com/exo-one/ann.sol) is failing under TestRPC when it does not fail on Mainnet and Ropsten. I suspect this is due to the fact I clear some data in this particular method (and only this method).

## Expected Behavior
Behaviour should match that of Mainnet and Ropsten

## Current Behavior

When the gas provided lower than 1.4x of the gasEstimate the transaction fails. On Mainnet and Ropsten the method succeeds with just 1.1x the gasEstimate. Using TestRPC, when the gas provided is at least 1.475x the gasEstimate the method succeeds.

All successful transactions gas usage exactly matches the gasEstimate.

## Possible Solution

I suspect this is to do with how TestRPC handles gas refunds for zeroing entries.

[This is the line](https://github.com/exo-one/ann.sol/blob/7e33a0224fb0aeb3d7b29f4c004aa53a4a822669/contracts/Announcement.sol#L113) where the delete is performed.

Perhaps this is the best place to start.

## Steps to Reproduce (for bugs)
1. Clone exo-one/ann.sol
2. Clone exo-one/ann-sol.com
2. check out commit `f0792e7772441f53410d3fcd8d6a4062e245448f` (a patch has since been applied)
3. Start TestRPC
4. Run `truffle deploy` in `ann.sol` directory
5. Copy the contract address
6. Load up `ann-sol.com/index.html` in a browser
7. Under 'config' section click 'use localhost' (to set it to use testrpc)
8. Under 'Announcement ens domain/address' section paste in the contract address and press 'go'
9. Under 'contract functions' select the owner address and type something into the announcement field and publish it
10. under 'contract functions' select an auditor (after the tx has confirmed within the UI), select the announcement you just made and then attempt to accept the announcement. Notice the out of gas error.
11. Bonus: try to reject the announcement, should work fine.

## Context
This is just important to make the testing environment as similar as possible to the real network.

## Your Environment
* Version used: 3.0.5 & 4.0.1
* Link to your project: https://github.com/exo-one/ann.sol https://github.com/exo-one/ann-sol.com

**Comment by fmrsabino** [comment]
Been testing a project and sometimes I need to switch to TestRPC and noticed that the transactions wouldn't get through (not enough gas). I guess for now I should use different multipliers depending on the network that I'm connected to. Thanks for describing the issue.

**Comment by mikeseese** [comment]
Closing in favor of https://github.com/trufflesuite/ganache-core/issues/26. There is going to be a new issue that will be linked in the linked issue that implements even more accurate estimation
