### ISSUE TITLE
Server won't close because of keep alive connections

### ISSUE THREAD

**Issue by krzkaczor** [ConsenSys-archive/ganache-cli-archive#365]
## Expected Behavior
Hitting ctrl+c (SIGINT) should always close the server. 

## Current Behavior
If there are connections kept alive (for example meta mask plugged into the local network) server will *never* stop. It's [expected behavior](https://github.com/nodejs/node-v0.x-archive/issues/9066) for` httpServer.close` but definitely not expected behavior for the user. 

## Possible Solution
Use `server-destroy` package which internally stores information about all connections and closes them before closing server. I will post a PR in a sec.

## Steps to Reproduce (for bugs)
1. Start RPC
2. Set up `metamask` to connect to local network.
3. Try closing the server.
4. NO PROFIT :(

## Your Environment
* Version used: 4.0.1
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): node v8.1.4
* Operating System and version: MacOS

**Comment by mattgstevens** [comment]
I also have this problem when using [concurrently](https://github.com/kimmobrunfeldt/concurrently) and the --kill-others flag.

Current behaviour of testrpc means it may not shutdown on SIGTERM which makes local development less nice, since you will need to use a command like `pkill -f testpc` to stop the testrpc

**Comment by step21** [comment]
Seconded. How to kill it?

**Comment by szerintedmi** [comment]
I've been struggling with this issue for a while and I found the following workaround which works with high enough nodejs versions:
Ctrl-Z 
then `kill %1`

the trick that it's only working with node > 8.3.0 , I've no clue why :)
I played a bit and 8.5.0 I've found the best version to use so far. 
With 8.4.0 it seemed to have worse performance and with new versions it regularly crashes.
