### ISSUE TITLE
ganache-cli does not deploy contract using web3 1.0 api

### ISSUE THREAD

**Issue by ShibaOnTheMoon** [ConsenSys-archive/ganache-cli-archive#369]
## Expected Behavior
I want to deploy a contract on the chain using the latest web3 library. It should deploy the contract when I use the following code :

```js
var contract = new web3.eth.Contract(contractInfo.abi);
contract.deploy({
  data: '0x' + contractInfo.bytecode
}).send({
  from: account.address,
  gas: 4500000
}).then(console.log);
```

## Current Behavior

The deployment fails with the following stacktrace :

```
Error: Synchronous requests are not supported.
 at Provider.send (node_modules/ethereumjs-testrpc/build/lib.node.js:27523:9)
 at RequestManager.send (node_modules/web3/packages/web3-core-requestmanager/src/index.js:129:19)
 at sendRequest (node_modules/web3/packages/web3-core-method/src/index.js:525:42)
 at Object.send (node_modules/web3/packages/web3-core-method/src/index.js:540:13)
 at Object._executeMethod (node_modules/web3/packages/web3-eth-contract/src/index.js:876:67)
 at Context.<anonymous> (test/myContract_test.js:19:8)
```

## Possible Solution

I have the feeling that it is due to the updates made in the web3 library and the API behind the two libraries are out-of-sync ?

## Steps to Reproduce (for bugs)
1. Install latest version of ethereumjs-testrpc and web3
2. Try to deploy a contract

## Context

It affected while I was working a on testing my contract behavior with the Mocha framework.

## Your Environment

* Version used :
```json
"dependencies": {
  "ethereumjs-testrpc": "^4.0.1",
  "mocha": "^3.5.0",
  "solc": "^0.4.15",
  "web3": "^1.0.0-beta.18"
}
```
* Environment name and version : node v8.1.2
* Operating System and version : ArchLinux (not sure really relevent for the issue)

**Comment by benjamincburns** [comment]
@MechanicalSloth I'm sorry it's been so long without a response from us! I think you're correct that this is a web3 issue. It should be calling the provider's `sendAsync` method rather than `send` in this case. I'd suggest raising the issue with them.

If you feel I'm wrong on this, please don't hesitate to reopen.

**Comment by benjamincburns** [comment]
This wasn't a web3 issue, but rather an issue with our provider. I'll have this fixed as part of the WebSockets work.

**Comment by ShibaOnTheMoon** [comment]
Thank you ! 👍

**Comment by benjamincburns** [comment]
@MechanicalSloth this is now fixed and available (along with websockets support) in our `7.0.0-beta.0` release. You can get this release by running `npm install -g ganache-cli@beta`

Thanks for reporting this issue!
