### ISSUE TITLE
how to use evm_snapshot

### ISSUE THREAD

**Issue by wighawag** [ConsenSys-archive/ganache-cli-archive#37]
Hi, I have tried to use evm_snapshot using

```
server.provider.manager.evm_snapshot(function(err,snapshotId){...});
```

but I get some error in web3 in the test using snapsho and revert.

I am not sure I am using it correctly 

I initialise testrpc this way (in mocha code):

```
var TestRPC = require("ethereumjs-testrpc");
var server = TestRPC.server();
before(function(done){
    server.listen(8545, function() {
        web3.setProvider(new web3.providers.HttpProvider("http://localhost:8545"));
        done();
    });
})
```

the only test that fail is the one using the snapshot feature. any help woudl be appreciated
Thanks

**Comment by tcoulter** [comment]
Hi @wighawag - quick question. Are you using this with Truffle? 

Either way, you'd want to do something like this after setting the provider:

```
web3.currentProvider.sendAsync({
  jsonrpc: "2.0",
  method: "evm_snapshot",
  id: 12345
}, function(err, result) {
  // this is your callback
});
```

The reason you have to do this is because `evm_snapshot` is a non-standard method and web3 does not provide an interface for it.

Aside: The `provider` interface exists on the TestRPC as well, which, depending on your context may simplify a few things for you:

```
var TestRPC = require("ethereumjs-testrpc");

before(function(done){
    web3.setProvider(new TestRPC.provider()));
    done();
})
```

Going to close this as unfortunately there's no way around this syntax given the relationship between providers and web3 proper.

**Comment by wighawag** [comment]
Thanks for the quick reply,  I am using it without anything except just node and mocha

using sendAsync I get the same error :

```
 Uncaught AssertionError: null == true
      at Object.callback (test/index.js:142:8)
      at node_modules/web3/lib/web3/method.js:142:25
      at node_modules/web3/lib/web3/requestmanager.js:89:9
      at Web3ProviderEngine._inspectResponseForNewBlock (node_modules/web3-provider-engine/index.js:217:12)
      at node_modules/web3-provider-engine/index.js:127:14
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:269:32
      at node_modules/async/lib/async.js:44:16
      at async.eachSeries.resultObj.id (node_modules/web3-provider-engine/index.js:108:9)
      at node_modules/async/lib/async.js:181:20
      at Immediate.iterate [as _onImmediate] (node_modules/async/lib/async.js:262:13)
```

but I can now see the log mentionning the snapshot saving and restore.

```
Saved snapshot #1
```

and

```
Reverting to snapshot #1
```

Not sure what is wrong here.

**Comment by wighawag** [comment]
no wait that's a different error, might be on my side. sorry
