### ISSUE TITLE
VM Out of gas exception happening only on non-constant type functions ?

### ISSUE THREAD

**Issue by sivachaitanya** [ConsenSys-archive/ganache-cli-archive#371]
Out of gas exception when sending Tx requests from web3

 

## Expected Behavior
I should be able to execute register_org function successfully as done in the truffle console environment
## Current Behavior
Sending Tx request raises out of gas exception even though I started test rpc with 450000000 gas limit, It When deployed in remix its working, when run in truffle console everything is working, Currently from web3 I am able to only call the constant function successfully but not State changing functions

Sample output logged in testrpc when making send Tx call 
```


  Transaction: 0xb929e535f7c35e15951021778ed1900c57b9fc6baa6f4fb1e6770e65870f0aa7
  Contract created: 0x0669ecf205508fc1a6dcb724573f3f97eeb736c9
  Gas usage: 1066838
  Block Number: 45
  Block Time: Sun Aug 20 2017 22:22:19 GMT+0530 (India Standard Time)

eth_newBlockFilter
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
eth_uninstallFilter
eth_accounts
eth_sign
eth_call
eth_sendTransaction

  Transaction: 0x10cd3d5fd3b59d2698f0928438eb51fce373cf76eb19ef4debe0b0c115d3e664
  Gas usage: 90000
  Block Number: 46
  Block Time: Sun Aug 20 2017 22:22:24 GMT+0530 (India Standard Time)
  Runtime Error: out of gas


```

## Possible Solution
No Idea,how to resolve this
## Steps to Reproduce (for bugs)

1.Execute Truffle compile in your power shell
2. Execute Truffle migrate in your power shell
3. Run test rpc
4. run npm run dev in your project directory
5. Go to localhost:8080 in your browser
6. Click on Register button which should execute, VerifyUser function from app.js
7. Notice contract gets created successfully, and able to call verify which is a constant function in EcrecTest.sol but deployedecrecTest.reg_org() will fail compalining out of gas exception

## Context
I am trying to call a register_org() functions which takes inputs and store them on the blockchain
## Your Environment

* Version used: 4.0.1
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Truffle+ Testrpc + Web3
[EcrecTest.zip](https://github.com/ethereumjs/testrpc/files/1237195/EcrecTest.zip)

* Server type and version:node 6.11.2 
[EcrecTest.zip](https://github.com/ethereumjs/testrpc/files/1237196/EcrecTest.zip)

* Operating System and version:windows 10
* Link to your project: Please find in the attachments, app.js (which has web3 code), index.html, EcrecTest.sol

**Comment by benjamincburns** [comment]
@sivachaitanya I believe this issue was likely due to truffle setting the gas limit for you. That problem is now fixed. Given the age of this case, I think it's best to close, but please do reopen if this is still a problem for you.

**Comment by benjamincburns** [comment]
And sorry for taking so long to get back to you!
