### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by leopoldjoy** [ConsenSys-archive/ganache-cli-archive#372]
When I run `npm install -g ethereumjs-testrpc` I get an installation error.

## Expected Behavior
I want to install the package on MacOS.

## Current Behavior
I get the following error during installation:

    /usr/local/lib
    └─┬ ethereumjs-testrpc@4.1.0 
      └─┬ webpack@3.5.5 
        ├─┬ node-libs-browser@2.0.0
        │ ├─┬ crypto-browserify@3.11.1
        │ │ └─┬ browserify-cipher@1.0.0
        │ │   └─┬ evp_bytestokey@1.0.2 
        │ │     └─┬ md5.js@1.3.4 
        │ │       └── hash-base@3.0.4 
        │ └── timers-browserify@2.0.4 
        ├── source-map@0.5.7 
        └─┬ watchpack@1.4.0
          └─┬ chokidar@1.7.0
            └─┬ anymatch@1.3.2
              └─┬ normalize-path@2.1.1
                └── remove-trailing-separator@1.1.0 

    npm ERR! Darwin 16.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ethereumjs-testrpc"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! path /usr/local/lib/node_modules/.staging/node-pre-gyp-74fa898f
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall rename

    npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/node-pre-gyp-74fa898f' -> '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/fsevents/node_modules/node-pre-gyp'
    npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/node-pre-gyp-74fa898f' -> '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/fsevents/node_modules/node-pre-gyp'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/username/path/to/app/npm-debug.log

## Steps to Reproduce (for bugs)
Simply run `npm install -g ethereumjs-testrpc` in the below environment.

## Your Environment
* Version used: 4.1.0
* Server type and version: node v6.2.1 and npm  v3.9.3
* Operating System and version: MacOS 10.12

**Comment by tcoulter** [comment]
Try adding `sudo` to your command. e.g., `sudo npm install -g ethereumjs-testrpc`.

If that doesn't fix your issue please reopen.

**Comment by leopoldjoy** [comment]
@tcoulter Adding `sudo` to the command didn't resolve the issue, I still get the same error. How can I reopen the issue?

**Comment by leopoldjoy** [comment]
@tcoulter I was able to resolve the issue by deleting the `/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/fsevents` directory and re-running `npm install -g ethereumjs-testrpc`. Thank you for your help!

**Comment by jbarros35** [comment]
NOENT: no such file or directory, access '/usr/local/lib/node_modules/ganache-cli'

**Comment by samanthawardhaugh** [comment]
@jbarros35 I had a similar issue so I thought I'd let you know how I solved it. When I cd'd to /usr/local/lib/node_modules and ran ls -la I found a symlink to another directory, ../../../../Users/sam/projects/node_modules/ganache-cli. The folder project existed, but nothing below it. I found a package-lock.json file in the project folder, deleted it, unlinked the symlink (unlink /usr/local/lib/node_modules/ganache-cli) and reran the install.

That worked for me, hope it helps!
