### ISSUE TITLE
Feature Request: Simulate block time

### ISSUE THREAD

**Issue by madvas** [ConsenSys-archive/ganache-cli-archive#374]
Hi,

It'd be very useful when creating UI to be able to fake block time for easier testing "pending" state in UI. Also, it'd be great if we could change this block time during run-time by calling RPC method, similarly to `evm_increaseTime `. 

Thank you

**Comment by tcoulter** [comment]
Hi there.

> It'd be very useful when creating UI to be able to fake block time for easier testing "pending" state in UI.

Please see the `-b` option.

As of now there's no way to increase the blocktime during runtime, but thanks for the request. Since you made two requests at once this ticket is harder to track and organize. Please create the following as a new ticket:

> Also, it'd be great if we could change this block time during run-time by calling RPC method, similarly to evm_increaseTime

Thanks!

**Comment by madvas** [comment]
Oops sorry, I missed that. Thanks I will
