### ISSUE TITLE
Can't exit (^C) when MetaMask keeps calling eth_getBlockByNumber

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache-cli-archive#379]
## Expected Behavior
testrpc exits when I press ^C.

## Current Behavior
MetaMask is calling eth_getBlockByNumber, and I want to exit testrpc. Here's the Terminal output:
```
eth_getBlockByNumber
^Ceth_getBlockByNumber
eth_getBlockByNumber
```
The ^C doesn't work like it normally does in testrpc.

## Steps to Reproduce (for bugs)

1. Connect MetaMask to testrpc.
2. Enter ^C to try to exit testrpc.

## Context
I often want to restart testrpc while MetaMask is running. In this case, it was to test something with MetaMask.

## Your Environment
* Version used: v4.0.1
* MetaMask version 3.9.11
* Environment name and version: Terminal
* Operating System and version: Mac OS X Yosemite 10.10.5

**Comment by Asone** [comment]
same here. 

# Environment 

- Version used : v4.0.1
- Metamask version : v3.10.9
- Environment name and version : Terminal
- Operating System and version : Debian 8.6
- nodeJS version : v0.10.29
- npm version : 5.3.0

**Comment by navp4l** [comment]
I'm seeing the same problem when using ganache-cli

# Environment

Version used : Ganache CLI v6.0.3 (ganache-core: 2.0.2)
Metamask version : v3.12.0
Environment name and version : iterm2
Operating System and version : Mac OS High Sierra 10.13.1
nodeJS version : v8.6.0
npm version : 5.5.1

**Comment by bwheeler96** [comment]
Me as well

**Comment by benjamincburns** [comment]
This is fixed in the current develop branch and will go out with the next beta.

**Comment by Asone** [comment]
Excellent news ! thanks for the info @benjamincburns :D 

with the race condition fix incoming too, stability of the tool is going to be greatly improved ! Nice work from the community ! ( to the mooooooon ? :p )

**Comment by benjamincburns** [comment]
This issue is fixed in the current beta release of `ganache-cli` (v6.1.0-beta.0)
Actually, I think it was fixed in the previous beta release as well. Sorry for the confusion.

**Comment by jordanglassman** [comment]
Fix verified in v6.1.0-beta.0. 

Are these infinite `eth_getBlockByNumber` calls a MetaMask bug?  I don't see a related issue on their tracker.

**Comment by benjamincburns** [comment]
Not a bug. They poll for the latest block number.

**Comment by 0xAnon101** [comment]
Btw @benjamincburns I am seeing this without metamask as well. I sent a transaction, it logs **eth_getTransactionReceipt**, then keeps on logging **eth_getBlockByNumber** continously, well until I hit cmd + S on my .sol file.
I have a Nodejs server running using nodemon, it sends a txn to smart contracts, after sending txn, I click save , it stops continuous logging and just output these logs at end - 
```
eth_accounts
net_version
eth_getBlockByNumber
```
