### ISSUE TITLE
Support for homestead/delegatecall

### ISSUE THREAD

**Issue by axic** [ConsenSys-archive/ganache-cli-archive#38]
See: https://github.com/ethereumjs/ethereumjs-vm/issues/52

Currently `ethereumjs-block` is used in `blockchain.js:createBlock()`, that could be changed to have the `isHomestead()` method return true.

Alternatively the `runBlock()` call can be adjusted in addition to the proposed `runCode()`/`runTx()` in https://github.com/ethereumjs/ethereumjs-vm/issues/52

**Comment by nmushegian** [comment]
delegatecall is used for solidity's libraries now, so +1 bump

**Comment by axic** [comment]
@tcoulter is this implemented now?

**Comment by tcoulter** [comment]
Yep. Sorry, was implemented here: https://github.com/ethereumjs/testrpc/commit/8e76d6b294d47824bf6eb0aa62182d3831e7832c

Closing.
