### ISSUE TITLE
cannot run testrpc on mac (wrong line ending?)

### ISSUE THREAD

**Issue by SCBuergel** [ConsenSys-archive/ganache-cli-archive#391]
I installed testrpc on MacOS and then tried running it and ran into an error:
```
$ npm install ethereumjs-testrpc -g
$ testrpc
env: node\r: No such file or directory
```
This used to work well but now shows the above error. The issue is clearly related to [this one](https://github.com/ethereumjs/testrpc/issues/388) and hence I managed to fix it by opening /usr/local/bin/testrpc (which seems to link to /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js), removing the line break in line 1 and adding it again and saving the file.

**Comment by tcoulter** [comment]
Hi there. Thanks for the report! The issue has been fixed in v4.1.3. Cheers!
