### ISSUE TITLE
msg.sender not properly verified in library external function calls

### ISSUE THREAD

**Issue by cbdotguru** [ConsenSys-archive/ganache-cli-archive#399]
## Expected Behavior
When calling an external library function from within another library function, the msg.sender should be the linked contract address.

## Current Behavior
The msg.sender is the original caller as if it is a delegate call opcode

## Possible Solution
Ensure the msg.sender is set as the contract because that is what the actual blockchain sets it as

## Steps to Reproduce (for bugs)
1. Create a library with a function that checks `require(msg.sender == callingEOAAddress)` at the beginning
2. Create another function in the same library that calls the previous function
3. Call function number 2 and it will pass the `require` in function number one

## Context
This created a situation where our function passed in testrpc but failed on the testnet because the testnet registered the `msg.sender` of function number one as the contract address.

## Your Environment
* Version used: 4.1.1
* Link to your project: https://github.com/Majoolr/ethereum-libraries

**Comment by eshaben** [comment]
Thank you @Hackdom for submitting this issue. When calling a library function the code is executed in the context of the calling contract, but `msg.sender` does not change it's value, therefore it is the externally owned account that should be the `msg.sender`. I verified this on the Ropsten test network using version `0.4.24` of Solidity.
