### ISSUE TITLE
Truffle v4 turned off the optimizer, default gas limit needs to be increased

### ISSUE THREAD

**Issue by roderik** [ConsenSys-archive/ganache-cli-archive#410]
I hit this issue and documented it int he truffle issues. https://github.com/trufflesuite/truffle/issues/648

@gnidan suggested to open a ticket here to fix this for the people that niot use testrpc built in to truffle

**Comment by benjamincburns** [comment]
Thanks, @roderik - it'll be in the next release, which if my schedule permits, should go out by tomorrow evening, EDT.

**Comment by benjamincburns** [comment]
I increased the default block gas limit in ganache-core, commit [088d040](https://github.com/trufflesuite/ganache-core/commit/088d0401a6bb2914edeaf56b01f4e161c9e3be9e). I likely have some readme changes to make as well, those will follow shortly.
