### ISSUE TITLE
Unable to run npm install ethereum-testrpc web3

### ISSUE THREAD

**Issue by arjunkapur95** [ConsenSys-archive/ganache-cli-archive#415]
Hi guys so i am facing this issue when i try to run the command npm install ethereum-testrpc web3.

As of now i have tried the basic fixes that is uninstall web3 and testrpc and install it back.I am pretty lost at this point but if my understanding is correct as of now   even though test-rpc is installed and running .(I have tested that ), for some reason ethereum-testrpc@latest is missing.

 

## Current Behavior

![stuck](https://user-images.githubusercontent.com/18692367/32406567-fc94f536-c1ce-11e7-949c-3d80718aa813.PNG)

Error Log File for the entire output is as follows

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ethereum-testrpc',
1 verbose cli   'web3' ]
2 info using npm@5.5.1
3 info using node@v8.4.0
4 verbose config Skipping project config: C:\Users\AJ/.npmrc. (matches userconfig)
5 verbose npm-session ca39aa28f4079330
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/web3 637ms (from cache)
9 silly pacote tag manifest for web3@latest fetched in 637ms
10 http fetch GET 404 https://registry.npmjs.org/ethereum-testrpc 2486ms
11 silly fetchPackageMetaData error for ethereum-testrpc@latest 404 Not Found: ethereum-testrpc@latest
12 verbose stack Error: 404 Not Found: ethereum-testrpc@latest
12 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
12 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
12 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
12 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
12 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
12 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at runCallback (timers.js:781:20)
12 verbose stack     at tryOnImmediate (timers.js:743:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
13 verbose cwd C:\Users\AJ\Desktop\win-unpacked
14 verbose Windows_NT 10.0.15063
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ethereum-testrpc" "web3"
16 verbose node v8.4.0
17 verbose npm  v5.5.1
18 error code E404
19 error 404 Not Found: ethereum-testrpc@latest
20 verbose exit [ 1, true ]

Any help would be appreciated, maybe you guys can make sense of the debug log , i dont see what ive done wrong.

**Comment by roderik** [comment]
`npm i ethereumjs-testrpc`, you are missing the "js" part

**Comment by arjunkapur95** [comment]
thanks a lot silly mistake, that fixed my error

**Comment by ongweijie** [comment]
I have tried to install the ethereum-testrpc web3 on the node.js 8.9.4 but I keep getting this error. I don't know if it is a problem if I want to use this while learning how to code ethereum.

```
npm WARN deprecated ethereumjs-testrpc@6.0.3: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-11T09_41_42_045Z-debug.log
```

**Comment by roderik** [comment]
install "git" to fix this

**Comment by cmuhirwa** [comment]
Git is installed i am even running (npm install -g ethereumjs-testrpc) from gitbash, but still not working
