### ISSUE TITLE
Error when trying to install testrpc

### ISSUE THREAD

**Issue by geminifund** [ConsenSys-archive/ganache-cli-archive#416]
I ran this to install testrpc 
sudo npm install -g ethereumjs-testrpc

but then I get this error.  I've looked around online but can't seem to figure out how to resolve this error.  Any ideas?  Thanks

npm WARN engine hash-base@3.0.4: wanted: {"node":">=4"} (current: {"node":"0.10.44","npm":"2.15.0"})
/
> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/lib/node_modules/ethereumjs-testrpc/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'sync-exec'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/lib/post_install.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.44","npm":"2.15.0"})
npm ERR! Linux 3.19.0-22-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! This is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by Febin-chain** [comment]
I am also facing the same issue, Could someone please help us

**Comment by benjamincburns** [comment]
@geminifund from your error message it looks like you're running node v0.10.44. TestRPC is meant to run against node v6.11.5 and later, however I'd highly recommend choosing the latest lts release, v8.9.0.

Please reopen if updating to a later version of node does not fix your problem.
