### ISSUE TITLE
Unable to sign transaction using web3

### ISSUE THREAD

**Issue by th4s** [ConsenSys-archive/ganache-cli-archive#418]
Currently developing a frontend in Typescript using Angular 4 and Web3 for communicating with local geth node. Tried to set up a testnet with testrpc.

I was unable to sign transactions using web3 signTransaction when my local testnet was testrpc. With the exactly same frontend code I was able to sign transactions on the mainnet using a standard gethnode with web3.

**Comment by mikeseese** [comment]
Closing due to age/inactivity. Our tests test signed transactions using web3, so this should be working now. If you're having issues still, please open a new issue. Thanks!
