### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by didil** [ConsenSys-archive/ganache-cli-archive#422]
I'm running mac os sierra 10.12.6 / node 8.2.1 / testrpc 6.0.1 and I've been getting this crash randomly since I updated to testrpc 6.0.1 from testrpc 4.x , especially when running truffle mocha tests

/Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:68497
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONME

TypeError: Cannot read property 'get' of undefined
    at dbGet (/Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61930:7)
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17591:5
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23173:20
    at iterate (/Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23254:13)
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23266:29
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23036:16
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17596:7
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61935:9
    at dispatchError (/Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:33055:36)
    at /Users/x/.nvm/versions/node/v8.2.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:22826:14

**Comment by benjamincburns** [comment]
I've seen this one myself on occasion. Will definitely be looking into it soon.

**Comment by benjamincburns** [comment]
@didil and thanks for reporting it!

**Comment by benjamincburns** [comment]
@didil lets track this over on #417
