### ISSUE TITLE
Requesting tx by unknown hash should return null, not an error.

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#429]
Currently requesting a tx by unknown hash returns an error with an internal testrpc stack trace.

Geth/Parity simply return `null`, to represent no entry by that hash.

We could use this behavior corrected in MetaMask to help us detect when testrpc is reset, so we can fix our nonce calculation in development situations:
https://github.com/MetaMask/metamask-extension/issues/1999

**Comment by benjamincburns** [comment]
Sounds like an easy one. Will short list it if it’s blocking you guys.

**Comment by danfinlay** [comment]
It would definitely make it much easier to help these devs, thank you!

**Comment by benjamincburns** [comment]
Just capturing some external conversation here - it looks like `ganache-cli` v6.0.3 has the correct behaviour, as does Ganache v1.0.1. @danfinlay said he was testing with TestRPC v4.1.3. I'll double check the annotated code, but I'm betting we added the checks which produce this output between v4.1.3 and v6.0.3.

@danfinlay - please reopen if there's still an issue.
