### ISSUE TITLE
testrpc: command not found on Mac

### ISSUE THREAD

**Issue by xx11dragon** [ConsenSys-archive/ganache-cli-archive#430]
I am trying to install testrpc on  my mac (macOS v10.13.1, npm v 5.5.1, node v8.9.1).

`Command:   sudo npm install -g ethereumjs-testrpc`
Log:    
```
/usr/local/Cellar/node/8.9.1/bin/testrpc -> /usr/local/Cellar/node/8.9.1/lib/node_modules/ethereumjs-testrpc/build/cli.node.js
+ ethereumjs-testrpc@6.0.3
updated 1 package in 18.567s
```

and i starting testrpc.
`Command:   testrpc`
Log:
`-bash: testrpc: command not found`

How start testrpc?

**Comment by Asone** [comment]
That's odd

have you check that you got access to testrpc through /usr/local/bin ? 

Other wise you might need to create a symlink there pointing to testrpc 

`sudo ln -s /usr/local/bin/testrpc <pathToTestRPC>`

**Comment by benjamincburns** [comment]
@xx11dragon try `npm install -g ganache-cli` and run using the `ganache-cli` command. This is the same as TestRPC, we've just renamed it.

Also chances are if you have to run `npm install -g` with `sudo` you aren't using [NVM](https://github.com/creationix/nvm). I highly recommend using this tool.

**Comment by benjamincburns** [comment]
@xx11dragon I'll assume that by closing this issue that my last response got you sorted. Glad I could help, and don't hesitate to reach out again in the future.

**Comment by joepagan** [comment]
Just as a heads up `yarn global add ganache-cli` doesn't seem to add `ganache-cli` as a command, whereas `npm install -g ganache-cli` does.

**Comment by jbarros35** [comment]
NOENT: no such file or directory, access '/usr/local/lib/node_modules/ganache-cli'

**Comment by dnewton090** [comment]
Hi, 
I'm encountering a permissions error on installing the Ganache CDI as follows:
>> npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
>> npm ERR! path /usr/local/lib/node_modules
>> npm ERR! code EACCES
>> npm ERR! errno -13

I was wondering the best way to get around this? I haven't used sudo commands to date, but is a syntax using it available here?

**Comment by mikeseese** [comment]
@dnewton090 unfortunately `/usr/local/lib/` is only accessible by privileged users. In your setup, you would need to use `sudo npm install -g ganache-cli`.

You could consider using [nvm (Node Version Manager)](https://github.com/creationix/nvm#installation) instead of installing node/npm to the system directory. If you did use `nvm`, `sudo` wouldn't be necessary as it would install to your home directory.

With that said, prepending `sudo` (assuming you have sudo access) to the command will mitigate this error.
