### ISSUE TITLE
Where is TestRPC?

### ISSUE THREAD

**Issue by hackingbeauty** [ConsenSys-archive/ganache-cli-archive#432]
This is confusing.  I came to this page expecting information on TestRPC; however, instead it's a repo on Ganache-CLI which appears to be new.

I'm just interested in installing and starting TestRPC from the terminal.  Is this gone now?

**Comment by benjamincburns** [comment]
‘ganache-cli’ is the same TestRPC that you know and love, but we’ve
migrated it under the Truffle org and renamed it to be more in line with
the Truffle suite of tooling we’re building out.

Today the only thing that has changed is the repo location on GitHub, the
npm package name, and the command you type to launch it. Have a look at the
updated README for more info!

**Comment by JasonGiedymin** [comment]
Might be useful to just say outright that __"`testrpc` has been renamed to `ganache-cli`. Use `ganache-cli` in place of `testrpc`"__.

**Comment by JasonGiedymin** [comment]
Otherwise, thanks for adopting it. 👍

**Comment by benjamincburns** [comment]
@JasonGiedymin good idea!

```bash
$ npm install -g ethereumjs-testrpc
npm WARN deprecated ethereumjs-testrpc@6.0.3: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
```

;-)

**Comment by JasonGiedymin** [comment]
Just need one more arrow/sign. A few too many new people are coming from testrpc docs. Which say depreciated. So they’re not going to ‘npm install’ it. They almost don’t believe the rename I guess (cautious ppl?).

In fact I was asked this very question by a dev for the second time. Which is why I’m here, got off my ass to see what happened.

I’ll PR it if I get asked one more time. :-D

**Comment by benjamincburns** [comment]
> A few too many new people are coming from testrpc docs. Which say depreciated.

@JasonGiedymin -- thanks for this. Can you please point me at the docs to which you're referring so that I can update them? Alternatively feel free to submit a PR if you're talking about our README.md!

**Comment by realChainLife** [comment]
@JasonGiedymin tx man, saved a life
