### ISSUE TITLE
web3.utils.soliditySha3() is not available via TestRPC

### ISSUE THREAD

**Issue by jakublipinski** [ConsenSys-archive/ganache-cli-archive#434]
[web3.utils.soliditySha3()](https://web3js.readthedocs.io/en/1.0/web3-utils.html#soliditysha3) is part of the standard Web3 interface. Unfortunatelly is not available from TestRPC. Please consider adding it.

**Comment by mikeseese** [comment]
This was implemented in the meantime. Thanks!
