### ISSUE TITLE
Invalid opcode on require() when running tests under truffle develop

### ISSUE THREAD

**Issue by jakublipinski** [ConsenSys-archive/ganache-cli-archive#435]
## Expected Behavior
You can use [`require()`](https://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions) to ensure valid contract conditions. It executs`REVERT` opcode when `require()` condition is not met.  It seems TestRPC does not support it and throws `Error: VM Exception while processing transaction: invalid opcode` when `REVERT` instruction is encountered.

It should be possible to create a test which asserts that `REVERT` instruction was executed when running particular test:
```
await tc.testRequire(false, {from: accounts[0]});
assert.revert("Contract didn't revert")
```

## Current Behavior
TestRPC throws `Error: VM Exception while processing transaction: invalid opcode` when REVERT opcode is executed.

## Possible Solution
Support for `REVERT` opcode and introduce `assert.revert()`.

## Steps to Reproduce (for bugs)
Init truffle:
`truffle init`

Put the following contract into the `contracts` folder as `TheContract.sol`:
```
pragma solidity ^0.4.18;

contract TheContract {
    function testRequire(bool param) {
        require(param == true);
    }
}
```

Put the following test into the `test` folder as `TestTheContract.js`:
```
var TheContract = artifacts.require("TheContract");

contract('TheContract', function(accounts) {

    it("should be able to test the contract with require", async function() {
        var tc = await TheContract.deployed();

        console.log('about to run testRequire(true)')
        await tc.testRequire(true, {from: accounts[0]});
        console.log('testRequire(true) passed')

        console.log('about to run testRequire(false)')
        await tc.testRequire(false, {from: accounts[0]});
        console.log('testRequire(false) passed') // unreachable code
  });
});
```

Alter `1_initial_migration.js` accordingly and run:
`truffle develop`

Run:
`truffle test`

The output will be:
```
Using network 'develop'.



  Contract: TheContract
about to run testRequire(true)
testRequire(true) passed
about to run testRequire(false)
    1) should be able to test the contract with require
    > No events were emitted


  0 passing (94ms)
  1 failing

  1) Contract: TheContract should be able to test the contract with require:
     Error: VM Exception while processing transaction: invalid opcode
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:331156:36
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:329855:7)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
```

## Context
I'd like to be able to test all the contract's conditions.

## Your Environment
* Version used:
Truffle: `Truffle v4.0.1 (core: 4.0.1)`
Solidity: `Solidity v0.4.18 (solc-js)`
* Operating System and version:
`macOS High Sierra Version 10.13.1`

**Comment by hiqua** [comment]
Which version of testrpc are you using? testrpc (ganache-cli) supports revert as of v6.0.1 according to https://github.com/trufflesuite/ganache-cli/releases/tag/v6.0.1.

**Comment by benjamincburns** [comment]
@jakublipinski `REVERT` and other byzantium changes should be supported as of the 6.x releases. 

I do reproduce this error when following the repro steps you describe, but when I run my own instance of `ganache-cli` and test against that, the test fails as I'd expect. This makes me think that Truffle v4.0.1 is actually built against an older release of `testrpc`, which I don't think was supposed to be the case. I'll look into this.

In the mean time if you want to configure this workaround so that you can run your own ganache-cli instance, add a `development` network to your `truffle.js` config like in the following:

```javascript
module.exports = {
  networks: {
    "development": {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};
```

Then simply run `ganache-cli` in a separate terminal before running `truffle test`.


Example output from testing against `ganache-cli` v6.0.3:

```
Contract: TheContract
about to run testRequire(true)
testRequire(true) passed
about to run testRequire(false)
    1) should be able to test the contract with require
    > No events were emitted


  0 passing (203ms)
  1 failing

  1) Contract: TheContract should be able to test the contract with require:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:331156:36
      at /Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/bburns/.nvm/versions/node/v9.0.0/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
```

**Comment by Blackening999** [comment]
TID-s3vvc WARN: IOError: VM Exception while processing transaction: invalid opcode

Error appear just by performing a simple transaction of checking balance:

```

  mapping(address => uint256) zombiesToPower;

  function addZombieWithPower(address _zombie, uint256 _power) public returns (bool success) {
    zombiesToPower[_zombie] += _power;
    return true;
  }
```

Tests are written in Solidity - passes

pragma solidity ^0.4.18;

Ganache CLI v6.0.3 (ganache-core: 2.0.2)

**Comment by benjamincburns** [comment]
Truffle was updated to depend on the post-byzantium release of ganache-core as of Truffle v4.0.3.

If you're still experiencing this issue when running `truffle test` against truffle's internal test network (the default behavior), or when running the `test` command after running `truffle develop`, please make sure you've updated to the latest release of Truffle.

If you're still experiencing this behavior when using an external instance of Ganache, make sure that

1. You're using `ganache-cli` and not `testrpc`, as we no longer maintain this code under the name `testrpc`.
2. Your installation of `ganache-cli` is the latest release. To ensure this is the case, run `npm install -g ganache-cli@latest`

**If none of the above steps solve this problem for you, please open a new issue rather than continuing to comment here.**

**Comment by benjamincburns** [comment]
@Blackening999 per my previous comment, can you please open a new issue for that? What you're describing is a bit different from the original issue which @jakublipinski raised, and may require a separate fix.

Edit: If possible, please also be sure to include a minimum runnable reproduction in your issue. I'm the sole maintainer of this project and I've been away for a week so I'm a bit bogged down with reproductions at the moment.
