### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by pszwec** [ConsenSys-archive/ganache-cli-archive#441]
I'm a noob an not sure where to ask a question so I'm trying here. I've downloaded this and installed it on a Windows 10 PC. My question is how do I create some "test" ether to use? Or do I actually have to purchase some and send it to some the accounts (those 10) that it creates when it starts up? Seems like I would lose the real ether once I closed it down.

Thanks and sorry in advance,

Peter

**Comment by KillariDev** [comment]
Check out the readme. You can generate ether on your account with --account parameter, like this:
ganache-cli --account="<privatekey>,balance" [--account="<privatekey>,balance"]

where balance is amount of wei you want to add to your account.

**Comment by pszwec** [comment]
Where are you getting the extra info? I did check out the read me 1st and it says the account to specify the number of account to create...I didn't see balance anywhere. Thanks Peter
Command Line

$ ganache-cli <options>
Options:

-a or --accounts: Specify the number of accounts to generate at startup.

**Comment by pszwec** [comment]
Thank you. I saw that and thought chicken and egg. I need an account number to add fake ether to yet the 10 accounts are created upon generation, so what to use as the 64 bit account number?......I guess I use my real account from my wallet, right?

**Comment by KillariDev** [comment]
You can launch the ganache-cli once and it will print out few keypairs that you can use. You can also use your real account (but I wouldn't recommend it). You can also use any other wallet to generate keypair.

**Comment by pszwec** [comment]
I'm still stuck.  I've copied out the 10 default private keys and accounts. The problem as I see it is the private keys don't match the read.me.
•	--account: Specify --account=... (no 's') any number of times passing arbitrary private keys and their associated balances to generate initial addresses:
$ ganache-cli --account="<privatekey>,balance" [--account="<privatekey>,balance"]
Note that private keys are 64 characters long, and must be input as a 0x-prefixed hex string. Balance can either be input as an integer or 0x-prefixed hex value specifying the amount of wei in that account

###  The accounts start with the 0x prefix but are not 64 characters long, the private keys are 64 characters but don't start with 0x. Here are the 1st 3
Available Accounts
==================
(0) 0x5b3f12905878ca686c5d7a9a456a9d6175800a1a
(1) 0x5273744aa54ff86a16eb3db2dc3aa98223b5cdf9
(2) 0x71b7c0b41015c1210d20383bbe5e2a1db9227b23

Private Keys
==================
(0) 4101df7c41e70291993f0672c48ebe36f4f44a710ad1cbf228f322b8d830e735
(1) c00d98fb8d2a37a067e24ea19e4a3e04a01ae13d8f63c86521419db869689f0b
(2) cad375ffe824988d616add7f01215f380dbd5e1590e87d4658dc6ae58e26c744

So I've tried both keys and accounts with this command  
C:\Users\Peter's Laptop>ganache-cli --accounts="c00d98fb8d2a37a067e24ea19e4a3e04a01ae13d8f63c86521419db869689f0b, 444444"



and get the following error

cannot read property address of undefined, on Friday I was getting invalid length of address

IF there is a forum please point me to it. If this is the correct place to ask these questions great. (Sorry for  the large text, I can't get rid of it)

**Comment by benjamincburns** [comment]
@pszwec definitely don't use your real account! There's no need, and you may inadvertently risk leaking your secrets!

Ganache (CLI or otherwise) goes best with [truffle](http://truffleframework.com/)! For instance, with truffle you can easily write JavaScript tests like:

```javascript

var MyContract = artifacts.require("MyContract");

contract("MyContract", function(accounts) {
  it('should do some transaction', function() {
    MyContract.deployed().then(function(contractInstance) {
        return contractInstance.someExampleFunction("arg1", "arg2", { from: accounts[0] });
    })
    .then(function(receipt) {
        assert.equal(receipt.status, 1);
    });
  });
})
```

Have a look at these tutorials to see how best to get started, though I highly recommend having a look through the entire Truffle docs page.

http://truffleframework.com/docs/getting_started/testing
http://truffleframework.com/docs/getting_started/javascript-tests
http://truffleframework.com/docs/getting_started/solidity-tests
http://truffleframework.com/docs/ganache/using

Finally, I highly recommend asking questions like these in our [gitter channel](https://gitter.im/ConsenSys/truffle). We have nearly 2500 community members in there who can offer help much more quickly than GitHub issues.
