### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by jorgeog96** [ConsenSys-archive/ganache-cli-archive#443]
I can´t migrate contracts to the network. Truffle doesn´t find a network specified. 

 

## Steps to Reproduce (for bugs)

1. Configured truffle.json
2. Compile code
3. Try to migrate (truffle migrate)
4. "Could not connect to your Ethereum client"

## Context

jorgeog96@Jorge-Osorio:~$ npm install -g ganache-cli
npm ERR! path /home/jorgeog96/.nvm/versions/node/v9.2.0/lib/node_modules/ganache-cli/node_modules/des.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/jorgeog96/.nvm/versions/node/v9.2.0/lib/node_modules/ganache-cli/node_modules/des.js' -> '/home/jorgeog96/.nvm/versions/node/v9.2.0/lib/node_modules/ganache-cli/node_modules/.des.js.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jorgeog96/.npm/_logs/2017-12-07T02_20_39_678Z-debug.log

then...

jorgeog96@Jorge-Osorio:/mnt/c/Users/jorge/Desktop/OVX/Solidity/Token/OVXET$ truffle migrate --reset
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

## Your Environment

* Version used: Truffle v4.0.1 & Solidity v0.4.18
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Ubuntu subsystem for Windows
* Server type and version: node v9.2.0 & nvm 0.33.6
* Operating System and version: Windows 10
* Link to your project:

**Comment by jorgeog96** [comment]
Reinstall Truffle in another way and reinstalling ganache-cli...now it looks better. Ganache CLI v6.0.3 installed, node v9.2.0, Truffle v4.0.1, Solidity v0.4.18, npm v5.5.1 and nvm 9.2.0. 

But the same error appears when I'm trying to deploy a contract...in the migration step: 

jorgeog96@Jorge-Osorio:/mnt/c/Users/jorge/Desktop/OVX/Solidity/Token/OVXET$ truffle migrate
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

jorgeog96@Jorge-Osorio:/mnt/c/Users/jorge/Desktop/OVX/Solidity/Token/OVXET$ truffle networks
Contracts have not been deployed to any network.

And this is the configurated truffle.js:
module.exports = {
    networks: {
      development: {
        host: "localhost",
        port: 8545,
        network_id: "*"
      }
    }
};

Maybe, the process is not easy, because i´m using an Ubuntu Subsystem for Windows 10 ...

**Comment by benjamincburns** [comment]
@jorgeog96 try replacing `localhost` in your `truffle.js` with `127.0.0.1`. `ganache-cli` only listens on IPv4, and IIRC on some systems when you use the `localhost` hostname it won't try falling back to IPv4 after it tries IPv6.

**Comment by benjamincburns** [comment]
also I think you don't need the `--network` flag when you invoke `truffle migrate` because you've set the `development` network, but just to rule out that problem please try doing

`truffle migrate --network development`

**Comment by mikeseese** [comment]
Closed due to inactivity/age
