### ISSUE TITLE
When >1 transactions in a block, incorrect .gasUsed and .cumulativeGasUsed.

### ISSUE THREAD

**Issue by beether** [ConsenSys-archive/ganache-cli-archive#445]
## Expected Behavior
When multiple transactions occur in a block, each transaction's `.gasUsed` should reflect the gas used in that transaction alone.

## Current Behavior
Each transaction's `.gasUsed` will equal the `.cumulativeGasUsed`.

## Steps to Reproduce (for bugs)
I'm too lazy to post this now.  It honestly has not been worth my time posting things because they often get ignored.

Do more than one transaction in a block and look at .gasUsed for each transaction.  The number will always be increasing for each transaction, since each successive .gasUsed is actually (previous .gasUsed + ownGasUsed).  It seems as though `.gasUsed` is what `.cumulativeGasUsed` should be.

Furthermore, `.cumulativeGasUsed` will be the same for each transaction (that of the last transaction).

I currently work around this by subtracting from the end to the beginning.

eg:  tx[n].gasUsed = tx[n].gasUsed - tx[n-1].gasUsed;
n--;

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by AugustoL** [comment]
I updated to the latest version and Im having weird errors about the gasUsed too, dont know why, and my backs have 1 tx all of them, usually is when ETH is transfered using `transfer` method.

**Comment by Steffen93** [comment]
I can confirm this issue. Calling the same method multiple times in one block with a fixed blocktime multiplies the amount of `gasUsed` in the transaction receipt.
I'm using version 6.0.3

**Comment by davidmurdoch** [comment]
Thanks @beether! Fixed in https://github.com/trufflesuite/ganache-core/commit/72efbd7b4d57955559a76521e90c2a4d418ce384
