### ISSUE TITLE
TransactionReceipt Status returns an integer instead of Hex

### ISSUE THREAD

**Issue by juanfranblanco** [ConsenSys-archive/ganache-cli-archive#451]
## Expected Behavior
The TransactionReceipt Status field should return a Hex value, this is the standard (if it has not changed :)) for all Eth RPC calls.

## Current Behavior
Returns an integer, so when trying to convert from a hex string it fails.

## Steps to Reproduce (for bugs)
1. Send a Transaction
2. Get the Receipt
3. Inspect Json output.
4.

**Comment by Enigmatic331** [comment]
I think what happened was previously the transaction hash (hex) was returned, but with the Byzantium fork a status (integer) is returned instead... Hmm. Still trying to figure out how to get around this.

Below an example screenshot of Testrpc (pre-Byzantium) vs Ganache (post-Byzantium) when I deploy the same contract:

![image](https://user-images.githubusercontent.com/28551011/34928080-19f3eccc-f9f6-11e7-8554-aced1b7d3b07.png)

**Comment by Enigmatic331** [comment]
To support what @juanfranblanco had mentioned - Below is a screenshot of status returned from ethereum mainnet vs Ganache. Still thinking of a way around this....

![image](https://user-images.githubusercontent.com/28551011/34929092-c3c86736-f9fc-11e7-9eec-4712116142a0.png)

**Comment by benjamincburns** [comment]
Thanks for reporting, @juanfranblanco & @Enigmatic331! This is fixed in the current `develop` branch and will go out with the next release.

**Comment by Frax0r** [comment]
Good work guys thanks for fix!
