### ISSUE TITLE
ganache-cli command not found MacOS High Sierra 

### ISSUE THREAD

**Issue by pradeeps** [ConsenSys-archive/ganache-cli-archive#452]
running ganache-cli returns command not found

## Expected Behavior
ganache-cli should return something and should not say command not found

## Current Behavior

MacBook-Pro:~ susarla$ ganache-cli
-bash: ganache-cli: command not found

## Steps to Reproduce (for bugs)
ganache-cli

## Context
I am trying to run ganache-cli

## Your Environment
I am running MacOS HS 10.13.1 with 

MacBook-Pro:~ susarla$ node -v
v8.9.3
MacBook-Pro:~ susarla$ npm -v
5.5.1
MacBook-Pro:~ susarla$ which node
/usr/local/bin/node
MacBook-Pro:~ susarla$ which npm
/usr/local/bin/npm

**Comment by 0xNPE** [comment]
did you `npm install -g ganache-cli`?

see: https://github.com/trufflesuite/ganache-cli#installation

**Comment by 0xcpu** [comment]
I've encountered same issue after installing `ganache-cli` with `npm` on `Debian 9 x86_64`.

[Update] Solved the issue by using `sudo` when installing the package.

**Comment by benjamincburns** [comment]
To fix this problem make sure that

1. You've installed ganache-cli globally by doing `npm install -g`
2. Your npm global bin directory is in your `PATH`. You can find your npm global bin directory by running `npm bin -g`

For item 2, copy and paste this one-liner and it'll tell you whether or not you're in good shape:

`echo $PATH | grep -q "$(npm bin -g)" && echo "Your PATH is set up correctly." || echo "You need to add '$(npm bin -g)' to your path variable."`

**Comment by jbarros35** [comment]
NOENT: no such file or directory, access '/usr/local/lib/node_modules/ganache-cli'
still not working

**Comment by jbarros35** [comment]
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/ganache-cli
npm WARN webpack-cli@2.0.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /usr/local/lib/node_modules/ganache-cli
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/ganache-cli'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-04-07T13_59_07_679Z-debug.log

**Comment by urssanj00** [comment]
sudo su 
npm install -g ganache-cli
root@ide:/# cd /usr/bin
root@ide:/usr/bin# ls -lrth

you will get below type of listing 
lrwxrwxrwx 1 root root      38 Aug  8 12:09  ganache-cli -> ../lib/node_modules/ganache-cli/cli.js

root@ide:/usr/bin# ./ganache-cli 

and it started.

**Comment by bhushanjpawar** [comment]
I faced similar issue for MacOS Catalina. 
ganache-cli command not found 

Below is the perfect solution worked for me:

run npm bin -g
--
You will get result something like /usr/local/Cellar/node/16.0.0/bin (not in PATH env variable)
run export PATH=$PATH:/Users/bhushanpawar/.npm-global/bin
on zsh this also works path+=(/Users/bhushanpawar/.npm-global/bin)
