### ISSUE TITLE
uint x minus x  throws "base fee exceeds gas limit"

### ISSUE THREAD

**Issue by szerintedmi** [ConsenSys-archive/ganache-cli-archive#458]
## Current Behavior
Ganache throws when a transaction has an operation of x - z and the result is 0 (i.e. x == z)

## Steps to Reproduce (for bugs)
```
/* Calling sub(1) or sub1() works fine on javascriptVM, fails on testrpc/ganache-cli 6.0.3 */
pragma solidity ^0.4.0;

contract Test {

  uint public counter = 1;
  
  function set(uint a) public returns(uint c) {
      counter = a;
      return counter;
  }
  
  function sub(uint a) public returns(uint c) {
      counter = counter - a;
      return counter;
  }
  
  function sub1() public returns(uint c) {
      counter -= 1;
      return counter;
  }
  
}
```

Calling sub(1) or sub1() on ganache:
```
transact to Test.sub errored: Error: base fee exceeds gas limit
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69361:17)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36) 
```

## Your Environment
* Version used: Ganache CLI v6.0.3 (ganache-core: 2.0.2)   but fails with TestRPC v4.1.3 ganache-core: 1.1.3 too
* Remix IDE

**Comment by szerintedmi** [comment]
even this throws the same error:
```
/* Calling set() works fine on javascriptVM, fails on testrpc/ganache-cli 6.0.3 */
pragma solidity ^0.4.18;

contract Test {

  uint public counter = 1;
  
  function set() public  {
      counter = 0;
  }
  
}
```

**Comment by benjamincburns** [comment]
Hi @szerintedmi, thanks for reporting this.

My strong suspicion is that remix is setting a very low gas limit for the transaction you're running. That is, the error is telling you that your gas limit is so low that it won't even bother to try and run the transaction in question. As for why this is happening, see [this](https://ethereum.stackexchange.com/a/13041/17829) excellent StackOverflow answer.

Just to confirm this is what's happening, can you please try running `ganache-cli --verbose` and paste the full log here? This will let me see the requests/responses that are going between remix and ganache-cli.  This output may be quite long, so you may need to create a new gist for it.

**Comment by szerintedmi** [comment]
[ganache.out](https://gist.github.com/szerintedmi/c0a10c1773f0f916b03a4abfbd7c89fe) for this code:
```
/* Calling set() works fine on javascriptVM, fails on testrpc/ganache-cli 6.0.3 */
pragma solidity ^0.4.18;

contract Test {

  uint public counter = 1;
  
  function set() public  {
      counter = 0;
  }
  
}
```

**Comment by benjamincburns** [comment]
I don't see the error you listed above in that output, or any errors for that matter.

**Comment by owidder** [comment]
I do get the same error. The following contract throws this error when "setTestVal" is called at first with 1 and then with 0:
```solidity
contract ErrorTest {
    int testval;

    function setTestval(int val) public {
        testval = val;
    }
}
```
On a local geth node it works fine.

(Ganache 1.1.0 on Mac)

**Comment by b232wang** [comment]
## One possible solution is use `uint(-1)` instead of `0`  

https://www.npmjs.com/package/@ventureum/conversion

This package can solve it without change the interface of contract, all the in/out will not change.

**Comment by davidmurdoch** [comment]
This should now be fixed by https://github.com/trufflesuite/ganache-core/commit/81e8f59d74bcb38773498c34c78fb7d35a22af7f in ganache-cli 6.1.7 and ganache-core 2.2.0. Please update and let us know if it's still a problem.
