### ISSUE TITLE
VM Exception while processing transaction: stack underflow

### ISSUE THREAD

**Issue by c1tt1** [ConsenSys-archive/ganache-cli-archive#465]
I have the following functions which store some info in a map:

The following are JS and Solidity code:
```js
const storeData = async(name, hash) => {
  await contractInstance.storeData(name, hash, { from: web3.eth.accounts[0] })
}
```
```js
mapping (bytes16 => bytes16) nameAndhash;

bytes16[] public imageList;

function storeData(bytes16 name, bytes16 imageHash) public {
  nameAndhash[imageHash] = name;
  imageList.push(imageHash);
}
```

When invoked I get the following error:
```Error: VM Exception while processing transaction: stack underflow```

I have tried both ganache and testrpc here are the logs:

```
  Transaction: 0x21dbebdd360197e2b8b7383f568b874fd41200b8fb5e2257b546defe1e582223
  Contract created: 0xf58d311145c64569b711b7666e119f14a57c657f
  Gas usage: 90000
  Block Number: 11
  Block Time: Wed Jan 17 2018 14:22:04 GMT+0000 (UTC)
  Runtime Error: stack underflow
```

**Comment by benjamincburns** [comment]
Hi @stern0 - have you tried stepping through this with `truffle debug`?

**Comment by c1tt1** [comment]
Hi @benjamincburns I am not using truffle.

**Comment by benjamincburns** [comment]
Ah, that's a bit sad. I suspect `truffle debug` would help in this case.

Either way, can you please post a minimum runnable example? The code you posted gives a hint, but it doesn't show me how you call `storeData` in JavaScript. A running example is the fastest way for me to diagnose this.

**Comment by c1tt1** [comment]
@benjamincburns here is an example of the using the `storeData` function.

```js
storeData('20180303_tropical_america', '34f7a3113803f8ed3b8fd7ce5656ebec')
  .then(res => console.log(res))
  .catch(err => console.log(err))
```

**Comment by LayneHaber** [comment]
@stern0 did you end up figuring out why this was happening? Running into something similar, and not sure why

**Comment by c1tt1** [comment]
I did not continue with it, but I think it's still a pending issue.

**Comment by krzkaczor** [comment]
In my case, it happened b/c we did malformed `eth_call`, without `to` param.

**Comment by dfsantamaria** [comment]
I'm experiencing the same issue. I have opened a thread here: https://stackoverflow.com/questions/60581930/web3j-gets-stack-underflow-error-with-ganache/60598228#60598228 . Any solution?

**Comment by boolafish** [comment]
Plus one here, suddenly seeing this issue on our contract repo too
- CI job failure: https://app.circleci.com/pipelines/github/omgnetwork/plasma-contracts/2354/workflows/7489954e-7f6b-4909-809c-a279b8bf2b77/jobs/12396
- repo/issue: https://github.com/omgnetwork/plasma-contracts/issues/664
