### ISSUE TITLE
Ganache client does not start

### ISSUE THREAD

**Issue by MartinKrmer** [ConsenSys-archive/ganache-cli-archive#469]
Hi,
am doing tutorial but I am stuck at the beginning.
If I try to run ganache-cli, I get:

ar Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!

can someone help me what the reason for? Yesterday testrpc was working. Today both are not working.

**Comment by benjamincburns** [comment]
Hi @MartinKrmer - Can you please include the actual error? It seems you've copied some arbitrary part in the middle of the output here, but missed the relevant bits.

**Comment by MartinKrmer** [comment]
Error: listen EADDRINUSE :::8545
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at Server.listen (net.js:1495:7)
    at Server.server.listen (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:106030:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:50244:8)
    at __webpack_require__ (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:21:30)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64:18
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:67:10)

**Comment by MartinKrmer** [comment]
I am sorry that's the error. 
I hope you can help me.

**Comment by Asone** [comment]
The port chosen for the service seems to be used  : 
`Error: listen EADDRINUSE :::8545`

Which means that either you have already another instance already running, either you have another service or software using this port. 

you can run `lsof -i :8545 -S` in a terminal to find what service or program is using the port

**Comment by MartinKrmer** [comment]
This was really dumb sorry. I did found that open terminal.

**Comment by Asone** [comment]
no problem, however can you close the issue then ? Thanks ! :D

**Comment by leonprou** [comment]
Sometimes ganache-cli is still running in the background, even when all by terminals are closed.

This issue is also described here: https://github.com/sc-forks/solidity-coverage/issues/109

**Comment by benjamincburns** [comment]
@leonprou can you please raise a new issue describing that problem? Please make sure to include the version of `ganache-cli`, as well as type/version of your OS, and version of nodejs.

**Comment by leonprou** [comment]
@benjamincburns hey, after another investigation I come to conclusion that the problem was (probably) with the script that we were using to start `ganache`. I'll get a look in the script and If I see something weird I'll open an appropriate issue. Thanks for now 👍
