### ISSUE TITLE
`eth_getBlockByHash` request without second param crashes ganache

### ISSUE THREAD

**Issue by XertroV** [ConsenSys-archive/ganache-cli-archive#470]
If you make a bad `eth_getBlockByHash` request (including only the block hash) then ganache crashes. This also occurs with `eth_getBlockByNumber` - not sure about other methods.

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

RPC error instead of crashing

## Current Behavior

Crash

## Possible Solution

The error thrown is `callback is not a function` - though the traceback is useless due to minification.

## Steps to Reproduce (for bugs)

send something like:

```
{ "jsonrpc": "2.0",
"id": 1,
"method": "eth_getBlockByHash",
"params": [ "0x1f715d6d8374232cf76ba73abd7e3ba42ed42f30377aab76c61920b193747ac1" ] }
```

## Context

Discovered when using a badly formed request in `purescript-web3`

## Your Environment

* Version used: Ganache 6.0.3
* Version of Truffle/Remix/Other tools used: purescript-web3 v0.11.0
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): macos

**Comment by benjamincburns** [comment]
Thanks for reporting this @XertroV. Can you please try `npm install -g ganache-cli@beta`? This issue should already be fixed in that version.

**Comment by XertroV** [comment]
@benjamincburns - Confirmed the beta version fixes this. Thanks 👍
