### ISSUE TITLE
When using -db which files created are related to ganache-cli logs and which ones are the actual Blokchain?

### ISSUE THREAD

**Issue by owngr** [ConsenSys-archive/ganache-cli-archive#472]
Hello,

For a project I'm using ganache-cli and truffle to know the actual size of a blockchain after a given scenario. For that I launch this command:
`ganache-cli -l 300000000 -p 7545 -g 1 --db blockchain`

My question is which files do I have to erase in my "blockchain" directory to have only the one related to Ethereum ?

I tried to run my truffle's test with  #geth but couldn't achieve it because of all the accounts that I would have to unlock.

**Comment by mikeseese** [comment]
@Olivierwenger all of the files currently in your `blockchain` folder are related to the ethereum blockchain. You can take a look at [filedown.js](https://github.com/trufflesuite/ganache-core/blob/c35f6a5d45730e7e930d188aeebee092a0aae741/lib/database/filedown.js) for more details
