### ISSUE TITLE
When running with `--account=0xaddress,balance`, the account has zero balance

### ISSUE THREAD

**Issue by aleybovich** [ConsenSys-archive/ganache-cli-archive#475]
Run `ganache-cli --account=<private key>,<balance>`  and check that account's balance. 

Actual behavior: account balance is zero. 

Expected behavior: the account has the specified balance

**Comment by aleybovich** [comment]
UPDATE: If I run without specifying balance (but keeping the trailing comma) the accounts are created with 100 ETH balance. When there is no trailing comma, the app crashes.

**Comment by aleybovich** [comment]
On initial testing of the source code, when you pass an account without comma and balance, the argument is converted form hex to decimal, which invalidates it. That leads Ganache to create random accounts instead of the one specified.

**Comment by aleybovich** [comment]
@benjamincburns how do I sumbit a hotfix for this? It doesn't let me push my branch - I get permissions denied.

**Comment by benjamincburns** [comment]
Hi @aleybovich,

Thanks for submitting this issue. Please refer to the GitHub docs on [submitting a pull request](https://help.github.com/articles/about-pull-requests/).

The gist is that you fork the repo, push your branch to your forked repo, and then submit the PR to the parent repo from your forked repo.

**Comment by mikeseese** [comment]
I'm having issues reproducing this with Ganache CLI v6.1.4. I'm guessing this has been fixed since then.

Please update to the latest version of ganache-cli, and if the issue is still happening, open up a new issue.

Thanks!
