### ISSUE TITLE
Out of gas errors

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache-cli-archive#479]
Given that I run:

`
ganache-cli -p7545 -l 990000000000000
`

What are the causes as to why I would be getting this error:

````
  Gas usage: 6721975
  Block Number: 5
  Block Time: Mon Feb 12 2018 18:36:10 GMT+1100 (AUS Eastern Summer Time)
  Runtime Error: out of gas
`````

My test code is simply just initialising a map of structs, and in the struct I have about 10 uint256's. I don't even initialise or write to the blockchain anything yet, Truffle fails to migrate because ganache runs out of gas.

I tried this with both the GUI and the command line version and I get the same bug.

Is there a reason as to why gas usage of ~7 million stops ganache-cli from working when my limit is over a billion? And is there also a reason as to why we have gas limits for development? Note that this only fails on Ganache cli, my code works fine for Remix

**Comment by Asone** [comment]
From what i know there's an amount of gas that a block can have. i'm not sure that you can define any value you want for limit as it's possible it is hard capped and can just specify lower values.

Any way, if your contract is small but when trying to call or deploy a contract, it's possible that your contract or method contains some errors. Have you tried to deploy it with remix IDE just to check that code is considered as good ?

**Comment by ghost** [comment]
@Asone I figured it out, it was a bug with how Solidity had compiled my code. I had to turn on optmisation, so its not the fault of ganache

**Comment by kyriediculous** [comment]
I deleted my build/contracts/ folder  and everything worked afterwards with default ganache settings.
