### ISSUE TITLE
testrpc crashes at launch with "Error: Cannot find module 'sha3'" on Linux

### ISSUE THREAD

**Issue by JeffreyBPetersen** [ConsenSys-archive/ganache-cli-archive#48]
The only line in the error trace that doesn't reference node internals is:
`at Object.<anonymous> (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/keccakjs/index.js:1:80)`
This is after having only used `npm install -g ethererumjs-testrpc`
I tried gulp as well on the same machine and it's working fine, which looks to isolate the issue to testrpc.

**Comment by JeffreyBPetersen** [comment]
Found the root of the issue, needed Python 2.7

Worth mentioning as a dependency in the main install directions.

**Comment by mluckenbill** [comment]
@JeffreyBPetersen I'm experiencing the same issue on Ubuntu however, I have Python 2.7 installed. Could you provide more details to me about your issue and solution?

**Comment by JeffreyBPetersen** [comment]
@mluckenbill It's hard to remember at this point, but I think I might've needed something like [this](https://wiki.archlinux.org/index.php/python#Dealing_with_version_problem_in_build_scripts) as well. tl;dr: calls to "python" expecting 2.7 instead of 3.x

**Comment by mluckenbill** [comment]
Thank you I actually figured it out. My issue was not fixing nodejs
permissions.

**Comment by grubby8** [comment]
@mluckenbill Can you tell me how to fix nodejs permissions,please!

**Comment by mluckenbill** [comment]
This should solve your problem.

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by grubby8** [comment]
@mluckenbill got it,thanks

**Comment by jmdfm** [comment]
Closing, as seems to be an environment setup and the Windows installation entry in the [Wiki](https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows) mentions installing Python 2.7.
