### ISSUE TITLE
TypeError: web3.eth.accounts.create is not a function

### ISSUE THREAD

**Issue by RajivSah** [ConsenSys-archive/ganache-cli-archive#484]
the javascript file for webpage is

$(document).ready(function(){

if (typeof web3 !== 'undefined'){
  console.log('Web3 found');
    web3 = new Web3(web3.currentProvider);
  } else {
    web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
}

$("#creatAccountSubmit").click(function(){
var count = $("#noOfAccount").val();
for (let index = 0; index < count; index++) {
  var accounts = web3.eth.accounts.create();
  console.log(accounts);

}    
});
});

I am using ganache-cli as local provider i dont know which web3 version it uses but the package.json file in my project folder seems to use 1.0.0

{
"name": "project",
"version": "1.0.0",
"description": "",
"main": "index.js",
"scripts": {
  "test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "ISC",
"dependencies": {
  "web3": "^1.0.0-beta.30"
}
}  

but after running the web page to create an accounti am getting an error

"TypeError: web3.eth.accounts.create is not a function"

How can i resolve this error?

**Comment by benjamincburns** [comment]
Hi @Rxyz58,

I'm afraid the issue that you're reporting has nothing to do with Ganache. You're looking for a function in web3 which apparently is no longer there. Web3 is a separate project.

I'd suggest checking the documentation for web3. https://web3js.readthedocs.io/en/1.0/web3-eth.html
