### ISSUE TITLE
ganache eth_getTransactionCount not returning correct value 

### ISSUE THREAD

**Issue by kc1116** [ConsenSys-archive/ganache-cli-archive#486]
Hi I am using Using the geth project as a library inside my own project. Right now I am trying to get the nonce for an account on my running ganache-cli instance. The response from ganache is "0x02". The client.NonceAt method inside the geth project is trying to unmarshal this into a type of hexutil.Unit64.  

```
// NonceAt returns the account nonce of the given account.
// The block number can be nil, in which case the nonce is taken from the latest known block.
func (ec *Client) NonceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (uint64, error) {
	var result string
	err := ec.c.CallContext(ctx, &result, "eth_getTransactionCount", account, toBlockNumArg(blockNumber))
	log.Println("result", result)
	return uint64(1), err
}
```
Is this the correct implementation inside ganache or would I have to make adjustments to tthi

**Comment by benjamincburns** [comment]
Hi @kc1116 what version of ganache-cli are you running? Can you tell me whether this is a problem in the current beta? `npm install -g ganache-cli@beta`

**Comment by DavidKuennen** [comment]
Having same issue. 

Using Version 6.1.0-beta.

**Comment by kc1116** [comment]
fixed in beta @benjamincburns nice work !
