### ISSUE TITLE
How to keep accounts

### ISSUE THREAD

**Issue by DavidKuennen** [ConsenSys-archive/ganache-cli-archive#487]
Unfortunately, unlike the ganache application, ganache-cli creates completely new accounts on each restart. This is very annoying, because I always have to reimport a new account into my metamask to test my application. 

Is there a way to keep the accounts in ganache-cli as well?

* Version used: 6.1.0-beta
* Version of Truffle/Remix/Other tools used: 4.0.6
* NodeJS Version: 8.2.1
* Operating System and version (include distro if Linux): Windows 10

**Comment by DavidKuennen** [comment]
Ok, figured it out.

**Comment by benjamincburns** [comment]
In the future your best bet is to ask questions like these in the [Truffle gitter](https://gitter.im/ConsenSys/truffle).

**Comment by chrisciszak** [comment]
@DavidKuennen obviously there is no point of actually answering your own question once you found the answer.

**Comment by mimoo** [comment]
run `ganache-cli --deterministic` to your options, this is insecure btw.
