### ISSUE TITLE
getTransactionReceipt not returning 'from' address

### ISSUE THREAD

**Issue by claykohut** [ConsenSys-archive/ganache-cli-archive#488]
Using web3.eth.getTransactionReceipt is not returning 'from' address when using a gananche as a provider.

## Expected Behavior

web3.eth.getTransactionReceipt() should return both the 'from' / 'to' fields as part of the receipt object

## Current Behavior

Currently neither from/to are returned in the receipt object as pictured below:

![screen shot 2018-02-25 at 2 02 49 am](https://user-images.githubusercontent.com/3993332/36639031-f23f5248-19d0-11e8-9ffd-e459b8e2875c.png)

## Steps to Reproduce (for bugs)

1. Make transaction
2. call web3.eth.getTransactionReceipt on the transactionHash
3. notice that from/to are not in the receipt object

**Comment by bbrh** [comment]
Have the same issue. Is it expected behaviour?

**Comment by fastchain** [comment]
Same problem here

**Comment by eshaben** [comment]
Thank you for submitting this issue. It has been fixed in PR#212.
