### ISSUE TITLE
Array reset leads to out of gas error using ganache-cli

### ISSUE THREAD

**Issue by crzndx** [ConsenSys-archive/ganache-cli-archive#491]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5a9c271ee4d1c63604bee393

## Expected Behavior

Given the code 

```
pragma solidity ^0.4.20;
contract Test {

    uint[4] public arr; // [0,0,0,0]
    event TestLog(string logmessage);

    function Test() public {
        arr[0] = 1; // [1,0,0,0]
    }

    function checkArray() public {
        if(arr[0] == 1) { // arr == [1,?,?,?]
            arr[1] = 1;
            arr[0] = 0; // switch values [0,1,0,0]
        }
        TestLog("some log");
    }
}
```

it should be able to execute the checkArray() function and set `arr[0]` to 0 with `arr[0] = 0; `.

## Current Behavior
When running ganache-cli in current version v6.0.3 (ganache-core: 2.0.2) executing the checkArray() function, it throws an `out of gas error` happens as the line setting the array to zero makes `arr[0] = 0;` problems.

## Possible Solution

Resetting arrays via index to 0 should not result in errors.

## Steps to Reproduce (for bugs)

Use the code provided above, and check the intended functionality on the deployed Rinkeby contract: https://rinkeby.etherscan.io/address/0x78aC7667BdeDC3b1CdF43611AdF7a88e05b600F5#code

When calling the checkArray function, it should be able to reset the value of arr[0] to 0.

This topic on Stackexchange is related: https://ethereum.stackexchange.com/questions/41651/contract-always-out-of-gas-in-remix/41675#41675

## Context
This is BASIC functionality that should work flawlessly.

## Your Environment
* Version used: ganache-cli v6.0.3 (ganache-core: 2.0.2), as well as testrpc (via npm install -g ethereumjs-testrpc)
* Version of Truffle/Remix/Other tools used: Remix online
* NodeJS Version: [x] 6.x, [] 7.x (unsupported), [ ] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): Mac OS X
* Link to your project or repro gist: 
* Commit hash to use with above link for reproduction: https://rinkeby.etherscan.io/address/0x78aC7667BdeDC3b1CdF43611AdF7a88e05b600F5#code
* I intend to submit a pull request to fix this issue: [ ]

**Comment by crzndx** [comment]
This issue #458 seems to be related. And I guess, the correct repository the open this issue in would have been ganache-core.

**Comment by davidmurdoch** [comment]
Thanks for reporting this, @crzndx! This should now be fixed by https://github.com/trufflesuite/ganache-core/commit/81e8f59d74bcb38773498c34c78fb7d35a22af7f in ganache-cli 6.1.7 and ganache-core 2.2.0. Please update and let us know if it's still a problem.
