### ISSUE TITLE
failed transactions: differing behaviour from go-ethereum (which is correct?)

### ISSUE THREAD

**Issue by chetmurthy** [ConsenSys-archive/ganache-cli-archive#495]
I have a trivial smart contract with an entrypoint that fails ("require(false)").  When run against ganache-cli, I get a VM exception back.  When run against go-ethereum, I get a tran-hash, and the associated receipt is found, but clearly the tran did not execute.

FURTHERMORE (though), it seems clear that several well-respected projects (openzeppelin, gnosis/MultiSigWallet) both write their tests expecting the ganache-cli behaviour, NOT the go-ethereum behaviour.

I'm not sure what is the right behaviour, but clearly this makes it difficult-to-impossible to write tests that work against both ganache-cli and go-ethereum.

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5ab46391c574b1aa3e21d342

## Expected Behavior
If go-ethereum is the correct behaviour, then ganache-cli should NOT return a VM exception when sent a transaction that fails (e.g. "require(false)").

## Current Behavior
Currently, ganache-cli returns a VM exception, and several projects (openzeppelin, gnosis/MultiSigWallet) depend on that behaviour in their testsuites.

## Steps to Reproduce (for bugs)

1.  Here's a contract Bar.sol.
```
pragma solidity ^0.4.13;

contract Bar
{
  uint n ;
  event Argle(uint arg);
  function argle_int(uint arg) internal {
    n = arg ;
  }

  function set(bool pass, uint arg) public {
    Argle(arg) ;
    require(pass) ;
    argle_int(arg);
  }

  function get() public view returns (uint) {
    return n ;
  }
}
```
2. with truffle (or even with the geth console -- either produces the same results) running against ganacle-cli, compile and deploy this contract.
3. run the following rpcs: get(), then set(true, 42), then get(), observe that the second get returns 42, as it should.
4. run set(false, 84), get(), observe that the set() call fails with a Javascript exception, and of course, the get() returns 42 (no change).
5. redo steps 2-4, but running against go-ethereum.  Now, the second set() will return a tran-receipt, but the state will not be changed.

## Context

I want to write test-suites that exercise both the "successful" and "failing" behaviours of my smart contract, and do so in complex chains of transactions.  I also want to run against both ganache-cli (b/c fast) and geth (b/c that's the intended production environment).  This is pretty difficult to do, when the two environments differ in behaviour.

## Your Environment
* Version used:Ganache CLI v6.0.3 (ganache-core: 2.0.2)
* Version of Truffle/Remix/Other tools used: Truffle v4.1.0 (core: 4.1.0)
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): Ubuntu 16.04.4 LTS
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by mikeseese** [comment]
This is related to https://github.com/trufflesuite/ganache-core/issues/59

**Comment by davidmurdoch** [comment]
Fixed by https://github.com/trufflesuite/ganache-core/commit/9a4cb880e5ed5a5bdf7fa45f8fd7d18349a58fbe
