### ISSUE TITLE
Remix + ganache-cli: VM exception while processing transaction: out of gas

### ISSUE THREAD

**Issue by mojuss** [ConsenSys-archive/ganache-cli-archive#497]
## Expected Behavior

**I'm testing a sample contract as below. The contract is called from Remix, using Environment - Web3 Provider ganache CLI v6.1.0, core 2.1.0**

```
_pragma solidity ^0.4.21;

contract Donation {
    address owner;
    event fundMoved(address _to, uint _amount);
    modifier onlyowner { if (msg.sender == owner) _; }
    address[] _giver;
    uint[] _values;

    function Donation() public {
        owner = msg.sender;
    }

    function donate() public payable {
        addGiver(msg.value);
    }

    function moveFund(address _to, uint _amount) public onlyowner {
        uint _balance = address(this).balance;
        bool _tosendbal = _to.send(_balance);
        if (_amount <= _balance) {
            if (_tosendbal) {
                emit fundMoved(_to, _amount);
            } else {
                revert();
            }
        } else {
            revert();
        }
    }

    function addGiver(uint _amount) internal {
        _giver.push(msg.sender);
        _values.push(_amount);
    }
}
```

**I'm invoking the function moveFund (before that I call donate, to transfer some ether to the contract. Ether should be sent from the contract to the selected address.**

## Current Behavior

Remix is saying that: _transact to Donation.moveFund errored: VM Exception while processing transaction: out of gas_

In the genache-cli output I see:
Transaction: 0x0e4e7564f5d530edb0855ff4f91fa69fccb1ff67104a1d293a99d82207d14fb0
  Contract created: 0x62a9cb52dceb1d48564ed91011e20b2f54041ed0
  Gas usage: 289303
  Block Number: 1
  Block Time: Sun Mar 25 2018 09:46:51 GMT+0200 (W. Europe Summer Time)

then I see that the appropriate amount of ether (17) is sent to the contract when the donate function is called (I do not see any error connected with this function):
eth_getTransactionByHash
   > {
   >   "jsonrpc": "2.0",
   >   "id": 30758,
   >   "method": "eth_getTransactionByHash",
   >   "params": [
   >     "0x2d6bdca320e6c3f8dfc0ee33df0143020ca1b88f10ce62e2719bc96623dad2b3"
   >   ]
   > }
 <   {
 <     "id": 30758,
 <     "jsonrpc": "2.0",
 <     "result": {
 <       "hash": "0x2d6bdca320e6c3f8dfc0ee33df0143020ca1b88f10ce62e2719bc96623dad2b3",
 <       "nonce": "0x01",
 <       "blockHash": "0x5c5eba2b4aedfdecbbd275e18cccc2b5636e1736750638878c2bc9a41ee65a0c",
 <       "blockNumber": "0x02",
 <       "transactionIndex": "0x00",
 <       "from": "0xb887966fcdb1de8dc2363c691712b3613bddda50",
 <       "to": "0x62a9cb52dceb1d48564ed91011e20b2f54041ed0",
 <       "value": "0xebec21ee1da40000",
 <       "gas": "0x0192dc",
 <       "gasPrice": "0x01",
 <       "input": "0xed88c68e"
 <     }
 <   }

And finally calling moveFund I'm receiving that:
eth_estimateGas
   > {
   >   "jsonrpc": "2.0",
   >   "id": 30783,
   >   "method": "eth_estimateGas",
   >   "params": [
   >     {
   >       "from": "0xb887966fcdb1de8dc2363c691712b3613bddda50",
   >       "to": "0x62a9cb52dceb1d48564ed91011e20b2f54041ed0",
   >       "data": "0xb01217f40000000000000000000000004f205c3169e0ce4ee69192289584f4f2863a75db0000000000000000000000000000000000000000000000000000000000000007",
   >       "value": "0x0"
   >     }
   >   ]
   > }
 <   {
 <     "id": 30782,
 <     "jsonrpc": "2.0",
 <     "result": [
 <       "0xb887966fcdb1de8dc2363c691712b3613bddda50",
 <       "0x4f205c3169e0ce4ee69192289584f4f2863a75db",
 <       "0x3533b05e7e2c5800fed9663b146e3f4fb3eb014b",
 <       "0x702b34c23da064380e93799e66393697913484ff",
 <       "0x082124945a490302edbbab24cf8361e3b3feb04b",
 <       "0xe23df3a01038603db4fb845ef67a7732a29d34c8",
 <       "0xc958e889f58ad0ef186771f1e70aabc660a69471",
 <       "0xa8875a4a14fd1b5873ffa3dc0adfba84f1c9ca32",
 <       "0x2a09ce1a3a84faf89c6e7fb54a26a8add155a49c",
 <       "0x1bb26d4ee55bc26000582a11d340b1ab54651fc6"
 <     ]
 <   }
 <   {
 <     "id": 30783,
 <     "jsonrpc": "2.0",
 <     "result": "0x7fa2"
 <   }
net_version
   > {
   >   "jsonrpc": "2.0",
   >   "id": 30784,
   >   "method": "net_version",
   >   "params": []
   > }
 <   {
 <     "id": 30784,
 <     "jsonrpc": "2.0",
 <     "result": "1521963994173"
 <   }
eth_sendTransaction
   > {
   >   "jsonrpc": "2.0",
   >   "id": 30785,
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "from": "0xb887966fcdb1de8dc2363c691712b3613bddda50",
   >       "to": "0x62a9cb52dceb1d48564ed91011e20b2f54041ed0",
   >       "data": "0xb01217f40000000000000000000000004f205c3169e0ce4ee69192289584f4f2863a75db0000000000000000000000000000000000000000000000000000000000000007",
   >       "value": "0x0",
   >       "gas": "0x7fa2"
   >     }
   >   ]
   > }

  Transaction: 0xaadd90e776900217ed33a6fa0ca12f3d6b4ba589d6664d3fc9625470d74788ca
  Gas usage: 32674
  Block Number: 3
  Block Time: Sun Mar 25 2018 09:47:02 GMT+0200 (W. Europe Summer Time)
  Runtime Error: out of gas

 <   {
 <     "id": 30785,
 <     "jsonrpc": "2.0",
 <     "result": "0xaadd90e776900217ed33a6fa0ca12f3d6b4ba589d6664d3fc9625470d74788ca",
 <     "error": {
 <       "message": "VM Exception while processing transaction: out of gas",
 <       "code": -32000,
 <       "data": {
 <         "0xaadd90e776900217ed33a6fa0ca12f3d6b4ba589d6664d3fc9625470d74788ca": {
 <           "error": "out of gas",
 <           "program_counter": 320
 <         },

-->

## Steps to Reproduce (for bugs)

1. Connect to the genache-cli from remix
2. Run the contract, first compiling it with solidity version 0.4.21 (the contract is stated in the Expected Behaviour section.

## Your Environment
* Version used: **ganache CLI v6.1.0, core 2.1.0**
* Version of Truffle/Remix/Other tools used: **https://ethereum.github.io/browser-solidity**
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x: **v8.9.4**
* Operating System and version (include distro if Linux): **Windows 10**
* Link to your project or repro gist: none
* Commit hash to use with above link for reproduction: **8000000 (setup when ganache is starting)**
* I intend to submit a pull request to fix this issue: [x ] 

I would appreciate any help

**Comment by j10sanders** [comment]
I've run into this same issue.  It took me a long time to realize it was a ganache issue, but realized when I used the JVM in Remix.  https://ethereum.stackexchange.com/questions/46494/cant-transfer-value-from-mapping-inside-mapping

**Comment by andompesta** [comment]
Same as her. 

Moreover, I'm also experiencing a similar problem when I'm trying to call a payable function between 2 contracts. So, it's like that the gas estimated do not take in consideration the gas used by the called function

**Comment by mikeseese** [comment]
Hello everyone! It seems that this is related to ganache gas estimation to be missing some components. We're tracking this issue in https://github.com/trufflesuite/ganache-core/issues/26. The solution to https://github.com/trufflesuite/ganache-core/issues/26 will try to add the high water mark estimation, and then we'll follow up in another issue with a more accurate estimation method.

I'm going to close this issue in favor of https://github.com/trufflesuite/ganache-core/issues/26, but we'll use your details to help us if we need it! Thanks!!

**Comment by superduck35** [comment]
Has this been resolved? I spent hours debugging a really silly issue which turned out to be something to do with ganache (think this is it). In my case I was interacting with a proxy contract and it was bugging out on different storage setting calls, was hard to pin down. Note I was using remix, so changed to Javascript VM and it worked :+1:

**Comment by mikeseese** [comment]
@alsco77 Bummer you're still having issues! Per my last comment, we were tracking this in https://github.com/trufflesuite/ganache-core/issues/26, not this issue (hence why this was closed 6 days ago).

That issue was closed 4 days ago, and is in `ganache-core` `v2.2.0+` (though there was a bug in `v2.2.0` which caused us to release `v2.2.1`). The associated `ganache-cli` releases were `v6.1.7` and `v6.1.8`. What version were you running on?

While we believe this should be solved in https://github.com/trufflesuite/ganache-core/issues/26, we have an open issue at https://github.com/trufflesuite/ganache-core/issues/147 which implements even more accurate gas estimation.

We definitely will need any more detail from your setup/contracts/etc. before we really can try to address your specific issue however.

Thanks!

**Comment by mikeseese** [comment]
@alsco77 I chatted with @davidmurdoch a little, and it appears the "gas estimation" issue isn't completely solved, which will be addressed in https://github.com/trufflesuite/ganache-core/issues/147

**Comment by superduck35** [comment]
@seesemichaelj thanks for your help! I ran on Linux based `Ganache CLI v6.1.8 (ganache-core: 2.2.1)`. I also tried using the GUI but same problem. You can see the contracts [here](https://github.com/alsco77/Decentra-Mart) and the particular command that was causing the problem was [DMartStore.sol 'addProduct'](https://github.com/alsco77/Decentra-Mart/blob/master/contracts/DMartStore.sol#L112).

When executing the method call via an interface on Remix, the method would fail for various reasons and it was hard to pin down, one thing that was causing it to fail was `uint id = numberOfProducts++;`, possibly due to the incrementing storage var?

As I said, I fixed this by deploying manually via Remix so no major issues for me
