### ISSUE TITLE
Stack underflow while sending a transaction

### ISSUE THREAD

**Issue by niran** [ConsenSys-archive/ganache-cli-archive#5]
I got the following error while sending a transaction:

`Error: VM Exception while executing transaction: stack underflow`

The same code succeeded with the Python testrpc. I don't have a good way for anyone to reproduce this issue yet.

**Comment by kumavis** [comment]
but we really wanna reproduce it c'mon

**Comment by niran** [comment]
It turns out that the transaction fails in the Python VM with an "out of range" error. It might be a contract bug. I'll follow up when I know more.

**Comment by tcoulter** [comment]
Yep. VM exception means "runtime error"

**Comment by kumavis** [comment]
im going to close this - reopen if its a testrpc error :+1:
