### ISSUE TITLE
Where to find/retrive generated account's password?

### ISSUE THREAD

**Issue by evaon1017** [ConsenSys-archive/ganache-cli-archive#501]
for visual studio unit test purpose, can I get password of auto-genereated account? I know I can use --unlock parameter to unlock what I need but... I would test multiple account of different privatekey to doing transaction call. maybe not a good idea if I unlock all using accounts.
please guild me how to find or retrive password via privatekey and account parsed from --acctKeys output.

**Comment by mikeseese** [comment]
There currently isn't any password setup for the accounts created. You'll have to use the unlock account capability to accomplish this.
