### ISSUE TITLE
After few seconds, accounts are flushed

### ISSUE THREAD

**Issue by Thebarda** [ConsenSys-archive/ganache-cli-archive#502]
Hi everyone.

When after created my blockchain's test, after a few seconds, my accounts balance are flushed.

## Current behavior

Balance's accounts is 0.0000001 ether

## Expected behavior

Balance's accounts should be 100 ether

## Step to reproduce

I just run `ganache-cli` on my server then I wait a few seconds, sometime a minute, then all balance's account are flushed.
I'm on a Debian 9 amd64

I'm using ganache-cli for 5 months without any problems to develop a crowdfunding app for a school project.

**Comment by surabhil** [comment]
I am getting this error too. Any updates on this

**Comment by m4rg4sh** [comment]
same issue here...

**Comment by blackwatertepes** [comment]
Same here.

This issue seems to be happening in Geth, as well: https://github.com/ethereum/go-ethereum/issues/16467

@m4rg4sh @Thebarda  What's the account address your eth is being drained to?

**Comment by Thebarda** [comment]
@blackwatertepes All of them in my case

**Comment by m4rg4sh** [comment]
The "bug" seems to match, the funds of all the accounts get moved to 0x6ef57be1168628a2bd6c5788322a41265084408a from what I can see.
So I assume there's someone scanning the web looking for open test blockchains to troll people?

**Comment by Thebarda** [comment]
I'm trying to catch his IP address to ban him.
I'm not using the default port.
Thanks @m4rg4sh

**Comment by blackwatertepes** [comment]
I'm experiencing this issue on a private Ethereum network, with no world access. So, this issue does not only exist on the public test nets, and is most likely caused from something related to the Ethereum codebase.

**Comment by Tudmotu** [comment]
Did anyone find a workaround for this issue, other than blocking port 8545?

**Comment by Thebarda** [comment]
It solve the problem for me.
Of course, you can catch his IP address and ban him.
So, can I close this issue ?

**Comment by Tudmotu** [comment]
How do you perform transactions via MetaMask on your blockchain if you block 8545?

**Comment by Thebarda** [comment]
I never used MetaMask.
I guess you should ask them on their Github

**Comment by Tudmotu** [comment]
How do you perform transactions on your blockchain?

**Comment by Thebarda** [comment]
I'm using web3.js because I develop a web application

**Comment by Tudmotu** [comment]
I apologize, but I'm trying to solve this for me as well and I still don't understand.. :confused: 
Are you using web3 in the browser or only on server-side? What provider are you giving web3? When you do:
```javascript
const web3 = new Web3(....);
```

**Comment by Thebarda** [comment]
So, in my case, I use web3 on server-side.
In my other application, I use web3 on client-side.
To declare a provider, you can use this :
```javascript
const web3 = new Web3(new Web3.providers.HttpProvider("http://myprovider.com:providerPort"));
```

Also you can use websockets instead of HTTP : 
```javascript
const web3 = new Web3(new Web3.providers.WebsocketProvider("ws://myprovider.com:providerPort"));
```

I hope that will help you ;)

**Comment by Thebarda** [comment]
So, I will close this issue
@Tudmotu If you have any question about web".js, please send me an email ;)
