### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing when installing ganache-cli

### ISSUE THREAD

**Issue by kaushiksk** [ConsenSys-archive/ganache-cli-archive#505]
I am unable to install ganache-clie and get the following error

```npm ERR! Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"e'```

## Environment

* NodeJS Version:  9.x
* npm version: 5.6.0
* Operating System and version: Ubuntu 16.04 LTS

**Comment by plummm** [comment]
same problem

**Comment by cupcakearmy** [comment]
for me running `rm -rf node_modules package-lock.json` and `npm cache clean --force` solved it

**Comment by mikeseese** [comment]
Closing as I'm sure @CupCakeArmy's suggestion is the fix for this :)

Thanks!

**Comment by juniorbuba** [comment]
same problem too

npm ERR! Unexpected end of JSON input while parsing near '...sts"},"dist":{"shasum'

**Comment by hangge666** [comment]
> for me running `rm -rf node_modules package-lock.json` and `npm cache clean --force` solved it

I'm solved,Thank your answer.

**Comment by amankumar10021998** [comment]
npm cache clean --force  ,   I run this command to fix my problem

**Comment by chrisbasalo08** [comment]
> for me running `rm -rf node_modules package-lock.json` and `npm cache clean --force` solved it

Thank you! It solved my issue.

**Comment by shah-cloud** [comment]
> for me running `rm -rf node_modules package-lock.json` and `npm cache clean --force` solved it

Thank you! It solved my issue.
