### ISSUE TITLE
sendTransaction to account address with data

### ISSUE THREAD

**Issue by zatsepinvl** [ConsenSys-archive/ganache-cli-archive#507]
I try to send transaction with data to external account (user address) using MetaMask and ganache-cli (ganache-core v2.1.0) :
`
web3.eth.sendTransaction({"from":"0x...","to":"0x..","value":1,"data":"0x..."}, (err,result) => {});
`
and get the error:
![image](https://user-images.githubusercontent.com/11683340/38604973-a5fc3266-3d7a-11e8-96c5-b46b368b0994.png)

But if I use previous version testrpc (ganache-core v2.0.2) transaction is passed successfully - the same with Ropsten net. 

Was it prohibited in the new version intentionally? And why?

**Comment by newship** [comment]
I have the same problem.. （ganache-core: 2.1.5）

**Comment by mikeseese** [comment]
We're also tracking this in https://github.com/trufflesuite/ganache-core/issues/117
