### ISSUE TITLE
400 Bad Request When Navigating to RPC URL in Browser

### ISSUE THREAD

**Issue by ehanoc** [ConsenSys-archive/ganache-cli-archive#514]
Ubuntu 16.04
Node v9.3

Steps : 

$ npm install -g ganache-cli
$ ganache-cli 

Trying to open on localhost:8545 gives 400 Bad Request

**Comment by GrzesiekP** [comment]
Faced the same issue

**Comment by soma11soma11** [comment]
same here

**Comment by linhnh-ibl** [comment]
Same issue

**Comment by shobhitJava** [comment]
same issue

**Comment by mikeseese** [comment]
Hi thanks for reporting this! Can you please provide some logs to the output of the `ganache-cli` command? Have you tried another port using the `-p` flag?

**Comment by shobhitJava** [comment]
It is working fine now. Thanks

**Comment by mikeseese** [comment]
So I think I understand what everyone is running into. It's sounding like you're running `ganache-cli` and then opening an internet browser and going to `localhost:8545`.

It sounds like you're treating it similarly to how you access Parity's UI. If you are interested in using a UI for Ganache, you can download our UI at https://github.com/trufflesuite/ganache/releases.

I'm keeping this issue open as we may be able to put a different screen when the user tries to navigate to the RPC URL via the browser.

**Comment by shobhitJava** [comment]
Yeah i got that. It will need web3.js to connect to it. Anyway thanks

**Comment by Ncortesa** [comment]
Hello (I'm kind of a rookie)
I was trying to do the quickstart of a truffle tutorial and when i deploy the testrpc on a CMD i get the normal testrpc config saying that is listening on localhost:8545

But when i tried to do the truffle migration i got blocked with an error saying ("Error: No network specified. Cannot determine current network.")

So i tried to run a curl command with localhost:8545 and i receive a "400 bad request" error.
shouldn't the curl command work?

Or is some testrpc default to refuse the dirct curl ping?

**Comment by mikeseese** [comment]
@Ncortesa What's the curl command you're using?

For example, if I run `ganache-cli` (installed by doing `npm install -g ganache-cli`), and then in separate terminal run the curl command:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' 127.0.0.1:8545
```

I get the response `{"id":67,"jsonrpc":"2.0","result":"EthereumJS TestRPC/v2.1.5/ethereum-js"}` (which we should update haha)

**Comment by Ncortesa** [comment]
I was trying to do a simple curl into the Default door and the local host

`curl localhost:8545 `

But by applying the correct definitions in the truffle.js file i got a good response in the console.

Mayby is related
