### ISSUE TITLE
Add support for eth_signTypedData

### ISSUE THREAD

**Issue by rhlsthrm** [ConsenSys-archive/ganache-cli-archive#515]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5ae26c212b9dfdbc3ad31939

## Expected Behavior
Support for eth_signTypedData from this [EIP](https://github.com/ethereum/EIPs/pull/712).

## Current Behavior
Error message: `Error: Method eth_signTypedData not supported.`

**Comment by tal-beja** [comment]
+1

**Comment by vans163** [comment]
Yea

**Comment by fabioberger** [comment]
Any update on this?

**Comment by benjamincburns** [comment]
Copying my comment here from the PR:

> I'm a little hesitant about this change, primarily because EIP-712 is still listed as draft status, and I can't find where either geth or Parity support it yet. I see that MetaMask has added support, however - so maybe that's good enough since most web apps will be interacting with the client via them or some other wallet middleware...

**Comment by benjamincburns** [comment]
OK, I'm walking back that comment a bit - I _really_ like the interaction this helps to support and I'd rather help move things forward by adding preliminary support for the RPC call.

**Comment by benjamincburns** [comment]
PR merged and will be released shortly - huge thanks to @rmeissner for saving us the hassle of implementing it ourselves! :heart:
