### ISSUE TITLE
--blockTime not working

### ISSUE THREAD

**Issue by e18r** [ConsenSys-archive/ganache-cli-archive#517]
## Expected Behavior

`ganache-cli --blockTime 15` should wait 15 seconds before mining each block.

## Current Behavior

`ganache-cli --blockTime 15` behaves exactly like `ganache-cli`

## Steps to Reproduce

1. clone my repository at https://github.com/emi-silva/lease.git and reset to commit 287b481de1df7b0ca5e8033990d434514b571754

2. run ganache-cli on port 8875 without the --blockTime option
3. truffle test test/delay.test.js --network dev
4. take a look at the output log. The state variable is updated immediately.

5. run ganache-cli on port 8875 with the --blockTime option set to 15 (or to 15000000 for that matter)
6. truffle test test/delay.test.js --network dev
7. The results are the same.

8. run ganache UI on port 8875, uncheck the automine option, set the block time to 15
9. truffle test test/delay.test.js --network dev
10. take a look at the output log. The state variable is not updated immediately.

11. run Rinkeby: geth --networkid 4 --rpcport 8555 --rpc
12. truffle test test/delay.test.js --network rinkeby
13. The state variable is again not updated immediately.

## Context

This issue is not letting me reproduce an actual production scenario for my unit tests, which is a potential source of bugs in my contract. If it is not solved, I cannot continue using ganache-cli.

## Your Environment

* Version used: 6.1.0
* Version of Truffle/Remix/Other tools used: Truffle 4.1.8, Ganache UI 1.1.0, Geth 1.8.4-stable-2423ae01
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [x] 9.x
* Operating System and version (include distro if Linux): Arch Linux (latest)
* Link to your project or repro gist: https://github.com/emi-silva/lease.git
* Commit hash to use with above link for reproduction: 287b481de1df7b0ca5e8033990d434514b571754
* I intend to submit a pull request to fix this issue: [ ]

**Comment by dostu** [comment]
This is already fixed in ganache-core develop branch (https://github.com/trufflesuite/ganache-core/pull/101), but they need to make a new release.

**Comment by linhnh-ibl** [comment]
Same issue, waiting for new release!

**Comment by mikeseese** [comment]
Hey everyone! A release was snapped a couple weeks ago, you can now use [v6.1.3](https://www.npmjs.com/package/ganache-cli/v/6.1.3)

I'm going to go ahead and close this, but please open it up again if the issue persists (or open a new issue if it's slightly different).

Thanks!

**Comment by deoidh** [comment]
Didn't work for me, resorted to ganache-ui which works flawlessly.

Tried `-b` `--blockTime` `--blocktime`

**Comment by mikeseese** [comment]
@samgos what version of ganache-cli are your using (either `ganache-cli --version` or `npm list -g ganache-cli`)?

This works for me on `6.1.6`

**Comment by deoidh** [comment]
@seesemichaelj  

### OS: MAC OS X Sierra v10.13.12

`/usr/local/lib
└── ganache-cli@6.1.6 `

&

`Ganache CLI v6.1.6 (ganache-core: 2.1.5)
`

Works fine on UI  but as you can imagine it is memory resourceful with the client side interface;

**Comment by deoidh** [comment]
Forgive me it seem's my observations were wrong, I was actually on the wrong port to truffle 😞 
Using; `ganache-cli --blockTime 5 --verbose true -p 9545`
This helped to log the `evn_mine` method output to the console and made me aware it was actually functional, I've a suggestion to add the mine method to the console automatically.

Forgive my silliness and have a nice day 👍
