### ISSUE TITLE
How to configure Ganache CLI for Rinkeby?

### ISSUE THREAD

**Issue by harikrishnanp** [ConsenSys-archive/ganache-cli-archive#520]
How to configure Ganache CLI for Rinkeby?

I have tried this `ganache-cli -i 4` where 4 is the network-id of Rinkeby.

**Comment by Uxio0** [comment]
I don't understand your question, Ganache-Cli creates its own private test network

**Comment by alejoamiras** [comment]
@harikrishnanp ganache-cli it's not the implementation of a light-node / node. You can't configure it to connect to Rinkeby. 
You must setup a node with geth / parity / others.

**Comment by mikeseese** [comment]
Thanks @alejoamiras and @Uxio0 for clearing this up!

Like they said, `ganache-cli` currently only creates a private blockchain. You cannot currently use it like a node/client.
