### ISSUE TITLE
Revert not returning error message

### ISSUE THREAD

**Issue by rmeissner** [ConsenSys-archive/ganache-cli-archive#521]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5afc9aafa2d9513633465dc4

## Expected Behavior
When calling a function that reverts with an error message (`revert("Some message")`) the message should be returned as data (as described here: http://solidity.readthedocs.io/en/v0.4.24/control-structures.html#error-handling-assert-require-revert-and-exceptions)
```
"result": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045465737400000000000000000000000000000000000000000000000000000000"
```
## Current Behavior
Currently ganache only returns the error object instead of a response
```
"error": {
            "message": "VM Exception while processing transaction: revert",
            "code": -32000,
            "data": {
                "stack": "<details>"
           }
}
```

## Steps to Reproduce (for bugs)

1.) Deploy the following contract:

```
contract Test {
    
    function test()
        public
    {
        revert("Test");
    }
}
```

2.) Call `test()` (`"data": "0xf8a8fd6d"`)

3.) Response should not contain an error, but the encoded error message as a result. E.g.:
```
{
        "jsonrpc": "2.0",
        "id": 45,
        "result": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000045465737400000000000000000000000000000000000000000000000000000000"
}
```

## Context
We want to use the error message of revert to return a value from a function that should never be called in a transaction. Using the revert message ensures that and still allows us to return the requested data.

## Your Environment
* Version used: 6.1.0
* Version of Truffle/Remix/Other tools used:
- Remix with 0.4.24+commit.e67f0147.Emscripten.clang
- Truffle v4.1.8 (core: 4.1.8)
- Solidity v0.4.24 (solc-js) 
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): Mac OS High Sierra

**Comment by rmeissner** [comment]
This might be a ganache-core issue

**Comment by benjamincburns** [comment]
@rmeissner what happens when you run with `--noVMErrorOnRPCResponse` (see README and recent release notes for info on this flag)

**Comment by rmeissner** [comment]
@benjamincburns I was using the flag, but this only changed the behaviour when performing a transaction. 

I am connected via remix to my ganache-cli. If I don't use `--noVMErrorOnRPCResponse` I get a error when performing a transaction, if I do use it it gives me a transactionhash. 

When using `eth_call` it always errors.

**Comment by rmeissner** [comment]
I will close this issue as it is something that needs to be adjusted in ganache-core
