### ISSUE TITLE
Ganache does not seem to be to handle web3's sendSignedTransaction.

### ISSUE THREAD

**Issue by jasperdg** [ConsenSys-archive/ganache-cli-archive#523]
When I try to use the sendSignedTransaction function according to the web3 documentation: 
https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5afeb76ee0b50c2d05d177a3

## Expected Behavior

If I call:        
`this.web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'))
`
I expect it to send the transaction.
## Current Behavior
Instead I get the following internal json-rpc error: 
`errors.js:29 Uncaught (in promise) Error: Returned error: {"id":4,"jsonrpc":"2.0","error":{"code":-32603}}`

## Possible Solution

I think sendSignedTransaction might not be supported, so adding support for it would be a solution

## Steps to Reproduce (for bugs)
https://ethereum.stackexchange.com/questions/48807/jsonrpc-error-on-sendsignedtransaction?noredirect=1#comment57826_48807

## Your Environment
* Version used: 1.1.0
* Version of Truffle/Remix/Other tools used: Truffle 6.0.0
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): OSX High Sierra

**Comment by ajhodges** [comment]
Hey, I think this issue might be related: https://github.com/ethereumjs/ethereumjs-tx/issues/113

I was seeing the same behavior with ganache-cli due to this bug. I've submitted a PR to ethereumjs-tx. If that gets merged then the package will have to be updated in ganache-core.

**Comment by benjamincburns** [comment]
@jasperdg Thanks for reporting! Please update to the latest Ganache. @ajhodges is correct that ethereumjs/ethereumjs-tx#113 is the culprit, but we worked around this in latest by rolling back to a prior version which didn't exhibit this issue.

Also please check your version numbers. Truffle's latest major version is 4.x.x.
