### ISSUE TITLE
mining disabled

### ISSUE THREAD

**Issue by JMLX42** [ConsenSys-archive/ganache-cli-archive#53]
Hi,

I did not find any way to enable mining and mining is disabled by default:

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_hashrate","params":[],"id":71}'  http://127.0.0.1:8545
{"id":71,"jsonrpc":"2.0","result":"0x0"}
```

How can one enable mining ?

Regards,

**Comment by tcoulter** [comment]
Mining at regular intervals isn't a feature that's been added yet. The
TestRPC will currently only mine a block if a transaction has been
submitted.

This is a good feature to have though and wouldn't be hard to implement.

**Comment by JMLX42** [comment]
OK.

My code is waiting for eth_mining to be true before sending the transaction.
That's an unexpected behavior but I could work around it and make a special case for testrpc.

If eth_mining will start automatically when required, wouldn't it be more accurante to always return true for eth_mining ?

**Comment by tcoulter** [comment]
Good point. Feel free to submit a PR setting it to true. Or I'm happy to
change it tomorrow.

**Comment by JMLX42** [comment]
> Or I'm happy to change it tomorrow.

Thanks :+1: 

Still, I'm sending a contract mining transaction and I don't see it in the testrpc logs.
All I see are calls to `eth_mining` and `net_listening`.

Here is my code:

``` javascript
var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider("http://127.0.0.1:8545"));

var hash = '';
var compiled = getCompiledVoteContract(web3);
var code = compiled.Vote.code;
var abi = compiled.Vote.info.abiDefinition;

console.log({log:'start mining contract'});

web3.eth.contract(abi).new(
    3, // num proposals
    {
        from: web3.eth.accounts[0],
        data: code,
        gas: 999999
    },
    function(error, contract)
    {
        if (error)
            return callback(error, null, null);

        if (!contract)
            return;

        if (!contract.address)
        {
            hash = contract.transactionHash
        }
        else
        {
            // tx mined
            console.log({
                log: 'contract transaction mined',
                hash: hash,
                contractAddress: contract.address
            });

            callback(null, contract, abi);
        }
    }
);
```

Is it because I'm not using the TestRPC provider?
The calls to `eth_mining` and `net_listening` work fine without it though...

Regards,

**Comment by promethe42** [comment]
I can answer my own question:

> Is it because I'm not using the TestRPC provider?

Yep. It is.

**Comment by wighawag** [comment]
I would need this feature (manipulate mining interval) as well as my contract rely on blockNumber and without being able to manipulate the number of transation per block, I cannot test it.

**Comment by tcoulter** [comment]
@wighawag I moved your request to #127 to better consolidate discussion about block times.

**Comment by tcoulter** [comment]
Fixed on master. Will go out with next release.

Apologies for not tackling this earlier as I said I would.
