### ISSUE TITLE
Running ganache-cli with -s parameter and without -d parameter says "Arguments d and s are mutually exclusive"

### ISSUE THREAD

**Issue by kristijan-ujevic** [ConsenSys-archive/ganache-cli-archive#538]
## Expected Behavior

`ganache-cli -p 8545 -s homeNetwork -a 11`

should run a blockchain with a mnemoic from homeNetwork arbitrary data

## Current Behavior

`ganache-cli -p 8545 -s homeNetwork -a 11`

says:

```
Arguments d and s are mutually exclusive

Specify -h, -?, or --help for available options
```

## Your Environment
* Version used: `ganache-cli --version` says `unknown` (i have done a fresh install today though)
* Version of Truffle/Remix/Other tools used: `Truffle v4.1.8 (core: 4.1.8) Solidity v0.4.23 (solc-js)`
* NodeJS Version: `v8.11.2`
* Operating System and version (include distro if Linux): `Ubuntu 17.10`

**Comment by alejoamiras** [comment]
Same happens to me with ganache-cli version 6.1.4

**Comment by rednaxus** [comment]
this got broken between 6.1.0 and 6.1.2 (no 6.1.1 version)

**Comment by mikeseese** [comment]
Thanks for reporting this! I'm looking into this now!

**Comment by mikeseese** [comment]
This is happening because a long lasting issue with `yargs` (https://github.com/yargs/yargs/issues/929)

Looks like this is an easy workaround that doesn't require us to wait for a fix in yargs (by setting the default of the `d` flag to `undefined`).

This should go in the next release!
