### ISSUE TITLE
"ganache-cli --version" returns "unknown"

### ISSUE THREAD

**Issue by travs** [ConsenSys-archive/ganache-cli-archive#541]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

Print the version number.

## Current Behavior

```
$ ganache-cli --version
unknown
```

## Your Environment
* Version used: unknown lol (seems to be `ganache-cli@6.1.3` based on `npm list -g`)
* Version of Truffle/Remix/Other tools used: none
* NodeJS Version: v8.11.2
* Operating System and version (include distro if Linux): 4.16.12-1-ARCH
* I intend to submit a pull request to fix this issue: [ ]

**Comment by mikeseese** [comment]
Thanks for reporting this!

This was actually fixed in #526 with #534. It will be in the next release.
