### ISSUE TITLE
nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

### ISSUE THREAD

**Issue by wuzhitian** [ConsenSys-archive/ganache-cli-archive#542]
```
sudo npm install -g ganache-cli --save-dev
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
events.js:183░░░░░░⸩ ⠙ extract:rxjs: sill extract binaryextensions@2.1.1
      throw er; // Unhandled 'error' event
      ^

Error: write after end
```

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]
* Link to my question on gitter: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Version used:
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [√ ] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): MAC
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by mikeseese** [comment]
Unfortunately I can't reproduce this; I'm guessing it got fixed it in a recent version. Thanks!
