### ISSUE TITLE
Failed to fetch all entries in block filter

### ISSUE THREAD

**Issue by artemistomaras** [ConsenSys-archive/ganache-cli-archive#546]
I am unable to fetch all entries using a block filter in **Web3.py**

## Expected Behavior

Block information to be retrieved from the block filter. 

## Current Behavior
The following exception:

```
eth_newBlockFilter
eth_getFilterLogs
TypeError: c.getAllResults is not a function
    at o.d.getFilterLogs (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:3924080)
    at Timeout._onTimeout (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:3922360)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

## Steps to Reproduce

Start ganache-cli with 
```
ganache-cli -d -p 7545
```

Write the following python code:
```
from web3 import HTTPProvider, Web3

web3 = Web3(HTTPProvider('http://localhost:7545'))
block_filter = web3.eth.filter('latest')

for block in block_filter.get_all_entries():
       print(block)
```

## Your Environment
* Version used: ganache-cli@6.1.4
* Version of Web3py: web3==4.4.0
* Version of Python: 3.6
* NodeJS Version: v9.11.2
* Operating System and version (include distro if Linux): Ubuntu 17.10

**Comment by benjamincburns** [comment]
Duplicates trufflesuite/ganache#879. Normally I'd prefer to track in `ganache-core` but since there's already activity against this issue we'll keep tracking it there.
