### ISSUE TITLE
Revert returns different error.message when run with blocktime vs no blocktime

### ISSUE THREAD

**Issue by cds-amal** [ConsenSys-archive/ganache-cli-archive#549]
When testing revert while running ganache-cli without block time set,  a revert occurs and the error message is `VM Exception while processing transaction: revert...` However with `ganache-cli -b 1` the error message includes the Transaction id stating it exited with an error (status 0).

```
Transaction: 0x3d45180a08e8c3696285352e2758da453c0e804f2f90df56593a3976c339acdd exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
```

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

Both configuration of ganache-cli should return the same error message for a revert.

## Current Behavior
ganache-cli : exception returns an appropriate  revert message
ganache-cli -b 1: returns a transaction id with a hint to check the transaction, that doesn't seem useful for testing purposes.  ie, Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.

## Steps to Reproduce (for bugs)

1. clone this repo: https://github.com/cds-amal/truffle-revert-issue and follow steps in readme.
2. See a asciinema screen cast demonstrating the issue. (and cut and paste text if you need): https://asciinema.org/a/zWISMUH3Wum6pDMAex4zXI7IT

## Context

I am in the Consensys developer program. This inconsistency in the blocktime variant makes testing challenging and presented an opportunity to dig further. 

## Your Environment
* Version used: ganache-cli@6.1.3
* Version of Truffle/Remix/Other tools used: truffle@4.1.12
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ x] 9.x
* Operating System and version (include distro if Linux): OS X
* Link to your project or repro gist: https://github.com/cds-amal/truffle-revert-issue
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by cds-amal** [comment]
Verified reproduction for Ganache CLI v6.1.5 (ganache-core: 2.1.4)

**Comment by cds-amal** [comment]
Verified reproduction for Ganache CLI v6.1.6 (ganache-core: 2.1.5)

**Comment by cds-amal** [comment]
Verified reproduction for Ganache CLI v6.1.8 (ganache-core: 2.2.1)

**Comment by benjamincburns** [comment]
Hi @cds-amal, thanks for raising this! With interval mining we can't run the transaction and report the result instantly in our response. `truffle-contract` does a good job of hiding this for the most part, but I think handling returning revert strings is still an open issue over there.

So unfortunately that's a lot of words to say that I need to close this as this is expected behavior for ganache-cli and friends.

cc @cgewecke

**Comment by cds-amal** [comment]
Thanks for the feedback @benjamincburns . The truffle-contract project is archived under trufflesuite, where should I comment on their related issue? I want to add my test repo for the issue.

Thanks again!

**Comment by mikeseese** [comment]
@cds-amal all of the `truffle-*` packages were moved into a monorepo at https://github.com/trufflesuite/truffle. That's where you should refer any `truffle-contract` issues.

**Comment by cgewecke** [comment]
Hi @cds-amal Visiting this issue from Truffle.

The new error format has a tx hash in it in part so people can grab that easily and pass it to a debugger. In truffle V5 (truffle@beta) you can pass 'reason strings' back with your require/revert statements and they will print out with the message.

Release notes for the beta [here](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0)
