### ISSUE TITLE
persistent data

### ISSUE THREAD

**Issue by JMLX42** [ConsenSys-archive/ganache-cli-archive#55]
Hello,

is there a way to make the `testrpc` data persistent?
I'm especially interested in being able to reuse my existing contracts after restarting `testrpc`.

Thank you,

**Comment by tcoulter** [comment]
Not yet, but this is a feature we've been exploring and hope to implement
soon.

**Comment by JMLX42** [comment]
OK. Then I guess I'll have to create a script to re-mine all my contracts when using `testrpc` then.

Thanks for the fast answer!

**Comment by tcoulter** [comment]
You could also write tests in Truffle and it'll do all that for you.
Disclaimer: I wrote Truffle.

**Comment by JMLX42** [comment]
OK. But (unit) tests are not my only use case for testrpc.
I want to use it mainly during development right now.

**Comment by JMLX42** [comment]
Any idea about the date for this feature?

**Comment by tcoulter** [comment]
Deploying is one of Truffle's main use cases.

No, no date set.

**Comment by JMLX42** [comment]
I was thinking we might leave this open to discuss the matter further. Possible workaround and implementations for example.

My first question would be: would it be foolish to think we could just save the serialized transactions in a file and then replay all of them when testrpc starts? Sure, it's not the best way to do it, but it sounds super easy to do.

Persistent data would be an option, so this startup cost would not impact much existing users.

**Comment by JMLX42** [comment]
My proposal would be to implement a `PersistentDataProvider` and instantiate/add it to the engine:

https://github.com/ethereumjs/testrpc/blob/master/lib/server.js#L157

This new PersistentDataProvider would do two things:
- at run time, it would record each receveid payload in a file ;
- at init time, it would open that file, load all previously recorded payloads and "replay" them (=> pass them to the next provider).

@tcoulter, do you thing that's the right way to do it?

**Comment by JMLX42** [comment]
Hi guys, any update on this ? Thanks,

**Comment by tcoulter** [comment]
Hey @promethe42. This is definitely a very important feature. I don't think I made that clear in my responses. Also, your proposal in the comment above somehow missed my eyeballs (could be that I have so many unread messages in my inbox).

I think your proposal is a good one. Most of us who maintain this are very busy, and I know we're always looking for community support. How's your JS skills? I would love to have you take a shot at this, and if you submitted a PR I would give it serious consideration. 

I like your approach though. Would be happy to include it.

**Comment by JMLX42** [comment]
I will give it a shot then.

**Comment by JMLX42** [comment]
@tcoulter could we use `evm_snapshot` for this?

**Comment by JMLX42** [comment]
Answering my own question: no, we can't use `evm_snapshot` for this. The "snapshot" feature only saves the blocknumber so that we can revert the head of the chain to his block when calling `evm_revert`.

**Comment by janverhulst** [comment]
Are there updates on this? Would really like this feature as well!

**Comment by raga2560** [comment]
I am not restarting testrpc. I just restart my application. Still data stored in my previous run are not there.
Example:- If i have pushed some data into array.It is not present after restarting application.
Is this the way it is supposed to work?

**Comment by mhhf** [comment]
There is quite a large [PR](https://github.com/ethereumjs/testrpc/pull/179) I made with this feature. Collaborators welcome!

**Comment by raga2560** [comment]
I can collaborate on doing this. Let me know where to get started.

**Comment by mhhf** [comment]
@raga2560 So the current branch is currently working, whats left to do is for @tcoulter to review the code and maybe discuss alternative implementation strategy as the old testrpc was not designed to work persistently.
You can start by testing it on your machine and start using it and may report on bugs.

**Comment by benjamincburns** [comment]
Closing this, as this feature is implemented now.
