### ISSUE TITLE
Feature Request: Faucet Feature

### ISSUE THREAD

**Issue by xinbenlv** [ConsenSys-archive/ganache-cli-archive#562]
Dear Team Truffle,

We have been able to run our testnet by simply start a dockerised Ganache-cli on a docker container, which is awesome, and we can then run our development and alpha testing on it. For the sake of testing smooth migration of contracts, we want to use the transaction data generated from Ganache-cli. Therefore we need some way to keep handing out eth. does ganache-cli currently supports faucet feature?  (we can certainly cause it to mine, but it is certainly easier if the ganache-cli can provide features to generate block coinbase with requested testETH amount for given address or batch of addresses)?

Victor

**Comment by mikeseese** [comment]
If someone wants to take this on, please state your interest so we can chat about your design thoughts. Thanks!

**Comment by xinbenlv** [comment]
The basic idea is to provide a command interface that
when requested, the ganache instance mines a new block with given address and given amount of eth

**Comment by mikeseese** [comment]
Yup, I think this implementation should be done within the https://github.com/trufflesuite/ganache-core repository. I'm thinking a custom RPC method (i.e. `evm_fund`) which would add a block/transaction to fund the specified account the specified ETH.

However @xinbenlv to answer your question (even though it was implied), there currently isn't a way to do this. Sorry for the delay on responding!

**Comment by xinbenlv** [comment]
Thanks, that would be great. 

By the way, just a side question: being one of the most successful developer-oriented communities for blockchain, has truffle considered use token to incentivize developer help for your open source projects?

I couldn't imagine any other project closer to this goal (using token to incentivize community contributions)

**Comment by mikeseese** [comment]
@xinbenlv We have had a [few software bounties](https://gitcoin.co/explorer?keywords=trufflesuite&order_by=-web3_created) for higher priority issues, yes.

Closing this issue in favor of https://github.com/trufflesuite/ganache-core/issues/160

**Comment by xinbenlv** [comment]
Great to hear you have bounty program. Hah, I don't have anywhere to know that this exist. Why don't you put it on your README.md so more people can know it? :)

**Comment by mikeseese** [comment]
It's not really a bounty program haha, and not all of those issues are funded by us; I just pulled the quickest link to show that we do pay bounties from time to time.

I'll let the Truffle devs handle your PR, but I'm guessing there will be some push back as we'd rather have our own landing page for bounties, and that would only happen if we really funded enough to justify a page. We would also want to do it for all of the repos.

**Comment by xinbenlv** [comment]
SGTM~
