### ISSUE TITLE
Out-Of-Gas bug not fixed in v6.1.8

### ISSUE THREAD

**Issue by dstsmallbird** [ConsenSys-archive/ganache-cli-archive#565]
## Description

With the following contract, if the contract is owning some ether, the withdraw() function will throw an out-of-gas exception. And the contract works fine with Javascript VM provided by Remix.

```
contract Money {  
    constructor() public payable {}  
    function withdraw() {  
        msg.sender.transfer(this.balance);  
    }  
}  
```

Besides, it will be reverted if I run test() function in Run to create a Test.

```
contract Test {  
    constructor() public {}  
}  
  
contract Run {  
    function test() returns (bool) {  
        new Test();  
        return true;  
    }  
}
```

## Expected Behavior

As the Javascript VM behaved.

## Current Behavior

For contract Money, it will throw an out-of-gas exception.
For contract Run, it will be reverted.

## Possible Solution

Maybe it's caused by eth_estimateGas.

## Steps to Reproduce (for bugs)

Using the contracts in description.

## Your Environment
* Version used: v6.1.8, with core version v2.2.1
* Version of Truffle/Remix/Other tools used: Truffle & Remix
* NodeJS Version: 9.x
* Operating System and version (include distro if Linux): macOS High Sierra 10.13.4

**Comment by davidmurdoch** [comment]
Thanks for reporting this. I'm testing this now. I suspect this is related to https://github.com/trufflesuite/ganache-core/issues/147

**Comment by davidmurdoch** [comment]
@dstsmallbird, I've confirmed the `eth_estimateGas` under-estimation in your provided test cases here: https://github.com/trufflesuite/ganache-core/commit/de18c4ca7a73ecbc79b446bae51be9102b2571be

I'm closing this one since these cases will be tracked in https://github.com/trufflesuite/ganache-core/issues/147

Thanks again!
