### ISSUE TITLE
Error: sender doesn't have enough funds to send tx.

### ISSUE THREAD

**Issue by princesinha19** [ConsenSys-archive/ganache-cli-archive#568]
I have the issue **"Error: sender doesn't have enough funds to send tx.  The upfront cost is: 6000000000000000 and the sender's account only has: 0"**. It occurs every time after doing first transaction. 
My ganache version is:-
![screenshot from 2018-08-28 13-06-19](https://user-images.githubusercontent.com/28489437/44707817-2de30f00-aac3-11e8-9226-0c205a3e9065.png)

**Comment by davidmurdoch** [comment]
Thanks @princesinha19 for reporting this. Can you provide steps to reproduce?

**Comment by davidmurdoch** [comment]
Possibly related to https://github.com/trufflesuite/ganache-core/issues/161

**Comment by princesinha19** [comment]
yes @davidmurdoch.
Steps to reproduce 
1. Run ganache in background using command **nohup ganache-cli -h 0.0.0.0 -p 8545 &>/dev/null &**
2. Deploy contract and then do one transaction.
3. On next transaction it shows error **"Error: sender doesn't have enough funds to send tx. The upfront cost is: 6000000000000000 and the sender's account only has: 0"**

**Comment by mikeseese** [comment]
@princesinha19 Unfortunately we can't reproduce the error with your steps. Given your error, it seems that you're not using the correct account in your transaction. Please reopen if you have specific reproduction steps. Sorry we couldn't be more help!

**Comment by princesinha19** [comment]
I have solved this issue by removing **-h 0.0.0.0** parameter from the command.
Thanks for your comments @davidmurdoch @seesemichaelj.
