### ISSUE TITLE
"to" for contract deployment is present and equal to "0x0"

### ISSUE THREAD

**Issue by D4nte** [ConsenSys-archive/ganache-cli-archive#579]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5bbc4af7c08b8b3067f1c674

## Expected Behavior

Regarding `web3.eth.getTransaction`. [Web3js doc](https://web3js.readthedocs.io/en/1.0/web3-eth.html#gettransaction).

```
to - String: Address of the receiver. null when its a contract creation transaction.
```
`null` should be returned when it is a transaction for a contract creation.

## Current Behavior

`0x0` is being returned:

```
"to": "0x0",
```

## Possible Solution

return `null` as per web3js doc.

## Steps to Reproduce (for bugs)

1. Deploy a contract.
2. Save the transaction hash
3. Run `{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["<transaction hash>"],"id":1}`
4. Look at the `to` value.

E.g.
Request:
```json
{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x09bd46e048485d4e70ef00b181b033a015314b52e3fc50a8762d9af69620e87c"],"id":1}
```
Response:
```
{
    "id": 8,
    "jsonrpc": "2.0",
    "result": {
        "hash": "0x09bd46e048485d4e70ef00b181b033a015314b52e3fc50a8762d9af69620e87c",
        "nonce": "0x0",
        "blockHash": "0x42ca22da634f523cfdf8e4bdbd298bb6a796077a746a53dc7e92f09ec494ccc7",
        "blockNumber": "0x01",
        "transactionIndex": "0x00",
        "from": "0x147ba99ef89c152f8004e91999fee87bda6cbc3e",
        "to": "0x0",
        "value": "0x8ac7230489e80000",
        "gas": "0x0170c0",
        "gasPrice": "0x77359400",
        "input": "0x4...9"
    }
}
```
## Context
When using `rust-web3` library, the unexpected value of `0x0` leads to deserialization issue, stopping the consumer (my application) to do anything with this transaction.

## Your Environment
* Version used:
* Version of Truffle/Remix/Other tools used: ganache-docker v6.1.3
* Operating System and version (include distro if Linux): Mac OS X
* I intend to submit a pull request to fix this issue: [ ] I am happy to look into it if the issue is accepted.

**Comment by D4nte** [comment]
Please note that the `to` is referred as `empty account` in solidity documentation too https://solidity.readthedocs.io/en/v0.4.25/introduction-to-smart-contracts.html

**Comment by davidmurdoch** [comment]
Thanks for reporting, @D4nte! I've confirmed that this is still an issue in our develop branch version of `ganache-core`, though interestingly the response is now `0x` instead of `0x0`.

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache-cli/issues/579

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache-core/issues/59
