### ISSUE TITLE
Feature request: please add -t or --startTime: Epoch time

### ISSUE THREAD

**Issue by pieterhartel** [ConsenSys-archive/ganache-cli-archive#580]
I would find the following cli option very useful:

```
-t or --startTime: Epoch time in seconds that the first block should start.
Use this feature, along with the evm_increaseTime method to test time-dependent code.
```

It is easy to implement because Ganache-core provides the feature already.

I have implemented this feature in my clone of ganache-cli here [https://github.com/pieterhartel/ganache-cli](url) but it would be nice if my feature could be merged into the main stream.

--pieter

**Comment by davidmurdoch** [comment]
Thanks @pieterhartel! At first glance this looks like a great feature to add. Do you mind making a pull request from your branch?

**Comment by pieterhartel** [comment]
I don’t really know what a pull request is, sorry. Feel free to use my changes!

—pieter

**Comment by martianov** [comment]
Hi David, Pieter,

I faced with the same problem couple of days ago. But I think it may be more convenient to use more user-friendly format for dates than epoch time. I've opened PR for that changes #581.

Let me know what you think about it please. Thanks!
