### ISSUE TITLE
eth_call with blockNumber parameter with 0x prefix

### ISSUE THREAD

**Issue by RomanFro** [ConsenSys-archive/ganache-cli-archive#582]
## Expected Behavior

Get result or error message.

## Current Behavior

Nothing, test rpc just dies without error. It's not just about it not saying anything about error, but stopping to function completely.

## Possible Solution

Parse input `blockNumber` parameter (which can be tag like `latest` as well).

## Steps to Reproduce (for bugs)

I used 6.1.0 and 6.1.8 versions of ganache-cli.

1. make request with calling method `eth_call` and pass as block number just plain decimal number.
2. ganache dies without **any** message/response.

I reproduced this bug by using both `web3.currentProvider.sendAsync` and `jayson.client.http.request` for request.

(web3 0.20.6 version)

## Context

It would be nice if ganache responded like geth does:

```
{ jsonrpc: '2.0',
  id: '4fad3d7b-7f01-4959-a937-5b8c35a02d63',
  error:
   { code: -32602,
     message: 'invalid argument 1: hex string without 0x prefix' } }
```

## Your Environment
* Version used: 6.1.8
* Version of Truffle/Remix/Other tools used: -
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [x] 9.x
* Operating System and version (include distro if Linux): MacOs High Sierra 10.13.6
* Link to your project or repro gist: -
* Commit hash to use with above link for reproduction: -
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
@RomanFro Thanks for reporting this!

When you say "decimal number", do you mean you are passing in something with decimal places, e.g., something like `5.5`?

For reference, our current logic is as follows:
```
getBlock: function(number, done) {
  try {
    number = to.number(number)
  } catch (e) {
    // Do nothing; must be a block hash.
  }

  self.getBlock(number, done)
}
```

where `to.number` is:

```
  number: function(val) {
    if (typeof val == "number") {
      return val;
    }
    if (typeof val == "string") {
      if (val.indexOf('0x') != 0) {
        return parseInt(val)
      }
    }
    return utils.bufferToInt(utils.toBuffer(val));
  }
```
which should handle numbers (`5`), RPC-encoded Quantity/Data Strings (e.g., `"0x5"`/`"0x05"`), and numbers as strings (`"5"`).

`"latest"`, `"pending"`, and `"earliest"` are handled elsewhere.

**Comment by RomanFro** [comment]
@davidmurdoch Thank you for quick reply.

I meant just integer value like 10.

And btw I should specify that number was of type string, this is an important note.

**Comment by RomanFro** [comment]
https://gist.github.com/RomanFro/20683c4d3b9e27511835c9be05f3fb90

**Comment by davidmurdoch** [comment]
Thanks @RomanFro. Thanks for the gist! Using it, i've confirmed that this is an issue when using the `ganache-core` provider directly; we incorrectly assume that a number stored as a string that doesn't begin with `0x` is a block tag and due to another bug we never call the callback and ganache will hang forever and will stop processing any further requests.

For maintainers, the buggy code is: https://github.com/trufflesuite/ganache-core/blob/cf723a0482e9e9706e03f997f1f88872fbfbce92/lib/blockchain_double.js#L187-L215
