### ISSUE TITLE
Console logs errors on startup

### ISSUE THREAD

**Issue by thatcort** [ConsenSys-archive/ganache-cli-archive#587]
When I run `ganache-cli` the console prints a continuous stream of error messages:

```
Listening on 127.0.0.1:8545
FilterSubprovider - no filter with that id: 0x05
eth_getFilterChanges
FilterSubprovider - no filter with that id: 0x05
eth_getFilterChanges
FilterSubprovider - no filter with that id: 0x05
eth_getFilterChanges
FilterSubprovider - no filter with that id: 0x05
eth_getFilterChanges
FilterSubprovider - no filter with that id: 0x05
eth_call
eth_getFilterChanges
FilterSubprovider - no filter with that id: 0x05
eth_call
eth_getFilterChanges
...
```

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5bdbcdcbb9c91919548a167b

## Expected Behavior

Don't print a continuous stream of error messages

## Current Behavior

It prints a continuous of stream of error messages

## Steps to Reproduce (for bugs)

1. `npm i -g ganache-cli`
2. `ganache-cli`

## Your Environment
* Version used: 6.1.8
* Version of Truffle/Remix/Other tools used: Truffle: 4.1.14
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x [x] 10.12.0
* Operating System and version (include distro if Linux): MacOS 10.13.6
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Thanks for filing this issue, @thatcort. From the logs it looks like something is immediately connecting to ganache-cli and attempting to get filter changes with an unknown id.

Can you still reproduce this issue?

**Comment by thatcort** [comment]
I eventually got things to work. I'm no longer sure how (some combination of reinstalling and trying various versions of Node). I suspect it may have been caused by switching the node version after installing and that might have conflicted with the natively compiled assets, but that's just a hunch. I'll close this, since I can't be of more helpl
