### ISSUE TITLE
Feature request: Log filters

### ISSUE THREAD

**Issue by roschler** [ConsenSys-archive/ganache-cli-archive#588]
### PROBLEM TO BE SOLVED

One of the few usability issues remaining with the Ganache GUI client is the need for log filtering.  A really powerful filter would be the addition of filter to the logging window.  The problem is, clients like the ubiquitous Metamask make certain RPC calls repeatedly to the log (once a second) so the log window is overlowing with with noise messages.  Worse, I believe it possibly is the cause of the Ganache client locking up when it has been running too long, in my case about day.  The reason I feel the log window overflowing is the cause of the crash is because after about 10 hours, switching to the log Tab takes many seconds, taking even more seconds as the runtime goes on until it completely locks up the client.  If you turn on `verbose` logging the time from to a crash compresses down to 2 hours or less.

This screen shot shows the Metamask client pinging the client once a second with an `eth_blockNumber` call:

![screenshot from 2018-11-03 00-05-14](https://user-images.githubusercontent.com/4660487/47947911-4a088f80-defc-11e8-9251-a4a188b6a0e0.png)

### FEATURE REQUEST

There could be a new tab in the Ganache client could `Filters`.  It would have a multi-line edit box and  a checkbox.  The edit box would contain a list of the RPC function call names that should be filtered (i.e. - not printed to the log), one function call name per line.  The checkbox turns filtering on and off.  For example, the edit box could contain `eth_blockNumber`, etc.

Right now you have to execute the tedious workflow of trying to clear the logs right before a transaction you are trying to debug.  Quickly grabbing the log contents after you get the desired transaction report, and then copying and pasting the logs to editor to cull out the desired log messages from the stream.

**Comment by davidmurdoch** [comment]
Issue moved to [trufflesuite/ganache #953](https://github.com/trufflesuite/ganache/issues/953) via [**ZenHub**](https://www.zenhub.com/)
