### ISSUE TITLE
eth_estimateGas inaccurate gas estimation under specific circumstances (attached Solidity sample).

### ISSUE THREAD

**Issue by Enigmatic331** [ConsenSys-archive/ganache-cli-archive#592]
## Current Behavior
With the below Solidity code, running eth_estimateGas on Ganache returns a slightly lower gas estimate compared to client implementations, subsequently during the execution of the code an out of gas error is encountered.

## Expected Behavior
In both cases client implementations provided a gas estimate of 28579, slightly higher than what is consumed at 28537; Whereas Ganache CLI provided an estimate of exactly 28537. Suspect it might be something to do with gas refunds (where Ganache CLI returns the gas estimates based off the final gas used post-transaction, instead of the highest gas used during the transaction).

## Steps to Reproduce (for bugs)

Solidity Code:
```
pragma solidity ^0.4.24;

contract BulkContract {

    address public balanceAddress;

    constructor() public {
        balanceAddress = new balanceContract();
    }

    function transaction() public {
        balanceContract t = balanceContract(balanceAddress);
        t.execute();
    }
}

contract balanceContract {
    
    // setting variable to non-zero
    // so we can work on a consistent gas limit from the get-go
    uint256 public counter = 1;

    constructor() public { }
    
    function execute() public {
        counter = counter + 1;
    }
}
```
<br />
<br />

Running estimates through Ganache CLI: Estimated gas amount isn't sufficient to complete transaction.
![image](https://user-images.githubusercontent.com/28551011/48699449-6c045080-ec24-11e8-850f-89de99d0fa75.png)

<br />

Comparing this through a private testnet (Geth 1.8.2):
![image](https://user-images.githubusercontent.com/28551011/48699894-825edc00-ec25-11e8-86b0-c787bd397b16.png)

<br />

Comparing this through Rinkeby:
![image](https://user-images.githubusercontent.com/28551011/48699997-cd78ef00-ec25-11e8-9eab-0f03d148d26f.png)

## Your Environment
* Version used: Ganache CLI v6.2.1/6.1.8
* Version of Truffle/Remix/Other tools used: Nethereum v3.0.0-rc-1
* NodeJS Version: v8.11.1
* Operating System and version (include distro if Linux): Windows 10

Feel free to let me know if you'd like any additional information at all. Thanks in advance - And thanks for the Truffle suite! :D

**Comment by davidmurdoch** [comment]
This should now be fixed in the latest **beta** tagged releases of ganache-cli and ganache-core.

This fix involved pretty significant code changes; check out the [release notes](https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4-beta.2) for details.

**We'd love it if you'd test this beta out to make sure things are good to go before we release to stable.** 

If you using `ganache-cli`, run: 

```console
npm install -g ganache-cli@beta
```

If you are using `ganache-core`, run:

```console
npm install ganache-core@beta
```

Let us know if you discover any bugs with this new beta release! Thanks!

**Comment by S3bb1** [comment]
Hi, sorry reopen this ticket. But trying out the above example still gives me a "Revert". Tested with ganache cli 6.4.4-beta.0

```
eth_sendTransaction

  Transaction: 0x9bb3f74771f1778dfa567fe33039014f4a3586bb8ea7cc55c5546a622ef8d75c
  Contract created: 0x3edd854c5fc429043a1ed2bbc8d656614f216732
  Gas usage: 180460
  Block Number: 1
  Block Time: Tue May 07 2019 07:23:21 GMT+0200 (GMT+02:00)
  Runtime Error: revert
```

**Comment by Enigmatic331** [comment]
Hey Sebastian :)

I tested the examples above on v6.4.3 and v6.4.4-beta but seems to work fine though (much thanks to the Truffle team!) - Or I misunderstood and it was something else you were running?

![image](https://user-images.githubusercontent.com/28551011/57308809-8c17c580-7119-11e9-85f5-410dcaac1fc8.png)

**Comment by S3bb1** [comment]
Hey Enigma :)

Thanks for your response! I've tested the contract in the issue ticket with Remix:

![image](https://user-images.githubusercontent.com/763247/57317227-eacc4780-70f7-11e9-8291-2e44b1125999.png)

Before i ran `` ganache-cli `` without any arguments and i see the following response:

![image](https://user-images.githubusercontent.com/763247/57317349-2404b780-70f8-11e9-9783-cbe9d8ab27ed.png)

**Comment by Enigmatic331** [comment]
Ah you're absolutely right Sebastian. I tested via Remix (also through Remix > Metamask on localhost:8545) and gotten the same issue too.

Looks like it might be reverting at the part where the contract attempts to create another contract - Will see if I could find anything, and open an issue later in the morning.

ADD: Yea... Had to manually increase the gas limit from its original estimates when I was on Metamask...


![image](https://user-images.githubusercontent.com/28551011/57320016-7feb3280-7130-11e9-80ec-c6e386779b55.png)


Transaction gas use:

![image](https://user-images.githubusercontent.com/28551011/57320076-a7da9600-7130-11e9-8860-7e7927acb178.png)

**Comment by S3bb1** [comment]
got it to work :) i've found another bug for the REVERT stuff from my private factory. I'll open another ticket

**Comment by S3bb1** [comment]
Ah nice! :) I have some other smart contracts (which also creating new ones) and fail also. Will open a new ticket for this
