### ISSUE TITLE
Version 6.2.X does not work good with Ethers.JS

### ISSUE THREAD

**Issue by sweetpalma** [ConsenSys-archive/ganache-cli-archive#598]
## Expected Behavior

Ethers.JS method "sendTransaction" (used both directly and as a part of the contract method execution) should work correctly with Ganache and make properly signed transactions.

## Current Behavior

Ethers.JS fails to sign transaction because it seems like Ganache is changing some of its fields under the hood, causing the txHash mistmatch, what leads to the nasty error - basically, making it completely unusable:

`Error: Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0xf6878651c3eefc608e4852a4fdcf28dd9319f950b78dfb0dcf6d726ab2dd153b", returnedHash="0xf9b4f394391c0f14b22337a0d496bc36d2c54f7fce2f061c4e98e3710afbe355")`

You can fix it by reverting Ganache back to the v6.1.8, but damn, that's not a real solution.

## Steps to Reproduce (for bugs)

1. Install Ganache of the version 6.2.X.
2. Install ethers.js of the version 4.0.X (no idea how it is going to work on the older versions).
3. Try sending transactions or calling contract methods.
4. Check error details.

## Your Environment
* Version used: v6.2.3
* Version of Truffle/Remix/Other tools used: Ethers 4.0.13.
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [x] 9.x
* Operating System and version (include distro if Linux): OS X.
* Link to your project or repro gist: Private.
* Commit hash to use with above link for reproduction: Private.
* I intend to submit a pull request to fix this issue: [ ] 

## Related issues:
https://github.com/ethers-io/ethers.js/issues/275

**Comment by davidmurdoch** [comment]
Thanks @sweetpalma 	Fixed in [ganache-cli@6.2.4](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.2.4). Also added a note about connecting ethers.js to ganache-cli in our readme.md.
