### ISSUE TITLE
Residual test state shared between test files when working with truffle@5.0.0.beta.2

### ISSUE THREAD

**Issue by elenadimitrova** [ConsenSys-archive/ganache-cli-archive#602]
## Expected Behavior

The `before`, `beforeEach`and tests in a single test file should not be returning different results when querying a contract property instance that hasn't been changed in that test file.

## Current Behavior
1st test file runs
   `beforeEach` - instantiates a new token `CLNY = Token.new()`=> and sets it on `ColonyNetwork.deployed()`

2nd test file runs
   `before` - get `ColonyNetwork.deployed()` => get CLNY - returns a new address
  `beforeEach` - get `ColonyNetwork.deployed()` => get CLNY- returns a new address
   helper function - get `ColonyNetwork.deployed()` => get CLNY - returns the address from 1st test above
The `before` and `beforeEach` of 2) are inventing some unknown token instance

## Steps to Reproduce (for bugs)
I haven't had time to isolate this into a minimum working example, but using our test suite at Colony you can just run `colony-network-auction.js` and `colony-network-mining.js` test files and observe this problem in that the MetaColony.token property differs in `colony-network-mining.js` between the `before` and tests.

## Your Environment
* Version used: `ganache-cli@6.2.3`
* Version of Truffle/Remix/Other tools used: `truffle@5.0.0.beta.2`
* NodeJS Version: 9.11.2
* Operating System and version (include distro if Linux): OSX
* Link to your project or repro gist: https://github.com/JoinColony/colonyNetwork
* Commit hash to use with above link for reproduction: 
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Thanks @elenadimitrova. Looking into this now!

**Comment by davidmurdoch** [comment]
@elenadimitrova, Were you able to get a minimal test case for this issue? We're having a hard time pinpointing the issue ourselves.

**Comment by 0xAshish** [comment]
I am having the same issue as well @davidmurdoch, I can run individual test perfectly but not in full test suite.

**Comment by nicholasjpaterno** [comment]
@elenadimitrova, thanks for reporting this and @0xAshish for the additional info!

Can you try the latest ganache-cli@beta (v6.2.4-beta.1) and let us know if you're still experiencing this issue during your unit tests?

**Comment by 0xAshish** [comment]
@nicholasjpaterno Thanks that worked awesomely. 😎

**Comment by nicholasjpaterno** [comment]
@0xAshish Awesome, very glad to hear that!

I'm going to close this for now, @elenadimitrova if you're still experiencing this issue - please feel free to reopen!

**Comment by elenadimitrova** [comment]
This is fine for us too. Thanks for addressing @nicholasjpaterno !
