### ISSUE TITLE
There should be a latest stable tag on docker hub

### ISSUE THREAD

**Issue by zmmille2** [ConsenSys-archive/ganache-cli-archive#608]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

`latest` docker tag should not point to a beta version, or there should be a `latest-stable` tag as well.

## Current Behavior

`latest == vx.x.x-beta.x`

## Possible Solution

`latest == vx.x.x`
OR
`latest == vx.x.x-beta.x` AND `latest-stable == vx.x.x`

## Context
We're running some docker images based on `latest`, and that's causing some issues likely related to beta functionality.  We're seeing different behaviors on Windows and Linux, for example.

## Your Environment
* Version used: `latest`
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): Windows
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]
    * Not sure if this is a fix that I can PR: docker image tag would need an update for this suggestion to be implemented.

**Comment by mikeseese** [comment]
This may be an issue with our CI/CD setup. @davidmurdoch is looking into it. We didn't mean to point `latest` to beta releases

**Comment by zmmille2** [comment]
Looks like this has been addressed, seeing a beta and next tag on [Dockerhub](https://hub.docker.com/r/trufflesuite/ganache-cli/tags).  Closing here.
