### ISSUE TITLE
eth_getTransactionCount returns 2, but eth_sendRawTransaction complains that it expects a nonce of 65

### ISSUE THREAD

**Issue by coventry** [ConsenSys-archive/ganache-cli-archive#610]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [X]
* Link to my question on gitter: 
https://gitter.im/ConsenSys/truffle?at=5c13e0cbb4c74555ccc9cb51

(Spread over a few subsequent messages)

## Expected Behavior

A `sendRawTransaction` immediately following a `getTransactionCount` reporting a value of 2 should expect a nonce of 2, not 65. 

## Current Behavior

`getTransactionCount` reports a value of 2, and when a transaction with this nonce is sent by `sendRawTransaction`, `ganache` throws, complaining that the expected nonce was 65:

```
eth_getTransactionCount
   > {
   >   "jsonrpc": "2.0",
   >   "id": 136,
   >   "method": "eth_getTransactionCount",
   >   "params": [
   >     "0x627306090abab3a6e1400e9345bc60c78a8bef57",
   >     "pending"
   >   ]
   > }
 <   {
 <     "id": 136,
 <     "jsonrpc": "2.0",
 <     "result": "0x2"
 <   }
eth_sendRawTransaction
   > {
   >   "jsonrpc": "2.0",
   >   "id": 137,
   >   "method": "eth_sendRawTransaction",
   >   "params": [
   >     "0xf924bd028502...
   >   ]
   > }
 <   {
 <     "id": 137,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "the tx doesn't have the correct nonce. account has nonce of: 65 tx has nonce of: 2",
 <       "code": -32000,
 <       "data": {
 <         "stack": "TXRejectedError: the tx doesn't have the correct nonce. account has nonce of: 65 tx has nonce of: 2\n    at self.blockchain.getQueuedNonce (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/lib/statemanager.js:966:11)\n    at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/lib/blockchain_double.js:465:5\n    at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:77:5\n    at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14\n    at Object.return (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:485:9)\n    at processNode (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:285:30)\n    at processNode (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:521:5)\n    at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13\n    at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)",
...
```

## Possible Solution

I don't have a solution, but it seems that this failure may be triggered in some way by the `evm_snapshot` and `evm_revert` RPC events just prior. `truffle` makes it through the tests for the first contract OK, but fails on every subsequent set of contract tests. I suspect that `sendRawTransaction` may be tracking the nonce independently of whatever mechanism `getTransactionCount` is using, and this is the ultimate source of the bug.

## Steps to Reproduce (for bugs)

The above output was generated with 

```
$ ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --verbose | tee /tmp/output.log
```

using version `Ganache CLI v6.2.3 (ganache-core: 2.3.1)`, and running the solidity tests on [this branch](https://github.com/smartcontractkit/chainlink/tree/example/nonce-race-condition] of the chainlink code. ([chainlink install instructions](https://github.com/smartcontractkit/chainlink#install), then `cd solidity; ../node_modules/.bin/truffle test --verbose-rpc`. )

It should also be possible to reproduce using the [full output](https://github.com/trufflesuite/ganache-cli/files/2682031/output.log), which contains every RPC transaction leading up to the failure.

## Context

I can still develop, because each set of tests run fine on their own. But it makes using truffle difficult in a CI environment.

## Your Environment
* Version used: 
```
$ ganache-cli --version
Ganache CLI v6.2.3 (ganache-core: 2.3.1)
```

* Version of Truffle/Remix/Other tools used:
```
$ ./node_modules/.bin/truffle version
Truffle v5.0.0-next.24 (core: 5.0.0-beta.2)
Solidity - 0.4.24 (solc-js)
Node v8.10.0
```

* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): AWS t2.xlarge, ubuntu image:
```
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l
```
* Link to your project or repro gist: [branch with this failure](https://github.com/smartcontractkit/chainlink/tree/example/nonce-race-condition)
* Commit hash to use with above link for reproduction:
```
$ git log | head
commit 9e6b378842c5ae9ea40ffc451bdac0f77437c28d
```
* I intend to submit a pull request to fix this issue: [ ]

**Comment by coventry** [comment]
Fixed the link to the branch with the triggering code: https://github.com/smartcontractkit/chainlink/tree/example/nonce-race-condition

**Comment by davidmurdoch** [comment]
There are some issues with snapshot and revert in the latest version. Can you try the current beta `npm install ganache-cli@beta -g` and let me know if that fixes the issue for you?

**Comment by coventry** [comment]
Thank you, that seems to be failing in a different way. (I am porting a test suite to latest truffle/ganache, so other errors are expected.) I will investigate for a few hours, and probably close this issue if it proves solved by the beta version.

**Comment by coventry** [comment]
Oh, and I just noticed the nonces now match, so I'm pretty confident it's fixed in the beta.
