### ISSUE TITLE
Feature request: save xmlhttpreqeust file to tmp directory

### ISSUE THREAD

**Issue by 4000D** [ConsenSys-archive/ganache-cli-archive#613]
`echo $TMPDIR` shows us the temporary directory path used by many other applications. `ganache-cli` also may use this directory to save `.node-xmlhttprequest-sync-*` files instead of `pwd` of running `ganache-cli`.

**Comment by nicholasjpaterno** [comment]
@4000D thanks for reporting this issue! What version of ganache-cli are you using?

**Comment by 4000D** [comment]
@nicholasjpaterno I'm using `Ganache CLI v6.2.3 (ganache-core: 2.3.1)` :)

**Comment by davidmurdoch** [comment]
Do you use an older version of web3 (pre v1-beta) in your project, by any chance?

**Comment by davidmurdoch** [comment]
Closing due to age. @4000D 	please open a new issue if this is still an issue.
