### ISSUE TITLE
delegatecall always throws exception

### ISSUE THREAD

**Issue by haseebrabbani** [ConsenSys-archive/ganache-cli-archive#614]
## Expected Behavior

When invoking a contract function using `delegatecall`, expecting the function to be invoked without throwing an exception

## Current Behavior

Invoking a function using `delegatecall` always throws an exception

## Steps to Reproduce (for bugs)

1. Run `ganache-cli` locally
2. Open up Remix in Chrome browser (https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.24+commit.e67f0147.js)
3. Connect to local Ganache on port 8545 using Metamask (and import at least one Ganache account)
4. Load the following `Implementation` and `Proxy` contracts into Remix
```
pragma solidity 0.4.24;

contract Implementation {

    bool public boolean = false;

    function initBoolean() public {
        boolean = true;
    }
}
```

```
pragma solidity 0.4.24;

/**
 * @title Proxy
 * @dev Gives the possibility to delegate any call to a foreign implementation.
 * @dev source https://github.com/zeppelinos/labs/blob/master/upgradeability_using_unstructured_storage/contracts/Proxy.sol
 */
contract Proxy {

    // Storage position of the address of the current implementation
    bytes32 private constant implementationPosition = keccak256("org.meridio.proxy.implementation");
    
    /**
    * @dev Tells the address of the current implementation
    * @return address of the current implementation
    */
    function implementation() public view returns (address impl) {
        bytes32 position = implementationPosition;
        assembly {
          impl := sload(position)
        }
    }

    /**
    * @dev Sets the address of the current implementation
    * @param newImplementation address representing the new implementation to be set
    */
    function setImplementation(address newImplementation) public {
        bytes32 position = implementationPosition;
        assembly {
          sstore(position, newImplementation)
        }
    }

    /**
    * @dev Fallback function allowing to perform a delegatecall to the given implementation.
    * This function will return whatever the implementation call returns
    */
    function () payable public {
        address _impl = implementation();
        require(_impl != address(0));

        assembly {
            let ptr := mload(0x40)
            calldatacopy(ptr, 0, calldatasize)
            let result := delegatecall(gas, _impl, ptr, calldatasize, 0, 0)
            let size := returndatasize
            returndatacopy(ptr, 0, size)

            switch result
            case 0 { revert(ptr, size) }
            default { return(ptr, size) }
        }
    }
}
```
5. Deploy an instance of the `Implementation` contract using 'Deploy' button under 'Run' tab
6. Deploy an instance of the `Proxy` contract using 'Deploy' button under 'Run' tab
7. Invoke the `setImplementation` function on `Proxy` contract by passing the `Implementation` contract address as parameter
8. Copy `Proxy` contract address to clipboard
9. Connect to proxied `Implementation` contract instance by providing `Proxy` contract address in 'At Address' field under 'Run' tab while having 'Implementation' selected in dropdown
10. Invoke the `initBoolean` function on the *proxied* `Implementation` contract
11. Observe error thrown in Metamask `ALERT: [ethjs-rpc] rpc error with payload {"id":2223915565426,"jsonrpc":"2.0","params":["0xf86d03843b9aca0082a7e094927e4f400e4114b644f8aba29fa20982c401767f8084d9cf350e8602d09a343fdea0cfdcdb89dc1862eaa295cdbbfc9f693e8e2506d4db9da096ef9b6d01a00c33a7a067471fdb9575e534b375ad7c60e8a4a8a304ae95e3194e60a2cd46d9b427863b"],"method":"eth_sendRawTransaction"} Error: VM Exception while processing transaction: revert`

## Context

This bug is preventing our app from working correctly while pointed to a local instance of ganache-cli. The issue also reproduces with Ganache UI 1.2.3.397. We verified that the above contracts work as expected on Rinkeby, as well as the Remix Javascript VM. What is also strange is that our Mocha tests written for this specific scenario pass successfully.

## Your Environment
* Version used: ganache-cli 6.2.5
* Version of Truffle/Remix/Other tools used: Metamask 5.3.0, Remix 0.7.5, solc-js 0.4.24+commit.e67f0147.js, Chrome 71.0.3578.98 
* Operating System and version: MacOS 10.14

**Comment by davidmurdoch** [comment]
Thanks for filing the issue, @haseebrabbani. This is due to a gas estimation bug when contract functions use certain op codes defined in [EIP-150](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md). We are currently working on a fix for this underestimation bug and are tracking this issue here: https://github.com/trufflesuite/ganache-core/issues/147

**Comment by davidmurdoch** [comment]
This should now be fixed in the latest **beta** tagged releases of ganache-cli and ganache-core.

This fix involved pretty significant code changes; check out the [release notes](https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4-beta.2) for details.

**We'd love it if you'd test this beta out to make sure things are good to go before we release to stable.** 

If you using `ganache-cli`, run: 

```console
npm install -g ganache-cli@beta
```

If you are using `ganache-core`, run:

```console
npm install ganache-core@beta
```

Let us know if you discover any bugs with this new beta release! Thanks!
