### ISSUE TITLE
Invalid JSON-RPC response when sending tokens with insufficient balance

### ISSUE THREAD

**Issue by webmaster128** [ConsenSys-archive/ganache-cli-archive#619]
I use ganache-cli v6.2.5 (via docker). When I send a ETH send transaction from an account with insufficient funds (unused account), I get the following response over the HTTP API: `{"jsonrpc":"2.0","id":5}`. However, this not valid JSON-RPC since the specs say, that either `result` or `error` is required: https://www.jsonrpc.org/specification#response_object

> Either the result member or error member MUST be included, but both members MUST NOT be included.

**Comment by davidmurdoch** [comment]
I'm unable to reproduce. Can you provide your docker command and transaction params?

**Comment by webmaster128** [comment]
Tried to prepare an example and it turned out the bug is 100 % in our client implementation. Sorry for wasting your time!

**Comment by davidmurdoch** [comment]
Thanks for following up, @webmaster128. Let us know if you do find any issues or bugs!
