### ISSUE TITLE
3.4 "Related Releases" ganache-core is mislabled as ganache-cli

### ISSUE THREAD

**Issue by zachlysobey** [ConsenSys-archive/ganache-cli-archive#622]
Sry if this is just noise for you and not worth fixing.

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5c51a14c8aa5ca5abf56fbbe

### Related Releases:

- [ganache-core](https://github.com/trufflesuite/ganache-core/releases/tag/v2.4.0)

### Related Releases:

- [ganache-cli](https://github.com/trufflesuite/ganache-core/releases/tag/v2.4.0)

## PS

Thank you for your amazing work truffle team et al.

**Comment by zachlysobey** [comment]
@davidmurdoch

**Comment by davidmurdoch** [comment]
Fixed! Thanks for pointing it out!
