### ISSUE TITLE
Websocket connection through ws:// doesn't work

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache-cli-archive#635]
Websocket connection only works with http://localhost:8545, is there any plans to support websocket connection through native ws:// protocol?

**Comment by davidmurdoch** [comment]
Thanks for taking the time to open the issue, @btenterprise2020!

Websocket connections should _not_ work over `http:` and they should be working over `ws:`. Can you explain the problem you are having in a little more detail?

**Comment by ghost** [comment]
I think I've confused with the default port of parity ( parity uses 8546 instead of 8545 ), also this documentation might cause a confusion https://gist.github.com/MagRelo/c9fe284d9e3ae44b4c941df646d0b7b8. Anyways, I am closing this issue now, thanks 👍
