### ISSUE TITLE
Send method events not being fired neither the promised resolved when automining

### ISSUE THREAD

**Issue by cnasikas** [ConsenSys-archive/ganache-cli-archive#643]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5cbf7156e416b84519cb7344

## Expected Behavior

Events of send function are emitted and promised is resolved when deploying a contract

## Current Behavior

I run ganache-cli with auto-mining on. When I deploy and send a contract the events of the send function are not emitted and the promise is not resolved. When I turn off auto-mining and set a block time interval (i.e. 1sec) the events are emitted and the promise is resolved.

## Steps to Reproduce (for bugs)

1. Create a contract. Code is irrelevant
2. Run `ganache-cli -a 10 -d -p 7545 -i 5777 -g 1 -e 10000000`
3. Deploy the contract with web3:

``` 
 // assume a compiled contract with solcjs or truffle.
const ABI = compiledContract.abi
const bytecode = compiledContract.evm.bytecode.object
const contract = new this.web3.eth.Contract(ABI)

const accounts = await this.web3.eth.getAccounts()
contract
 .deploy({ data: bytecode, arguments: args })
 .send({ from: accounts[0], gas: 1000000 })
 .once('transactionHash', (hash) => {
   console.log(hash)
 })
 .once('confirmation', (conf, res) => {
   console.log(conf, res)
 })
 .once('receipt', (receipt) => {
   console.log(receipt)
 })
 .once('error', err => console.log('err', err))
 .then((res) => {
   console.log('then', res)
 })


```

## Your Environment
* Version used: Ganache CLI v6.4.3 (ganache-core: 2.5.5)
* Version of Truffle/Remix/Other tools used: web3js 1.0.0-beta.52, solc 0.5.4
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x, [x] 10.x 
* Operating System and version (include distro if Linux): macOS Mojave 10.14.4
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by cnasikas** [comment]
I think that this is happening because web3js waits 24 confirmation to resolve the promise or emit the receipt event and 1 confirmation to emit the confirmation event. That's why the events are not emitted and the promised is not resolved

**Comment by hrishikeshio** [comment]
@cnasikas Thanks. it worked.
https://web3js.readthedocs.io/en/1.0/web3-shh.html#transactionconfirmationblocks

**Comment by cnasikas** [comment]
@hrishikeshio You are welcome! How did you manage to get it work ? I put `transactionconfirmationblocks` to zero but still I face the same problem.

**Comment by hrishikeshio** [comment]
@cnasikas I set transactionConfirmationBlocks to 1 and set ganache-cli to make block every second by using -b 1

**Comment by cnasikas** [comment]
I see. I thought you make it work with auto-mining on.

**Comment by bergkvist** [comment]
The reason is indeed that Web3 will by default wait for 24 confirmations before resolving, but ganache-cli will only give you one, causing it to hang indefinitely.

The easiest solution is to change options for web3 to only require one confirmation:

```javascript
const Web3 = require('web3')
const ganache = require('ganache-cli')
const web3 = new Web3(ganache.provider(), null, { transactionConfirmationBlocks: 1 /* This is the critical part */ })

// ... send your transaction using web3
```

**Comment by cnasikas** [comment]
> The reason is indeed that Web3 will by default wait for 24 confirmations before resolving, but ganache-cli will only give you one, causing it to hang indefinitely.
> 
> The easiest solution is to change options for web3 to only require one confirmation:
> 
> ```js
> const Web3 = require('web3')
> const ganache = require('ganache-cli')
> const web3 = new Web3(ganache.provider(), null, { transactionConfirmationBlocks: 1 /* This is the critical part */ })
> 
> // ... send your transaction using web3
> ```

That doesn't work if the auto mining is on. The problem is not that the confirmation blocks are set by default to 24 so you have to wait that long. The problem is that when you have the automining on the promise is not resolved and the events are not being fired because no extra block is mined on top of the block where the contract is deployed.

**Comment by bergkvist** [comment]
@cnasikas Wrong. This is exactly when it works. (with auto-mining being on). I know this is true because I tested it myself.

Maybe you are thinking that you will get 0 confirmations when auto-mining is on? This is wrong. The block that includes the transaction counts as the first confirmation. 

(Which is why requiring only one confirmation will allow the promise to resolve)

**Comment by cnasikas** [comment]
Would you mind posting how did you did it? I tried the following but it doesn't work:

**Ganache**:

`ganache-cli -a 10 -d -p 7545 -i 5777 -g 0 -e 10000000`

**Web3**:

```
const web3 = new Web3(new Web3.providers.WebsocketProvider(provider), null, { transactionConfirmationBlocks: 1 })
const contract = new web3.eth.Contract(ABI)
const instance = await contract.deploy({ data, arguments: args }).send({ from, gas: 2000000 }) // never resolves
```

**Comment by nicholasjpaterno** [comment]
@cnasikas, @bergkvist posted an example with ganache here: https://github.com/trufflesuite/ganache-cli/issues/644#issuecomment-497997629

**Comment by cnasikas** [comment]
@nicholasjpaterno The examples are not working in my case. Let's say that my contract is deployed in block number 10. The promise is not resolved despite having the `transactionConfirmationBlocks: 1`. When the block with number 11 is mined on top of block number 10 then the promised is resolved. In my case the next block is counted as the first confirmation block (I know that the first one should be the block where the transaction is mined). I cannot understand what I am doing wrong.

**Comment by nicholasjpaterno** [comment]
@cnasikas In your example. what is the `provider` variable?  It should be a string of the address to your local ganache instance, something like `ws://localhost:7545`. Is it possible that you're instantiating a new WebsocketProvider with a pre-existing ganache provider?

**Comment by cnasikas** [comment]
The `provider` variable is set to `ws://localhost:7545` (a string) and I do not provide a pre-existing ganache provider (object). @nicholasjpaterno Did you set the `transactionConfirmationBlocks: 1` and the promise resolves when deploying a contract ? Thanks a lot for your time!

**Comment by nicholasjpaterno** [comment]
@cnasikas, sorry for the delay!  I'm unable to reproduce this issue with WebsocketProvider, can you try downgrading your web 3 version to beta 37? https://github.com/ethereum/web3.js/releases/tag/1.0.0-beta.37

**Comment by cnasikas** [comment]
@nicholasjpaterno No worries! I tried to downgrading to beta 37 and is working! Not sure what is different in beta 52 & 53 that causes that behavior.
