### ISSUE TITLE
Deploy version 6.4.4-beta.0 to Docker Hub

### ISSUE THREAD

**Issue by zrubenst** [ConsenSys-archive/ganache-cli-archive#649]
Currently the most recent deployment to Docker Hub (https://hub.docker.com/r/trufflesuite/ganache-cli/builds) is v6.4.3, and in the past v6.4.3-beta.0 was deployed. Please deploy the current `beta` branch, which has the version 6.4.4-beta.0, to Docker Hub.

[x] I asked about this on [gitter](https://gitter.im/ConsenSys/truffle)
[x] Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5ced79679b50f63935434cfe

## Context

There is a bug with `ganache-core` with estimating gas fees that crashes ganache. This was fixed in the current beta for ganache-core which the beta for ganache-cli has updated to.

**Comment by davidmurdoch** [comment]
Docker builds are a completely automated process, and it looks like our docker account got unlinked from our github recently and has been unable to access our repositories. I've gone in and clicked the button in docker to enable github access again and things looks to be building now.

I've also enabled build failure email notifications so I can catch issues like this sooner.

Let me know if this new beta build works for you.

Thanks!
