### ISSUE TITLE
Add flag to run in unauthenticated mode

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#65]
Some users developing for clients (like MetaMask) that do the transaction signing have run into the confusing situation that they can _either_ ask MetaMask to sign a transaction, OR just submit the transaction, which succeeds on TestRPC, since it runs in authenticated mode.

It would be nice to disable the authenticated accounts, so devs can enforce that they're correctly signing code.

**Comment by tcoulter** [comment]
Wouldn't setting 0 accounts at startup work? `testrpc -a 0`?

**Comment by danfinlay** [comment]
But this still generates the mnemonic accounts and funds them?
- Dan

**Comment by tcoulter** [comment]
Nope. It generates no accounts.

**Comment by tcoulter** [comment]
Oh hmm. I see. You may the money but not the features. Where's the money
Lebowski???

Makes sense. Good feature.
On Apr 10, 2016 1:25 PM, "Dan Finlay" notifications@github.com wrote:

But this still generates the mnemonic accounts and funds them?
- Dan

**Comment by danfinlay** [comment]
I just want my rug back
- Dan

**Comment by benjamincburns** [comment]
Implemented. See the `--secure` flag.
