### ISSUE TITLE
Latest Docker image broken for contracts compiled with solc 0.5.5 or higher

### ISSUE THREAD

**Issue by petscheit** [ConsenSys-archive/ganache-cli-archive#650]
I've been running into invalid opcode errors when using the latest docker image (c75a27e) and using solc 0.5.5 or higher. Everything works when I compile with 0.5.4 or lower

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ x]

## Expected Behavior

When I compile my smart contract with solc 0.5.5 or higher, I should be able to call functions without getting invalid opcode errors, given that the compiler doesn't throw any errors.

## Current Behavior
When I compile with 0.5.4 or lower, I have no issues. 
When using 0.5.5 or higher, I don't get any compiler errors in remix, I am able to deploy the contract successfully to the ganache-cli docker image but when I call a function I get invalid opcode errors. 
What I find very confusing, is that when I run this locally (ganache-cli with version 0.4.3) the issues don't appear, even though the docker image uses the same version. 
## Steps to Reproduce (for bugs)

I'm using the following smart contract:
```
contract Test {
    uint public num = 0;
    
    function add() public {
        num += 1;
    }
}
```

1. Start docker container with: `docker run -p 8545:8545 trufflesuite/ganache-cli:latest`
2. Compile contract with solc 0.5.5 or higher
3. Deploy with web3 provider (http://localhost:8545)
4. Call add function

## Your Environment
* Version used: latest docker image (c75a27e)
* Version of Truffle/Remix/Other tools used: solc v0.5.5, remix v0.7.7

**Comment by BrendanChou** [comment]
Sounds like an EVM problem as I think the default EVM version for solidity 0.5.5+ is petersburg rather than byzantium. Try running ganache-cli with the flag `-k=petersburg` to solve the issue

**Comment by petscheit** [comment]
Well it works when using the npm package without any issues, but not when using the docker container. I checked the dockerfile but can't find anything that would explain this behaviour. A workaround is to use the :next version on dockerhub
