### ISSUE TITLE
Add a block lag feature

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#66]
Sometimes you want to test your app under real blockchain-type conditions, where transactions succeed, but the change isn't seen for up to 15 seconds.

Developers should have an easy way to experience that lag in development, so they can build their UI's around it.

It would be really great if `testrpc` provided a flag for lagging the block addition, to help this process.

**Comment by tcoulter** [comment]
Closing this in favor of #127, which consolidates a couple of discussions about this feature. Thanks!
