### ISSUE TITLE
Fully support eth_signTypedData RPC call (aka EIP712 signature) by allowing arrays

### ISSUE THREAD

**Issue by BrendanChou** [ConsenSys-archive/ganache-cli-archive#662]
Same example as here https://github.com/MetaMask/metamask-extension/issues/6106

Arrays currently unimplemented in encodeData in `eth_signTypedData` rpc call
To reproduce the error, run the following code:

```
TYPES =
{
	EIP712Domain: [
		{ name: "name",              type: "string"  },
		{ name: "version",           type: "string"  },
		{ name: "chainId",           type: "uint256" },
		{ name: "verifyingContract", type: "address" },
	],
	Entry: [
		{ name: "id",                 type: "address" },
		{ name: "value",              type: "uint256" },
	],
	Entries: [
		{ name: "content",            type: "Entry[]" },
	],
};
DOMAIN =
{
	name:              "test-domain",
	version:           "0.0.1",
	chainId:           await web3.eth.net.getId(),
	verifyingContract: 0,
};
wallet = "0x......."; // Your wallet address here
message = { content: [{ id: 0, value: 0 }] };
await web3.currentProvider.sendAsync({
	method: "eth_signTypedData",
	params: [ wallet, JSON.stringify({ types: TYPES, domain: DOMAIN, primaryType: "Entries", message: message }) ],
	from: wallet,
});
```

**Comment by BrendanChou** [comment]
Needs ganache-core to update to a newer package version. See more here
https://github.com/trufflesuite/ganache-core/issues/459

**Comment by BrendanChou** [comment]
Necessary change was made in ganache-core. Please update to ganache-core > 2.7.0 when it is released

**Comment by davidmurdoch** [comment]
2.7.0 is actually already released on npm, but I haven't yet published on GitHub due to some CI/CD issues in Ganache UI.

This change will _probably_ land in 2.8.0.

**Comment by davidmurdoch** [comment]
Closing as this is now supported by the latest cli beta. https://github.com/trufflesuite/ganache-cli/releases/tag/v6.7.0-beta.0 Thanks!
