### ISSUE TITLE
account_keys_path does nothing

### ISSUE THREAD

**Issue by Swader** [ConsenSys-archive/ganache-cli-archive#663]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: (https://gitter.im/ConsenSys/truffle?at=5d3871e3d6188741642d2698

## Expected Behavior

`account_keys_path` should create a file with account keys in target location. The location is a sister folder next to the folder where my database is, so it's not a write permission issue.

## Current Behavior

Nothing happens.

## Steps to Reproduce (for bugs)

Clone [Thundercloud](https://github.com/status-im/thundercloud) and run `node start.js` after installing deps with `yarn install`.

## Context

I'm trying to save private keys to a file. I cannot continue work effectively without this as I would have to hack rather heavily on it.

## Your Environment

* Version used:     "ganache-cli": "^6.5.0"
* Version of Truffle/Remix/Other tools used: /
* NodeJS Version: 10
* Operating System and version (include distro if Linux): Windows 10
* Link to your project or repro gist: https://github.com/status-im/thundercloud
* Commit hash to use with above link for reproduction: https://github.com/status-im/thundercloud/commit/2586615867427306b3afd601dbaed89579fbe814
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Hm. Looks like the option is named `acctKeys`, not `account_keys_path` like the documentation states (it _is_ named `account_keys_path` in ganache-core options, though).

I'll PR a fix for this right now! Thanks for bringing this to our attention!

**Comment by davidmurdoch** [comment]
PR: https://github.com/trufflesuite/ganache-cli/pull/664, waiting for review before merging into develop. This fix will mostly likely land in the next beta release of cli early next week!

Sorry for the headache this may have caused!

You can safely switch to using the `acctKeys` cli option, as it will continue to work for the foreseeable future.

**Comment by Swader** [comment]
@davidmurdoch thanks but I think I may have misrepresented the problem - I am using ganache-cli in nodejs, so:

```js
const startupOptions = {
	"mnemonic": process.env.mnemonic,
	"default_balance_ether": 1000000,
	"total_accounts": 1,
	"db_path": "./deploy/db",
	"acctKeys": "./deploy/keys/validators.json"
};
// ...
const ganache = require("ganache-cli");
const provider = new ethers.providers.Web3Provider(ganache.provider(startupOptions));
// ...
```

Neither `acctKeys` nor `account_keys_path` have any effect.

**Comment by davidmurdoch** [comment]
Hm, does the `./deploy/keys/` directory already exist?

**Comment by Swader** [comment]
Yup, and it's being populated by manual file writes just fine.

![image](https://user-images.githubusercontent.com/1430603/61883014-eabf3500-aef9-11e9-9f85-c0b969dd8eaa.png)

**Comment by davidmurdoch** [comment]
Turns out that the `account_keys_path` option isn't actually supported by `ganache-core`, only by usage via the cli (and currently only via `acctKeys`, though that is changing per PR #664). I'm moving the logic out from `ganache-cli` and into `ganache-core` so they will share this feature. Work in progress PR here: https://github.com/trufflesuite/ganache-core/pull/458 (I still need to write tests)

**Comment by Swader** [comment]
Roger that, thank you, commencing implementation of manual output of PKs.

**Comment by Swader** [comment]
@davidmurdoch What is the most painless way to get the private keys of the generated accounts? Is there a ganache-cli API that would let me do this? So I can manually export them... I'm also importing some third party ones by feeding them into the accounts object, wondering if there's a way to access them all at once like you do in that work-in-progress PR, but not during bootstrap, later.

**Comment by Swader** [comment]
Never mind, got it done with [hacks on hacks](https://github.com/status-im/thundercloud/blob/master/start.js), works 👌

**Comment by davidmurdoch** [comment]
Glad you found a solution. BTW, this doesn't look hacky to me, but seems to be intended use of Ganache's advanced options that you can expect to continue to work.

I'm going to try to get a beta out with the above PR later today.
