### ISSUE TITLE
[Ganache CLI 6.8.1] `eth_sendRawTransaction` Not Working For Signed Transactions

### ISSUE THREAD

**Issue by nlordell** [ConsenSys-archive/ganache-cli-archive#706]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

`eth_sendRawTransaction` does not seem to be accepting signed transactions with the node's chain ID. It only seems to accept signed transactions with chain ID of `1` despite of what `eth_chainId` call returns (hardcoded to `1337` as far as I can tell). The error message also seems to suggest that the signature V-value is being verified for the wrong chain ID:
```
Error: Incompatible EIP155-based V 2710 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
```

In the previous Docker image version of `v6.7.0` any V-value was accepted.

I only tested this on the Docker image.

## Steps to Reproduce

1. First start a Docker container with Ganache v6.8.1 (latest) with the deterministic mnemonic:
  ```sh
docker run -p 8545:8545 docker.io/trufflesuite/ganache-cli:v6.8.1 --deterministic
  ```
2. Install some needed NPM dependencies:
  ```sh
npm install ethereumjs-tx node-fetch
  ```
2. Then run the JavaScript code from the following gist to send some raw transactions: https://gist.github.com/nlordell/c2c8681e716c04c71c35a14ba3045e68

## Expected Behavior

The included script should output:
```
=== Signing and sending for chain ID: 1337 ===
Nonce: 0x0
V-value: 2710
Raw tx: 0xf86d8084ffffffff82520894ffcf8fdee72ac11b5c542428b35eef5769c409f0880de0b6b3a764000080820a96a01c4399c5fbc655e3d804b60e8163d6558b1fab10881c18adfe544b9855c6f056a008c7202d4c3ad0d31b9147317936a7dbe1fcd68ab3d85d855c78912058d067c6
Success: 0x642fa0ae49b84ed3cc6f63b83ea65bb212745dec1c120cfb9a27ad7b7042b409
=== Signing and sending for chain ID: 1 ===
Nonce: 0x1
V-value: 38
Raw tx: 0xf86b0184ffffffff82520894ffcf8fdee72ac11b5c542428b35eef5769c409f0880de0b6b3a76400008026a07ebdb0885c67f9cf14a5092c96573f7d52e82a5b0bd3e97fe1b20a27a242b946a04f15185592fe467b234bb8d9dab07828e4ed87e2fa52639fd6d92804ab70f5db
Error: Error: Incompatible EIP155-based V 38 and chain id 1337. See the second parameter of the Transaction constructor to set the chain id.
``` 

## Current Behavior

```
=== Signing and sending for chain ID: 1337 ===
Nonce: 0x0
V-value: 2710
Raw tx: 0xf86d8084ffffffff82520894ffcf8fdee72ac11b5c542428b35eef5769c409f0880de0b6b3a764000080820a96a01c4399c5fbc655e3d804b60e8163d6558b1fab10881c18adfe544b9855c6f056a008c7202d4c3ad0d31b9147317936a7dbe1fcd68ab3d85d855c78912058d067c6
Error: Error: Incompatible EIP155-based V 2710 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
=== Signing and sending for chain ID: 1 ===
Nonce: 0x0
V-value: 37
Raw tx: 0xf86b8084ffffffff82520894ffcf8fdee72ac11b5c542428b35eef5769c409f0880de0b6b3a76400008025a0b7388aaf3c247d0e5bacd0aad8fef9bb349543fe81ca0c4add8872a3f278fb20a03618ee17d0218c07d6c78714e5dbf9e7db49ba4e233ffd375b149249d97e32ce
Success: 0xa5aff49fedd9db1f1150d65805f68b5c24f2e14ec7c72ab2fab1a36958b45e8d
``` 

## v6.7.0 Behaviour

```
=== Signing and sending for chain ID: 1337 ===
Nonce: 0x0
V-value: 2710
Raw tx: 0xf86d8084ffffffff82520894ffcf8fdee72ac11b5c542428b35eef5769c409f0880de0b6b3a764000080820a96a01c4399c5fbc655e3d804b60e8163d6558b1fab10881c18adfe544b9855c6f056a008c7202d4c3ad0d31b9147317936a7dbe1fcd68ab3d85d855c78912058d067c6
Success: 0x642fa0ae49b84ed3cc6f63b83ea65bb212745dec1c120cfb9a27ad7b7042b409
=== Signing and sending for chain ID: 1 ===
Nonce: 0x1
V-value: 38
Raw tx: 0xf86b0184ffffffff82520894ffcf8fdee72ac11b5c542428b35eef5769c409f0880de0b6b3a76400008026a07ebdb0885c67f9cf14a5092c96573f7d52e82a5b0bd3e97fe1b20a27a242b946a04f15185592fe467b234bb8d9dab07828e4ed87e2fa52639fd6d92804ab70f5db
Success: 0x371fb67fc30dbc63ee3f5a9fa57cb590d7df7c805e659f5ffe59188aef99dd62
```

## Your Environment
* Docker Image Version used: 6.8.1
* NodeJS Version (only for sample script): [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x, [x] 10.x
* Operating System and version (include distro if Linux): Ubuntu 18.04
* Commit hash to use with above link for reproduction: https://gist.github.com/nlordell/c2c8681e716c04c71c35a14ba3045e68
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Sorry you're running into this issue! What is happening here is that ganache previously used ethereumjs-vm's default internal chain id, which was `1`, while we simultaneously hard coded `eth_chainId` to `1337`, as you've noticed.

When we updated `ethereumjs-vm` to add `istanbul` support we now needed to specify our own `chain_id` when initializing the vm. For legacy reasons we chose to keep the chain id set to `1`, even though eth_chainId was returning `1337` (which we also kept for legacy reasons).

I'll try to expedite a major version release to correct these past inaccuracies.

I'll also look into the feasibility of a workaround that accepts both chainId `1` and `1337` as `6.7.0` as valid (as was previously the case).

**Comment by nlordell** [comment]
Ah makes sense. Thanks for looking into this!

**Comment by michael1011** [comment]
Is fixed in `v6.8.2` @davidmurdoch!

**Comment by nicholasjpaterno** [comment]
Fixed in https://github.com/trufflesuite/ganache-core/pull/532

**Comment by klipa-dev** [comment]
Is it possible that this is still a problem when trying to fork mainnet node? 

version:
Ganache CLI v6.9.1 (ganache-core: 2.10.2)

Steps to reproduce:
1. Start ganache: 
`ganache-cli -f https://mainnet.infura.io/v3/<secret>`
2. Try to call some static method to confirm everything is fine (this should work)
3. Try sending raw transaction, for example:
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["<rawTransaction>"],"id":1, "networkId":1, "chainId":1337}' http://localhost:8545
```


Error trace
```
{"id":1,"jsonrpc":"2.0","error":{"message":"Missing required chain parameter: networkId","code":-32000,"data":{"stack":"Error: Missing required chain parameter: networkId
    at e.setChain (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:78974)
    at new e (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:78232)
    at Function.e.forCustomChain (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:78404)
    at S.queueRawTransaction (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:203311)
    at p.eth_sendRawTransaction (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:193695)
    at p.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:190541)
    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:52700)
    at n.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:188823)
    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:52700)
    at f.s.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:169286)
    at f.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:167096)
    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:52700)
    at o.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:175350)
    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:52700)
    at n.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:174795)
    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:37:52700)","name":"Error"}}}
```

**Comment by nlordell** [comment]
There are way to many Ni[ck]s for one thread to handle!

**Comment by mt-bt** [comment]
+1, I am having the same issue as @nklipa13

**Comment by adrianmcli** [comment]
I had a similar issue, turns out you need to set the network ID to 1 when you start ganache.

**Comment by BlinkyStitt** [comment]
Just ran into this. The error saying "Missing required chain parameter" was confusing. Could it be changed to say "Incorrect chain parameter. Expected X. Received Y".

I got a little lost trying to figure this out since the docs (https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendrawtransaction) didn't mention anything about the id.

Doing `ganache-cli ... --fork ... --chainId 1` works for now

**Comment by davidmurdoch** [comment]
This is a bug in `ganache-core`'s forking mode, you shouldn't have to use the `--networkId` flag for it to work (`--chainId` isn't a flag ganache-cli supports yet). I'll fix this in an upcoming release!
