### ISSUE TITLE
VM Error for generic calls don't propagate

### ISSUE THREAD

**Issue by mhhf** [ConsenSys-archive/ganache-cli-archive#71]
Let A, B be two contracts. A has an instance of B and B has a function that throws (`function gothrow(){ throw; }`). If this function is called via solidity interface (e.g. `b.gothrow()`) the error is propagated to the caller (A) and results in an overall throw of the transaction. If the function is called in a generic way (`address(b).call(bytes4(sha("gothrow()")));`) an error in B is thrown but **NOT** propagated and the calling function proceeds with its transaction!

I suppose this is not the expected behavior.

An minimal example with truffle/ testrpc and a detailed error description can be found here: https://github.com/mhhf/testrpc_error_propagation

**Comment by tcoulter** [comment]
This is best answered by @wanderer. @wanderer: Should the correct behavior be to propagate the throw?

@mhhf Have you tested this against geth first to see how it responds?

**Comment by mhhf** [comment]
Hmm, just tested it on morden and it shows the same behavior.
Sorry, should have done it before opening an issue.

Closing this since it's not an testrpc issue .

**Comment by axic** [comment]
@mhhf maybe you want to open an issue on ethereum/solidity with two code samples?

**Comment by mhhf** [comment]
@axic: I've talked to chris about this. Not propagating errors by a call statement is the expected behavior: Call returns a boolean indicating if the call was successful or not, mirroring the call opcode. One has to catch errors manually and propagate them:

```
if( !address(b).call(bytes4(sha("gothrow()"))) ) throw;
```
