### ISSUE TITLE
Add method for fast-forward account nonce

### ISSUE THREAD

**Issue by thegostep** [ConsenSys-archive/ganache-cli-archive#714]
Right now - the only way to increment an account nonce is create a loop that sends transactions. This is very slow. Would be great to have method where we can skip forward to an arbitrary nonce.

https://github.com/trufflesuite/ganache-core/issues/524

**Comment by krzkaczor** [comment]
You might want to check out Deth - https://github.com/ethereum-ts/deth it has a flag to ignore nonce errors (perfect to test with Metamask).

**Comment by davidmurdoch** [comment]
Tracking this in trufflesuite/ganache-core#589
