### ISSUE TITLE
[WSL] EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by juharris** [ConsenSys-archive/ganache-cli-archive#718]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]
* Link to my question on gitter: 

## Expected Behavior
`ganache-cli` should start.

## Current Behavior
`ganache-cli` does not start.
It did work fine in version `6.5.1`.
## Possible Solution
Use a module like `mv`: https://github.com/andrewrk/node-mv as suggested in https://stackoverflow.com/a/43206506/1226799

## Steps to Reproduce (for bugs)
In WSL:
```bash
$ npx ganache-cli --db blockchain_db
Ganache CLI v6.9.0 (ganache-core: 2.10.1)
Error: EXDEV: cross-device link not permitted, rename '/tmp/tmp-1580wcSrmVw2vfps' -> 'blockchain_db/!trie_db!0x41c488877f4bd7f076e7a46574f86eb2e58bb101aad9fd4da0dbf9b60ec8c949'
```

`npx ganache-cli` does work fine.
So does: `mkdir --parents ~/blockchain_db && npx ganache-cli --db ~/blockchain_db/`

## Context
I'm trying to start a database and sometimes need to use it later with the same state.

## Your Environment
* Version used: Ganache CLI v6.9.0 (ganache-core: 2.10.1)
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: v10.17.0
* Operating System and version (include distro if Linux): WSL, Ubuntu 18.04.3 LTS
* Link to your project or repro gist: https://github.com/microsoft/0xDeCA10B
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ] I might.

**Comment by juharris** [comment]
Looks like this is already reported in https://github.com/trufflesuite/ganache/issues/1617
and should be corrected by https://github.com/trufflesuite/ganache-core/pull/548

**Comment by davidmurdoch** [comment]
Yup (closing since this is a duplicate)! We're smoketesting the release today and will release a new version soon.
