### ISSUE TITLE
Unable to install testrpc in Windows 2012 R2

### ISSUE THREAD

**Issue by moinakbh** [ConsenSys-archive/ganache-cli-archive#72]
Hi,
I am trying to install ethereumjs-testrpc in Windows 2012 R2 64-bit OS machine and getting the following error, any help will be greatly appreciated. The PATH env variable has git, python etc. 2.7.11 is the python version that I got from anaconda. 
Thanks,

--------- ERROR ---------------------------
24837 verbose lifecycle secp256k1@3.0.1~install: CWD: C:\Users\119078\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
24838 silly lifecycle secp256k1@3.0.1~install: Args: [ '/d /s /c', 'npm run rebuild' ]
24839 silly lifecycle secp256k1@3.0.1~install: Returned: code: 1  signal: null
24840 info lifecycle secp256k1@3.0.1~install: Failed to exec install script
24841 verbose unlock done using C:\Users\119078\AppData\Roaming\npm-cache_locks\staging-179b54b46d2bd924.lock for C:\Users\119078\AppData\Roaming\npm\node_modules.staging
24842 silly rollbackFailedOptional Starting
24843 silly rollbackFailedOptional Finishing
24844 silly runTopLevelLifecycles Starting
24845 silly runTopLevelLifecycles Finishing
24846 silly install printInstalled
24847 verbose stack Error: secp256k1@3.0.1 install: `npm run rebuild`
24847 verbose stack Exit status 1
24847 verbose stack     at EventEmitter.<anonymous> (C:\Users\119078\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
24847 verbose stack     at emitTwo (events.js:100:13)
24847 verbose stack     at EventEmitter.emit (events.js:185:7)
24847 verbose stack     at ChildProcess.<anonymous> (C:\Users\119078\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
24847 verbose stack     at emitTwo (events.js:100:13)
24847 verbose stack     at ChildProcess.emit (events.js:185:7)
24847 verbose stack     at maybeClose (internal/child_process.js:850:16)
24847 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
24848 verbose pkgid secp256k1@3.0.1
24849 verbose cwd C:\Users\119078
24850 error Windows_NT 6.3.9600

**Comment by IamSandipC** [comment]
I could install it successfully in win 2012 R2. If anyone is facing problem here are the steps
1. Make sure you have .Net 2.0 (Because MSBuils 2.0 is used).. Add the feature in the windows server to install .Net 3.5 (that inclueds 2.0)
2. You need C++ build tool as well.. There are many suggestion in different forums to install Visual Studio community / express for this. Actually you do not need to install complete VS. Just install Microsoft Visual C++ Build Tools 2015 which is only one component of VS.
3. Next install test rpc with the option --msvs_version=2015

Hope this helps.

**Comment by dgoswami75** [comment]
Facing a problem with Win8 x64 install. I have Visual Studio Express already. Following the windows install instructions, I got Python 2.7.11 and OpenSSL successfully installed, but get this error when I do npm install -g for testrpc:

C:\WINDOWS\system32>npm install -g ethereumjs-testrpc
npm ERR! git clone C:\Users\dhgoswami\AppData\Roaming\npm-cache_git-remotes\git
-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-6f2
958aa C:\Users\DHGOSW~1\AppData\Local\Temp\npm-13176-cbb86290\git-cache-1cd29a87
\94d7146671b9719e00a09c29b01a691bc85048c2: Cloning into 'C:\Users\DHGOSW~1\AppDa
ta\Local\Temp\npm-13176-cbb86290\git-cache-1cd29a87\94d7146671b9719e00a09c29b01a
691bc85048c2'...
npm ERR! git clone C:\Users\dhgoswami\AppData\Roaming\npm-cache_git-remotes\git
-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-6f2
958aa C:\Users\DHGOSW~1\AppData\Local\Temp\npm-13176-cbb86290\git-cache-1cd29a87
\94d7146671b9719e00a09c29b01a691bc85048c2: **error: cannot spawn sh: No such file
or directory**
npm ERR! git clone C:\Users\dhgoswami\AppData\Roaming\npm-cache_git-remotes\git
-github-com-debris-bignumber-js-git-94d7146671b9719e00a09c29b01a691bc85048c2-6f2
958aa C:\Users\DHGOSW~1\AppData\Local\Temp\npm-13176-cbb86290\git-cache-1cd29a87
\94d7146671b9719e00a09c29b01a691bc85048c2: **fatal: unable to fork**

Any ideas are greatly appreciated...

**Comment by tcoulter** [comment]
@dgoswami75 Interesting. Can you using git bash on Windows? https://git-for-windows.github.io/

**Comment by dgoswami75** [comment]
Cool.. That did it. :) Thanks for the suggestion.

**Comment by jmdfm** [comment]
Closing, seems to be resolved
