### ISSUE TITLE
Ganache not respecting the --port option.

### ISSUE THREAD

**Issue by palkeo** [ConsenSys-archive/ganache-cli-archive#722]
##  Expected Behavior

> $ ganache-cli --fork http://my-node:8545 --port 8545

Should listen to port 8545.

## Current Behavior

Listen to port 8546.

> Listening on 127.0.0.1:8546

Which doesn't make sense, I explicitly specify "--port 8545" so it should use it.
The --fork option uses the same port, but this node is on a remote machine, it's absolutely fine.

## Possible Solution

Remove this block of code:
https://github.com/trufflesuite/ganache-cli/blob/develop/cli.js#L106-L120

Or at least, make it check that the hostname is "127.0.0.1".

## Context

This is caused a tool build no top of ganache-cli to crash, because it's passing "--port 8545", so it expect it to listen to that port. It's very counter-intuitive to have it fiddle with that port that was explicitly passed (but only when an unrelated option is passed in…).

**Comment by davidmurdoch** [comment]
Oh wow. Great catch! Do you mind putting removing this block of code and putting in a PR?

**Comment by palkeo** [comment]
Done.
I think another option would be to only do it if the host for the --fork option and the one to listen to are the same.
But personally, I think it's better to not silently fiddle with the port at all: better to have it stop because the port is already taken (which would be the case if you don't use --fork anyway!).
