### ISSUE TITLE
gas estimation about tests on Ganache forked mainnet

### ISSUE THREAD

**Issue by cmli93** [ConsenSys-archive/ganache-cli-archive#727]
I come up with this solution with gas estimation. Could someone help check whether it is feasible?

If we want to send a transaction, first, we just fork the newest mainnet blockchain using ganache-cli fork. Then we send the transaction to local forked chain with intended input, and we can get the gasUsed after this transaction succeeds.

Is this gasUsed the same as the cost for trans sent to mainnet?

The link below found they are different. But do someone know why this happens? Or what the difference between forked mainnet with actual mainnet?
[https://ethereum.stackexchange.com/questions/68960/why-does-my-private-network-transaction-use-a-different-amount-of-gas-than-my-ma?rq=1](url)

**Comment by nicholasjpaterno** [comment]
@cmli93 Great question!

Unfortunately, that solution won't account for things like the "all but one 64th" rule where extra gas is withheld during certain operations in the VM (see: these release notes https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4 or EIP 150 for more info).  In other words, sometimes you need more gas available for a successful transaction then is actually needed by the VM.

Your best bet is to use `eth_estimateGas`.  One thing to keep in mind is that the state of the blockchain can change in between the time you get your estimate and the time you send the transaction - this too can cause your estimate to be inaccurate or the transaction to fail outright.

I'm going to close this issue for now, please reopen if you believe this was closed in error!

**Comment by cmli93** [comment]
Dear Sir, thank you very much

**Comment by cmli93** [comment]
Could you please give me some hint about the difference between the forked mainnet and the actual mainnet? @nicholasjpaterno

**Comment by nicholasjpaterno** [comment]
@cmli93 Anytime! There shouldn't be a difference if you've forked mainnet and ran your estimate.  However, if the state on the main chain has changed your estimate may no longer be accurate on that chain.
