### ISSUE TITLE
Wrong Blockhash in transaction receipt

### ISSUE THREAD

**Issue by IamSandipC** [ConsenSys-archive/ganache-cli-archive#73]
I created a transaction by calling a function in a contract. The contract function writes an event. All these were done from web3 against TestRPC running at localhost. After the transaction is added to network, I call the following : 
web3.eth.getTransactionReceipt(tx, function (err,objTx) {
                    if (objTx != null) {
                        console.log(objTx.log);
                    }
                })
It returns the receipt with the event data in the log. But the blockhas in the transation receipt and the blockhash inside the log is different. Should be same.

**blockHash: "0x4a9cfaee8eb83857eac751ec87b529a1557fdbaf7e665cf19267da1593ef9daa"**
blockNumber: 60
contractAddress: null
cumulativeGasUsed: 182322
gasUsed: 182322
logs: Array[1]
0: Object
address: "0x4c5a0ef079f1b71227e3281f7e735e9261523e26"
**blockHash: "0x9af250903bb2431be098e4bd77c1146730a8882d1801f298385a360f0c4c8d24"**
blockNumber: 60
data: "0x000000000000000000000000083ce37b3f31d51821a3996ae4d4cad87635774200000000000000000000000000000000000000000000000000000000000001bc0000000000000000000000000000000000000000000000000000000000000036"
logIndex: 0
topics: Array[1]
transactionHash: "0x6b1790ade62f1213ccef43395dab3c6c897e6a73f71b2ecd71f9f8906f62b472"
transactionIndex: 0
type: "mined"
**proto**: Object
length: 1
**proto**: Array[0]
transactionHash: "0x6b1790ade62f1213ccef43395dab3c6c897e6a73f71b2ecd71f9f8906f62b472"
transactionIndex: 0

**Comment by tcoulter** [comment]
Interesting bug. Thanks!

**Comment by tcoulter** [comment]
Fixed. Version 2.0.4 released. Thanks!
