### ISSUE TITLE
Add `net_version` method.

### ISSUE THREAD

**Issue by danfinlay** [ConsenSys-archive/ganache-cli-archive#75]
Over at Metamask, we're adding a feature to provide blockchain-explorer links for transactions.

To do this intelligently, we have to check what blockchain we're on.

The `net_version` method lets a web3 client ask what blockchain version is being used. Main net returns `1`, the morden test-net returns `2`, and `testrpc` throws an error:

```
├─ id: 1
├─ jsonrpc: 2.0
└─ error
   ├─ message: Error: RPC method net_version not supported.
```

I think it would be cool to support this method, and just return something, like maybe a large random number, or maybe the string `testrpc`.  Something useful.

Thoughts?

**Comment by tcoulter** [comment]
Good idea. How about the number created from `new Date().getTime()`, run on startup? Therefore, each new instance of the TestRPC would have a new net_version.

**Comment by tcoulter** [comment]
Say the word and I'll implement it right now. :)

**Comment by danfinlay** [comment]
I think that’d be fine!

**Comment by tcoulter** [comment]
@flyswatter Added and pushed to npm v2.0.5.

**Comment by danfinlay** [comment]
Sweeet!  Thanks!!
