### ISSUE TITLE
Setting the domain isn't possible anymore ?

### ISSUE THREAD

**Issue by ffmad** [ConsenSys-archive/ganache-cli-archive#77]
Hi !

I've installed the latest version of testrpc and seen that the -d option, which was there to set the domaine to something else than localhost, is now used for generating deterministic addresses.

As I need to put my server address, I can't work with this new version

Is there a new command to set the domain ?

**Comment by tcoulter** [comment]
Is this still an issue for you? My impression is that with node, this is not needed. If you run the TestRPC on your server, it'll open the port. There should be no need to set the domain.

If I'm wrong and this is still an issue, please reopen.
