### ISSUE TITLE
ganache-cli not getting installed on Ubuntu

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache-cli-archive#777]
I am getting the following error while trying to install npm install ganache-cli
```
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/ganache-cli failed, reason: connect ENETUNREACH 2606:4700::6810:1323:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rahul/.npm/_logs/2020-08-15T08_50_50_947Z-debug.log
```

I executed the following commands in order.

```
sudo snap install node --classic
sudo npm install -g ganache-cli

```

## Environment
OS : Xubuntu 20.04
Solidity version used : 0.4.24
Node js version 12.18.3
npm version : 6.14.6

**Comment by ghost** [comment]
Okay, I have resolved it by doing the following.
`npm config set registry http://registry.npmjs.org/`

**Comment by davidmurdoch** [comment]
Just FYI: you should (almost) NEVER install anything from npm with sudo.
