### ISSUE TITLE
console access

### ISSUE THREAD

**Issue by gskerry** [ConsenSys-archive/ganache-cli-archive#78]
Hello, 
Is there a native console interface? 
If no, is there a way to expose node to geth console? So far: 
$ geth attach localhost:8545
"Unable to attach to geth node - Invalid endpoint"
(Have tried all the variants of the url I can think of).

If it's supposed to be possible, is host potentially the issue? Possible to set host? (i.e. issue #51, #77)

Thanks for your help!

**Comment by Janaka-Steph** [comment]
Please answer this issue!

**Comment by jmdfm** [comment]
@Janaka-Steph The author of this issue closed it on Apr 29th. If you have a question or issue please submit a new Issue that specifically deals with your question.

**Comment by karelstriegel** [comment]
@Janaka-Steph 
Assuming you have the testrpc running you can attach via geth to the console via 

`geth attach http://localhost:8545`

![image](https://user-images.githubusercontent.com/6882032/29551343-8e47958a-8712-11e7-9bf3-c04d693a84ca.png)
