### ISSUE TITLE
eth_getTransactionCount returns an incorrect value

### ISSUE THREAD

**Issue by thekevinbrown** [ConsenSys-archive/ganache-cli-archive#781]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5f56d3c989cf2d584ba44027

## Expected Behavior

Expected eth_getTransactionCount return value to be able to be used as a nonce in subsequent transactions.

## Current Behavior

```
TXRejectedError: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 4
    at validateNonce ([project directory]/node_modules/ganache-core/lib/statemanager.js:1010:11)
    at [project directory]/node_modules/ganache-core/lib/statemanager.js:1019:7
    at [project directory]/node_modules/ganache-core/lib/blockchain_double.js:444:5
    at [project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:77:5
    at [project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at Object.return ([project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:485:9)
    at processNode ([project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:288:30)
    at processNode ([project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:521:5)
    at [project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at [project directory]/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

## Possible Solution

Unsure

## Steps to Reproduce (for bugs)

I can create a script to reproduce this if necessary, just let me know.

## Context

This is currently blocking us from using ganache as a testing environment locally.

## Your Environment
* Version used: ganache-core@2.11.2
* Version of Truffle/Remix/Other tools used: @nomiclabs/buidler-ganache@1.3.3
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x, [x] 12.x
* Operating System and version (include distro if Linux): OS X 10.15.6
* Link to your project or repro gist: 
* Commit hash to use with above link for reproduction: 
* I intend to submit a pull request to fix this issue: [ ] (If I know where the problem is I may be able to help, just not very familiar with the codebase or why this is happening.)

**Comment by thekevinbrown** [comment]
After extensive debugging, this was on our side. It's still strange that ganache insists on sequential nonces, unlike normal clients, but that's likely intended behaviour for some reason, so I'll close this issue. Sorry for the noise!

**Comment by davidmurdoch** [comment]
Thanks for following up on this, @thekevinbrown! (and sorry I didn't reply sooner)

Yes, you are correct that Ganache doesn't support non-sequential nonces (or pending transactions/blocks). However, it will fully support it in the next major release!
