### ISSUE TITLE
scrypt optional dependency

### ISSUE THREAD

**Issue by alcuadrado** [ConsenSys-archive/ganache-cli-archive#785]
Hey @davidmurdoch,

As you probably know, we are working with Tenderly (/cc @nebojsa94 ) to migrate the Ethereum ecosystem away from native dependencies that need to be recompiled when you install them. 

Most of this work is ready, and we are now waiting for new versions of `ganache-core` and `ganache-cli`, but we just noticed that `scrypt` is now an optional dependency of `ganache-cli`.

We wonder if this dependency can be reconsidered/removed. It won't prevent your users to use ganache without a compiler, but it will degrade the installation speed.  

As `scrypt` has been deprecated for two years and fails to install in most modern node versions, I believe most of your users are actually using the js version, so this change shouldn't have a big impact.

If using a javascript version of this function is a no go, we can also help with that.

Thanks!

**Comment by davidmurdoch** [comment]
Merged. Thanks!
