### ISSUE TITLE
How can I determine right ganache instance?

### ISSUE THREAD

**Issue by sfl0r3nz05** [ConsenSys-archive/ganache-cli-archive#799]
Hi, I have deployed a ganache-cli on docker. In addtion, I have deployed the smart contract successfully through truffle migrate, however when I try to access from the application a new instance is generated even though I define correctly the mnemonic and the network id. 

## Expected Behavior

The expected behavior is that when emitting a transaction, the number of blocks increases, for example to 5.
![image](https://user-images.githubusercontent.com/6643905/97695055-bdb9e480-1aa3-11eb-8b19-61f8dfb058f8.png)

## Current Behavior

In the following images you can see how when the application is launched (via postman) a transaction is executed, but generating the block Number 1, while ganache once the contract is deployed is in block 4.

Node App behavior:
![image](https://user-images.githubusercontent.com/6643905/97692582-3e76e180-1aa0-11eb-9684-82503a5ddbb9.png)

Ganache behavior:
![image](https://user-images.githubusercontent.com/6643905/97692480-1ab39b80-1aa0-11eb-83fe-f6dc2596e680.png)

I have passed both: mnemonic and network id (determined when contract was deployed)
`const provider = ganache.provider({mnemonic: process.env.GANACHE_CLI, network_id: process.env.NETWORK_ID});`

I have also passed smart contract address:
`const contract_address = process.env.CONTRACT_TRUST_ANCHOR;`

![image](https://user-images.githubusercontent.com/6643905/97693365-5bf87b00-1aa1-11eb-8205-b6fc4a09c66e.png)
![image](https://user-images.githubusercontent.com/6643905/97693390-6450b600-1aa1-11eb-8736-3d059d3f4f8f.png)

Docker environment is set to true in docker-compose
![image](https://user-images.githubusercontent.com/6643905/97693483-86e2cf00-1aa1-11eb-9cc8-87361ce5fe36.png)

Network definition in truffle-config.js
![image](https://user-images.githubusercontent.com/6643905/97694627-2a80af00-1aa3-11eb-875b-b3a597defdbd.png)

## Possible Solution

I think it might be a matter of missing some of the options defined for [ganache-cli](https://hub.docker.com/r/trufflesuite/ganache-cli/)

## Your Environment
* Version used: "ganache-cli": "^6.12.1", "ganache-core": "^2.13.1",
* Version of Truffle/Remix/Other tools used: truffle": "^5.1.50"
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x, [x] 13.x
* Operating System and version (include distro if Linux): Ubuntu 18.04
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Hey, so the following code creates a javascript client only (without the webserver). Perhaps that's the issue?

```javascript
const provider = ganache.provider({mnemonic: process.env.GANACHE_CLI, network_id: process.env.NETWORK_ID});

```

If you want to launch via docker you'll need to pass ganache-cli options through the docker container. See: https://github.com/trufflesuite/ganache-cli#docker

**Comment by sfl0r3nz05** [comment]
Hey @davidmurdoch,

To deploy successfully ganache on docker-compose, I recommend this configuration:
![image](https://user-images.githubusercontent.com/6643905/99683407-9c379180-2a80-11eb-844f-ad10ca280087.png)

To interact with ganache, i recommend to use websocket to recover events:

const Web3 = require("web3");
const web3 = new Web3(`ws://${process.env.HOST_PROVIDER_GANACHE}:${process.env.PORT_PROVIDER_GANACHE}`);

Also it works with http, however, this configuration it is not able to decode events.
