### ISSUE TITLE
Events don't work

### ISSUE THREAD

**Issue by barkthins** [ConsenSys-archive/ganache-cli-archive#8]
I get the following error in a web3 watch() callback for an solidity event, where I'm listening on a specific event.  The code works on geth.

```
[Error: Method not found]
```

I read in other in other simulators that events aren't supported but it doesn't say so explicitly in the README here.

If events aren't supported, what's the alternative to getting transaction logs? It appears that web3's default log gathering capability is via events.

**Comment by kumavis** [comment]
@barkthins logs can be supported but they are not implemented currently

**Comment by kumavis** [comment]
we could take some of the provider-engine stuff and reuse it perhaps

**Comment by tcoulter** [comment]
@barkthins Events are now supported and will be included in the next release.

**Comment by barkthins** [comment]
Awesome!  thanks!
