### ISSUE TITLE
Windows install wiki page missing solc and /tmp

### ISSUE THREAD

**Issue by JeffreyBPetersen** [ConsenSys-archive/ganache-cli-archive#80]
Manager.prototype.eth_compileSolidity was failing before doing the following:

Create a "tmp" directory at the root of your default drive.
Add the directory containing "solc.exe" to your path. The binary is available in [the latest webthree-umbrella release](https://github.com/ethereum/webthree-umbrella/releases).

**Comment by jmdfm** [comment]
Updated the wiki with these instructions, thanks @JeffreyBPetersen 

https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows
