### ISSUE TITLE
Extra bytes returned on revert("")

### ISSUE THREAD

**Issue by ZumZoom** [ConsenSys-archive/ganache-cli-archive#800]
Calling `revert(string)` in Solidity should return abi-encoded string as if it were a call to `Error(string)` function ([docs](https://solidity.readthedocs.io/en/latest/control-structures.html#revert)).

Therefore when calling revert with empty string `revert("")` I expect to receive correct abi-encoded `Error("")`: 
```
0x08c379a0                                                          <- Error(string) selector
0000000000000000000000000000000000000000000000000000000000000020    <- string offset = 32
0000000000000000000000000000000000000000000000000000000000000000    <- string length = 0
```

However ganache-cli appends extra 32 bytes of zeroes in that case and returned bytes are
```
0x08c379a0                                                          <- Error(string) selector
0000000000000000000000000000000000000000000000000000000000000020    <- string offset = 32
0000000000000000000000000000000000000000000000000000000000000000    <- string length = 0
0000000000000000000000000000000000000000000000000000000000000000    <- unexpected extra 32 bytes
```

Those extra zeroes break the code that relies on the size of abi-encoded string.

## Expected Behavior

`Error("")` should be abi-encoded as 68 bytes.

## Current Behavior

`Error("")` is abi-encoded as 100 bytes.

## Steps to Reproduce

```
contract RevertReasonParserTest {
    function emptyStringRevert() external pure  {
        revert("");
    }

    function test() external view {
        try this.emptyStringRevert() {
        } catch (bytes memory reason) {
            require(reason.length == 68, "Incorrect reason length");
        }
    }
}
```

## Your Environment
* Version used: 6.12.1

**Comment by axic** [comment]
Can you open the same issue on https://github.com/ethereum/solidity? It seems to be belonging there and not here. (Also confirming this is happening.)

**Comment by ZumZoom** [comment]
Sure. Thanks for suggestion.
https://github.com/ethereum/solidity/issues/10170
I also checked that the behaviour is consistent with mainnet, ropsten and ethereumjs-vm.
It is likely a Solidity bug so I'm closing the issue.
