### ISSUE TITLE
Ganache-cli Fork hang on net_version

### ISSUE THREAD

**Issue by Madeindreams** [ConsenSys-archive/ganache-cli-archive#809]
When I try to fork the main net with Ganache-cli using this comand

` ganache-cli --fork http://localhost:8545@11468204`
 
 I get the following output;
 
```
 Ganache CLI v6.12.1 (ganache-core: 2.13.1)
net_version
```

https://gitter.im/ConsenSys/truffle?at=5fdad8f0efa9c806fbd6a66b

## Expected Behavior

I was expecting my 10 accounts to show.

Instead I have the output

`net_version`

And nothing else happen.

I have tried a different port

`ganache-cli --fork http://localhost:8545@11468204 --port 12000`

Then I get an Error;

`Error: The fork provider errored when checking net_version: Invalid JSON RPC response: ""`

How do I select the port to use with Ganache-cli? The port flag seam to try to fork from that port.

## WSL2
* Node v 10.17
* Ganache CLI v6.12.1
* Ubtuntu 
*  Geth/v1.9.25-stable-e7872729/windows-amd64/go1.15.6

**Comment by arushsri515** [comment]
I have this exact same issue

**Comment by Madeindreams** [comment]
> I have this exact same issue

ganache-cli -f  <alchemy api url + KEY> -u <address of an account that has funds>

Grab the accounts and mnemonic. Leave the port as default. This setup is working fine with hardhat.
Alchemy provide an archive state.

**Comment by rayeaster** [comment]
> I have this exact same issue

any solution?
