### ISSUE TITLE
How to use ganache-cli to fork the block specified by the bsc main network?

### ISSUE THREAD

**Issue by 0xwhatly** [ConsenSys-archive/ganache-cli-archive#826]
Hi,I use ganache-cli to fork bsc main network
```
ganache-cli --fork https://bsc-dataseed.binance.org@6727775
```

logs
![image](https://user-images.githubusercontent.com/11549225/115397090-45450c80-a218-11eb-8c36-080b6f215699.png)

**Comment by Code0x2** [comment]
You cant do that on binance provided rpcs. They only open the bare minimum methods for metamask/remix to work for people to send transactions. You'll need to point the fork to your own node or a hosted one for ganache to work

**Comment by 0xwhatly** [comment]
@Code0x2 In fact I can only fork the nearest block use binance provided rpcs. if  i want to fork any block,i must use archive nodes.
