### ISSUE TITLE
Bad web3 code crashes testrpc instance

### ISSUE THREAD

**Issue by redsquirrel** [ConsenSys-archive/ganache-cli-archive#83]
If I run an instance of `testrpc` from the command line, and then run the following script (with the boolean flipped to `false`), the testrpc instance doesn't just return an error, it crashes.

``` javascript
var fs = require('fs');

var Web3 = require('web3');
var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://0.0.0.0:8545'));
web3.eth.defaultAccount = web3.eth.coinbase;

var abi = [{"constant":false,"inputs":[{"name":"x","type":"bytes32"}],"name":"register","outputs":[],"type":"function"}];
var contract = web3.eth.contract(abi);

var encoding;
if (true) encoding = 'utf8'; // turn false to crash testrpc
// single-line file with well-formed address
var address = fs.readFileSync('./fake-address.txt', encoding);

contract.at(address).register("foo", {value: 0, gas: 1000000});
```

I'm reading an address from a file. I forgot to pass in the encoding, so instead of returning a `String` it returns a `Buffer`, feeding that into `contract.at()`. This apparently doesn't play well with testrpc.

**Comment by SilentCicero** [comment]
@redsquirrel I'm also finding web3 is crashing my node. Just handling basic things like contract creation and event listening. On a normal node everything is fine with the identical code.

**Comment by tcoulter** [comment]
Example code would be awesome.

**Comment by tcoulter** [comment]
Fixed here: https://github.com/ethereumjs/testrpc/commit/380ae4ba3bccb72d20e6964d7d40a41488e07500

Will go out with next release.

@SilentCicero If you're having issues with your node dying, please be more specific so I have a chance to reproduce it. Otherwise I'm sitting on my hands guessing what you're running into.

Happy to fix any issues you guys find.

Cheers!
