### ISSUE TITLE
can solidity have console.log()?

### ISSUE THREAD

**Issue by myuniswap2000** [ConsenSys-archive/ganache-cli-archive#843]
Hello, everyone. In Ganache cli, is there anything like hardhat's console. log()?

**Comment by davidmurdoch** [comment]
This is actually an experimental truffle feature. See https://github.com/trufflesuite/truffle-logger-example/issues/3 for info.

I don't think ganache itself could handle solidity features like this, as it doesn't even know about solidity; it deals with EVM OpCodes. If the solidity compiler itself allowed for a special opcode for logging ganache could handle it, but as things are now, there's no easy way to do this.

Perhaps ganache-cli itself could try to intercept/use hardhat's and truffle's console.sol events to log these itself. Is that the behavior you were hoping for?

**Comment by myuniswap2000** [comment]
thank you very much ! I know.
