### ISSUE TITLE
error in  install

### ISSUE THREAD

**Issue by daya135** [ConsenSys-archive/ganache-cli-archive#85]
npm install -g ethereumjs-testrpc
/usr/local/bin/testrpc -> /usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc

> secp256k1@3.1.0 install /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1
> npm run rebuild
> 
> secp256k1@3.1.0 rebuild /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.14"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory`/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1/build'

> sha3@1.2.0 install /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/sha3
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.14"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/sha3/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
  CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
  CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
  CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
  CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
  SOLINK_MODULE(target) Release/obj.target/sha3.node
  COPY Release/sha3.node
make: Leaving directory`/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/sha3/build'
/usr/local/lib
└─┬ ethereumjs-testrpc@2.0.7 
  ├── async@1.5.2 
  ├── bignumber.js@2.3.0 
  ├─┬ bip39@2.2.0 
  │ ├─┬ create-hash@1.1.2 
  │ │ ├── cipher-base@1.0.2 
  │ │ ├── inherits@2.0.1 
  │ │ ├── ripemd160@1.0.1 
  │ │ └── sha.js@2.4.5 
  │ ├─┬ pbkdf2@3.0.4 
  │ │ └── create-hmac@1.1.4 
  │ ├── randombytes@2.0.3 
  │ └── unorm@1.4.1 
  ├─┬ eth-lightwallet@2.3.2 
  │ ├── bignumber.js@2.0.7  (git://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  │ ├─┬ bitcore-lib@0.13.15 
  │ │ ├── bn.js@2.0.4 
  │ │ ├── bs58@2.0.0 
  │ │ ├── buffer-compare@1.0.0 
  │ │ ├─┬ elliptic@3.0.3 
  │ │ │ ├── brorand@1.0.5 
  │ │ │ └── hash.js@1.0.3 
  │ │ ├── inherits@2.0.1 
  │ │ ├── lodash@3.10.1 
  │ │ └── sha512@0.0.1 
  │ ├── bitcore-mnemonic@1.0.1 
  │ ├── crypto-js@3.1.6 
  │ ├─┬ elliptic@3.1.0 
  │ │ ├── bn.js@2.2.0 
  │ │ ├── brorand@1.0.5 
  │ │ └── hash.js@1.0.3 
  │ ├── rlp@2.0.0 
  │ ├── scrypt-async@1.2.0 
  │ └── tweetnacl@0.13.2 
  ├── ethereumjs-account@2.0.2 
  ├─┬ ethereumjs-block@1.2.2 
  │ └── ethereum-common@0.0.16 
  ├─┬ ethereumjs-tx@1.1.1 
  │ └── ethereum-common@0.0.17 
  ├─┬ ethereumjs-util@4.4.0 
  │ ├── bn.js@4.11.3 
  │ ├─┬ keccakjs@0.2.0 
  │ │ ├─┬ browserify-sha3@0.0.1 
  │ │ │ └── js-sha3@0.3.1 
  │ │ └── sha3@1.2.0 
  │ └─┬ secp256k1@3.1.0 
  │   ├── bindings@1.2.1 
  │   ├── bip66@1.1.4 
  │   ├── bn.js@4.11.3 
  │   ├─┬ drbg.js@1.0.1 
  │   │ └─┬ browserify-aes@1.0.6 
  │   │   ├── buffer-xor@1.0.3 
  │   │   └── evp_bytestokey@1.0.0 
  │   ├── elliptic@6.2.3 
  │   └── nan@2.3.3 
  ├─┬ ethereumjs-vm@1.3.0 
  │ ├─┬ async-eventemitter@0.2.2 
  │ │ └── async@0.2.10 
  │ ├── ethereum-common@0.0.16 
  │ └── functional-red-black-tree@1.0.1 
  ├─┬ merkle-patricia-tree@2.1.2 
  │ ├─┬ level-ws@0.0.0 
  │ │ ├─┬ readable-stream@1.0.34 
  │ │ │ └── isarray@0.0.1 
  │ │ └─┬ xtend@2.1.2 
  │ │   └── object-keys@0.4.0 
  │ ├─┬ levelup@1.3.1 
  │ │ ├── deferred-leveldown@1.2.1 
  │ │ ├── level-codec@6.1.0 
  │ │ ├─┬ level-errors@1.0.4 
  │ │ │ └─┬ errno@0.1.4 
  │ │ │   └── prr@0.0.0 
  │ │ ├─┬ level-iterator-stream@1.3.1 
  │ │ │ ├── readable-stream@1.1.14 
  │ │ │ └── xtend@4.0.1 
  │ │ ├── prr@1.0.1 
  │ │ ├── semver@5.1.0 
  │ │ └── xtend@4.0.1 
  │ ├─┬ memdown@1.1.2 
  │ │ ├─┬ abstract-leveldown@2.4.1 
  │ │ │ └── xtend@4.0.1 
  │ │ └── ltgt@1.0.2 
  │ ├─┬ readable-stream@2.1.2 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── isarray@1.0.0 
  │ │ ├── process-nextick-args@1.0.7 
  │ │ ├── string_decoder@0.10.31 
  │ │ └── util-deprecate@1.0.2 
  │ └── semaphore@1.0.5 
  ├── seedrandom@2.4.2 
  ├── shelljs@0.6.0 
  ├─┬ web3@0.15.3 
  │ ├── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  │ ├── utf8@2.1.1 
  │ └── xmlhttprequest@1.8.0 
  ├─┬ web3-provider-engine@7.6.2 
  │ ├─┬ fake-merkle-patricia-tree@1.0.1 
  │ │ └── checkpoint-store@1.1.0 
  │ ├─┬ isomorphic-fetch@2.2.1 
  │ │ ├─┬ node-fetch@1.5.2 
  │ │ │ ├─┬ encoding@0.1.12 
  │ │ │ │ └── iconv-lite@0.4.13 
  │ │ │ └── is-stream@1.1.0 
  │ │ └── whatwg-fetch@1.0.0 
  │ ├─┬ request@2.72.0 
  │ │ ├── aws-sign2@0.6.0 
  │ │ ├── aws4@1.4.1 
  │ │ ├─┬ bl@1.1.2 
  │ │ │ └─┬ readable-stream@2.0.6 
  │ │ │   └── isarray@1.0.0 
  │ │ ├── caseless@0.11.0 
  │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── extend@3.0.0 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├── form-data@1.0.0-rc4 
  │ │ ├─┬ har-validator@2.0.6 
  │ │ │ ├─┬ chalk@1.1.3 
  │ │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ │ ├── has-ansi@2.0.0 
  │ │ │ │ └── supports-color@2.0.0 
  │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ ├─┬ is-my-json-valid@2.13.1 
  │ │ │ │ ├── generate-function@2.0.0 
  │ │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ │ └── is-property@1.0.2 
  │ │ │ │ ├── jsonpointer@2.0.0 
  │ │ │ │ └── xtend@4.0.1 
  │ │ │ └─┬ pinkie-promise@2.0.1 
  │ │ │   └── pinkie@2.0.4 
  │ │ ├─┬ hawk@3.1.3 
  │ │ │ ├── boom@2.10.1 
  │ │ │ ├── cryptiles@2.0.5 
  │ │ │ ├── hoek@2.16.3 
  │ │ │ └── sntp@1.0.9 
  │ │ ├─┬ http-signature@1.1.1 
  │ │ │ ├── assert-plus@0.2.0 
  │ │ │ ├─┬ jsprim@1.2.2 
  │ │ │ │ ├── extsprintf@1.0.2 
  │ │ │ │ ├── json-schema@0.2.2 
  │ │ │ │ └── verror@1.3.6 
  │ │ │ └─┬ sshpk@1.8.3 
  │ │ │   ├── asn1@0.2.3 
  │ │ │   ├── assert-plus@1.0.0 
  │ │ │   ├─┬ dashdash@1.13.1 
  │ │ │   │ └── assert-plus@1.0.0 
  │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │   ├─┬ getpass@0.1.6 
  │ │ │   │ └── assert-plus@1.0.0 
  │ │ │   ├── jodid25519@1.0.2 
  │ │ │   └── jsbn@0.1.0 
  │ │ ├── is-typedarray@1.0.0 
  │ │ ├── isstream@0.1.2 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├─┬ mime-types@2.1.11 
  │ │ │ └── mime-db@1.23.0 
  │ │ ├── node-uuid@1.4.7 
  │ │ ├── oauth-sign@0.8.2 
  │ │ ├── qs@6.1.0 
  │ │ ├── stringstream@0.0.5 
  │ │ ├── tough-cookie@2.2.2 
  │ │ └── tunnel-agent@0.4.3 
  │ ├── solc@0.2.2-2 
  │ ├─┬ tape@4.5.1 
  │ │ ├── deep-equal@1.0.1 
  │ │ ├── defined@1.0.0 
  │ │ ├── function-bind@1.1.0 
  │ │ ├─┬ glob@7.0.3 
  │ │ │ ├─┬ inflight@1.0.4 
  │ │ │ │ └── wrappy@1.0.1 
  │ │ │ ├─┬ minimatch@3.0.0 
  │ │ │ │ └─┬ brace-expansion@1.1.4 
  │ │ │ │   ├── balanced-match@0.4.1 
  │ │ │ │   └── concat-map@0.0.1 
  │ │ │ ├── once@1.3.3 
  │ │ │ └── path-is-absolute@1.0.0 
  │ │ ├── has@1.0.1 
  │ │ ├── minimist@1.2.0 
  │ │ ├── object-inspect@1.1.0 
  │ │ ├── resolve@1.1.7 
  │ │ ├── resumer@0.0.0 
  │ │ ├─┬ string.prototype.trim@1.1.2 
  │ │ │ ├─┬ define-properties@1.1.2 
  │ │ │ │ ├── foreach@2.0.5 
  │ │ │ │ └── object-keys@1.0.9 
  │ │ │ └─┬ es-abstract@1.5.0 
  │ │ │   ├─┬ es-to-primitive@1.1.1 
  │ │ │   │ ├── is-date-object@1.0.1 
  │ │ │   │ └── is-symbol@1.0.1 
  │ │ │   ├── is-callable@1.1.3 
  │ │ │   └── is-regex@1.0.3 
  │ │ └── through@2.3.8 
  │ ├─┬ xhr@2.2.0 
  │ │ ├─┬ global@4.3.0 
  │ │ │ ├─┬ min-document@2.18.0 
  │ │ │ │ └── dom-walk@0.1.1 
  │ │ │ └── process@0.5.2 
  │ │ ├── is-function@1.0.1 
  │ │ ├── once@1.1.1 
  │ │ ├─┬ parse-headers@2.0.1 
  │ │ │ ├── for-each@0.3.2 
  │ │ │ └── trim@0.0.1 
  │ │ └── xtend@4.0.1 
  │ └── xtend@4.0.1 
  └─┬ yargs@3.32.0 
    ├── camelcase@2.1.1 
    ├─┬ cliui@3.2.0 
    │ ├─┬ strip-ansi@3.0.1 
    │ │ └── ansi-regex@2.0.0 
    │ └── wrap-ansi@2.0.0 
    ├── decamelize@1.2.0 
    ├─┬ os-locale@1.4.0 
    │ └─┬ lcid@1.0.0 
    │   └── invert-kv@1.0.0 
    ├─┬ string-width@1.0.1 
    │ ├─┬ code-point-at@1.0.0 
    │ │ └── number-is-nan@1.0.0 
    │ └── is-fullwidth-code-point@1.0.0 
    ├── window-size@0.1.4 
    └── y18n@3.2.1 

root@jiang-ThinkPad:~# testrpc
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/tweetnacl/nacl-fast.js:2152
       throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object Object], use Uint8Array
    at checkArrayTypes (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/tweetnacl/nacl-fast.js:2152:14)
    at Object.nacl.secretbox (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/tweetnacl/nacl-fast.js:2201:3)
    at Function.KeyStore._encryptString (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:113:21)
    at new KeyStore (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:91:29)
    at new Blockchain (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:48:19)
    at new Manager (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:15:21)
    at Object.Server.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:153:19)
    at Object.Server.server (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:23:25)
    at Object.TestRPC.server (/usr/local/lib/node_modules/ethereumjs-testrpc/index.js:23:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc:43:22)
root@jiang-ThinkPad:~#

**Comment by daya135** [comment]
why "root" does not have permission ??

**Comment by daya135** [comment]
root@jiang-ThinkPad:~# npm -v
3.8.9
root@jiang-ThinkPad:~# node -v
v0.12.14

**Comment by jmdfm** [comment]
This is an issue with `node-gyp` on Linux distributions: https://github.com/nodejs/node-gyp/issues/454

Try to follow the guide here: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
