### ISSUE TITLE
Support 'activatePrecompiles' as an option

### ISSUE THREAD

**Issue by axic** [ConsenSys-archive/ganache-cli-archive#88]
See: https://github.com/ethereumjs/ethereumjs-vm/pull/65

Without this option, every testrpc instance behaves like a fresh private network, where no transactions were made with precompiled contracts.  I think this is the desired default behaviour.

With turning on the above option, this changes into a network which had transactions prior with precompiled contracts (i.e. it will be in a very similar state to homestead/morden for the contract developer).

The main difference is that the first contract calling these precompiled contract will incur additional fees and that can confuse developers (e.g. "why does my first call has a different fee than the second?")

**Comment by tcoulter** [comment]
Definitely looking for a feature like this. Only unsolved mystery is how/where to save the chain data. If we do it right, we can save it in the same was a geth, and be able to read from that data as well.

**Comment by axic** [comment]
Oh, you only need to pass an option to the VM constructor: `activatePrecompiles: true` (pending new ethereumjs-vm release)

**Comment by tcoulter** [comment]
For the record (chatted with @axic offline) I misunderstood the PR. This is a good feature, and should be set to true by default, likely without the option to make it false.

**Comment by axic** [comment]
@tcoulter ping! This should go into the next release if possible

**Comment by axic** [comment]
@kumavis does this needs to go into `web3-provider-engine`?

**Comment by tcoulter** [comment]
Probably does too.

FYI: Ping received. I'm on it. In the middle of a big refactor, which it
will be a part of.

On Tue, Jul 26, 2016 at 12:24 PM, Alex Beregszaszi <notifications@github.com

**Comment by tcoulter** [comment]
This has been added to the latest TestRPC: https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain_double.js#L24

Thanks!
