### ISSUE TITLE
getBlock always returns empty list of transactions

### ISSUE THREAD

**Issue by alexhanh** [ConsenSys-archive/ganache-cli-archive#89]
After making successful transaction, `getBlock` seems still to return empty list of transactions.

If I'm not mistaken, this can be traced here https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L283

Is there a mistake how I'm using TestRPC? Or is this by design?

``` javascript
var Web3 = require('web3');
var web3 = new Web3();
var TestRPC = require("ethereumjs-testrpc");
web3.setProvider(TestRPC.provider());

web3.eth.getAccounts((err, accounts) => { 

  const tx = { from: accounts[0], to: accounts[1], value: web3.toWei(1, "ether") };

  // Send transaction automatically increases block number
  web3.eth.sendTransaction(tx, (err, txHash) => {

    web3.eth.getTransaction(txHash, (err, tx) => {
      console.log(tx); // blockNumber: 1
    });

    web3.eth.getBlock(1, (err, block) => {
      console.log(block.transactions); // Returns empty array
    });

  });
});
```

**Comment by redsquirrel** [comment]
I believe what's happening here is that the `sendTransaction` callback is returning with the `txHash`, but the transaction is still pending. Try polling with [getTransactionReceipt](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt) to ensure that the transaction has made it into a block.

**Comment by alexhanh** [comment]
`sendTransaction` ultimately calls `processTransaction`, which instantly creates a new block and adds the tx to the block. https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L495

So it appears calling `sendTransaction` will create a new block and "instant mine" a new block, if you will. Please correct if I'm wrong.

The end result is that the tx is properly added to the block's transactions as well as the blockchain's transaction hash (https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L33)

That's why `getTransactionReceipt` and `getTransaction` will work, but `getBlock` will always return an empty transaction list, because that's what is done here https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L283 (weirdly enough, the solution seems to be commented out)

**Comment by aquabu** [comment]
@alexhanh I'm encountering the same problem. Thanks for pointing this out.

**Comment by alexhanh** [comment]
https://github.com/ethereumjs/testrpc/commit/b3ec03eb8e2615453adcea7a93188ceb578a4094 seems to fix this, closing.
