### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by MrChico** [ConsenSys-archive/ganache-cli-archive#9]
I've been getting a lot of this error lately:

```
eth_getBalance
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:117
    db.get(key, {
      ^

TypeError: Cannot read property 'get' of undefined
    at dbGet (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:117:7)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/util.js:64:5
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/util.js:69:7
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/baseTrie.js:122:9
    at dispatchError (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/node_modules/levelup/lib/util.js:64:35)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/merkle-patricia-tree/node_modules/levelup/lib/levelup.js:222:14

```

This causes testrpc to crash.
I don't know exactly what causes it, because if I restart testrpc and truffle deploy and build my project again it doesn't necessarily happen again. I think it happens when I do a lot of calls at the same time
Seems non-deterministic.

**Comment by tcoulter** [comment]
That's very odd. I haven't seen this error yet myself. If you can do more to track it down I'd appreciate it.

Does it seem reproduceable at all, at least with your app? Or does it seem random?

**Comment by MrChico** [comment]
I haven't been able to reproduce it very effectively, no, but it seems to be happening more often during the start up phase of my dapp, when I am sending a lot of contract.foo.call() requests. With that and the fact that it comes randomly I am thinking that there is some parallelism involved, but otherwise I'm not sure. If I figure out a bit more details on when it happens I will let you know

**Comment by tcoulter** [comment]
@MrChico Can you clone testrpc from master and then do the following to run it:

```
cd ethereumjs-testrpc
./bin/testrpc [-p xxxx]
```

Does the problem still persist? There's been quite a few updates. Would love to know if we inadvertently fixed this.

**Comment by MrChico** [comment]
Pulled the git and with 0.1.1 I still got a crash :/

**Comment by tcoulter** [comment]
This is one of the weirdest errors. You wouldn't have happened to use `npm
link` on ethereumjs-vm awhile back, somehow causing you to use an older
version would you?

**Comment by tcoulter** [comment]
@MrChico This still an issue? Can you test it with the latest v1.1.0 npm release?

**Comment by pirapira** [comment]
@MrChico ?

**Comment by MrChico** [comment]
Have not had this error in a while, so I think this issue can be closed

**Comment by nacmonad** [comment]
i am getting this every 10-20 min on testrpc v4.0.1 (ganache-core:1.0.1)
on ubuntu 16.04

**Comment by skozin** [comment]
Having the same on TestRPC v4.1.3 (ganache-core: 1.1.3) on OS X, Node.js version 8.3.0:

```
eth_getBlockByNumber
eth_getTransactionReceipt
eth_getTransactionByHash
eth_call
TypeError: Cannot read property 'get' of undefined
    at dbGet (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61465:7)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17652:5
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23385:20
    at iterate (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23466:13)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23478:29
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23248:16
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17657:7
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61470:9
    at dispatchError (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:33014:36)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:22881:14
```
