### ISSUE TITLE
deterministic vs mnemonic

### ISSUE THREAD

**Issue by kumavis** [ConsenSys-archive/ganache-cli-archive#91]
whats the difference?

from the readme:

```
-d or --deterministic: Generate deterministic addresses based on a pre-defined mnemonic.
-m or --mnemonic: Use a specific HD wallet mnemonic to generate initial addresses.
```

**Comment by tcoulter** [comment]
- `-d`: Pre-defined mnemonic, but you don't care what it is. i.e., you just care about determinism: 

```
$ testrpc -d
```
- `-m`: You care what the mnemonic is: 

```
$ testrpc -m "dead fish racket soul plunger dirty boats cracker mammal nicholas cage"
```

Both are deterministic, but only in the latter case do the details of that determinism matter to you (and as such, it requires more complex input).

**Comment by kumavis** [comment]
ohhhhh

**Comment by zalesky** [comment]
How to use -m key? example pls
