### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by zach-is-my-name** [ConsenSys-archive/ganache-cli-archive#97]
Can we still install with apt? That worked previously

**Input** 
sudo npm install -g ethereumjs-testrpc
**Output:**

/usr/bin/testrpc -> /usr/lib/node_modules/ethereumjs-testrpc/bin/testrpc

> secp256k1@3.1.0 install /usr/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1
> npm run rebuild
> 
> secp256k1@3.1.0 rebuild /usr/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/zmg/.node-gyp/6.2.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Linux 3.10.18
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Linux 3.10.18
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "rebuild"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.1.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.1.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/ethereumjs-testrpc/node_modules/secp256k1/npm-debug.log
/usr/lib
`-- (empty)

npm ERR! Linux 3.10.18
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ethereumjs-testrpc"  
npm ERR! node v6.2.0  
npm ERR! npm  v3.8.9  
npm ERR! code ELIFECYCLE                                                                                                                                                                        

npm ERR! secp256k1@3.1.0 install: `npm run rebuild`  
npm ERR! Exit status 1  
npm ERR!  
npm ERR! Failed at the secp256k1@3.1.0 install script 'npm run rebuild'.  
npm ERR! Make sure you have the latest version of node.js and npm installed.  
npm ERR! If you do, this is most likely a problem with the secp256k1 package,  
npm ERR! not with npm itself.  
npm ERR! Tell the author that this fails on your system:  
npm ERR!     npm run rebuild  
npm ERR! You can get information on how to open an issue for this project with:  
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zmg/npm-debug.log
npm ERR! code 1

**Comment by zach-is-my-name** [comment]
Resolved! 
Installed NJS optional build tools and it resolved
 https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Still getting output that root does not have sufficient privileges

Also kind of annoying that we can't use stable nodejs off the apt repo. 
Thanks!

**Comment by jmdfm** [comment]
The npm stack trace above in the initial report includes the message: 

> gyp ERR! stack Error: not found: make

`make` is included in the `build-essentials` package, and is pretty much needed if you want to build anything from source, which a fair number of node modules like to do. 

Closing.

**Comment by jbarros35** [comment]
Missing write access to /usr/local/lib/node_modules/ganache-cli
macOS high Sierra
